<script lang="ts" module>
	import type { RxColor } from '$lib/registry/lib/color';
	export interface ColorPickerProps { value?: string; alpha?: boolean; swatches?: string[]; color?: RxColor; size?: 'lg' | 'default' | 'sm'; disabled?: boolean; onValueChange?: (value: string) => void }
</script>
<script lang="ts">
	import { styleColor } from '$lib/registry/lib/color'; import { parseColor, hsvToHex, type HsvColor } from './hsv';
	let { value = $bindable('#3366ff'), alpha = false, swatches = [], color, size = 'default', disabled = false, onValueChange }: ColorPickerProps = $props();
	let initial = parseColor(value) ?? { h: 220, s: .8, v: 1, a: 1 };
	let hsv = $state<HsvColor>(initial), textValue = $state(value), invalid = $state(false);
	const hex = $derived(hsvToHex(hsv, alpha)); const hueColor = $derived(hsvToHex({ h: hsv.h, s: 1, v: 1, a: 1 }));
	$effect(() => { const next = parseColor(value, hsv.h); if (next && value.toLowerCase() !== hex) { hsv = next; textValue = hsvToHex(next, alpha); invalid = false; } });
	function commit(next: HsvColor) { hsv = next; const output = hsvToHex(next, alpha); value = output; textValue = output; invalid = false; onValueChange?.(output); }
	function pointer(node: HTMLElement, update: (x: number, y: number) => void) { const move = (event: PointerEvent) => { const rect = node.getBoundingClientRect(); update(Math.min(1, Math.max(0, (event.clientX - rect.left) / rect.width)), Math.min(1, Math.max(0, (event.clientY - rect.top) / rect.height))); }; const down = (event: PointerEvent) => { if (disabled) return; node.setPointerCapture(event.pointerId); move(event); }; const drag = (event: PointerEvent) => { if (node.hasPointerCapture(event.pointerId)) move(event); }; node.addEventListener('pointerdown', down); node.addEventListener('pointermove', drag); return () => { node.removeEventListener('pointerdown', down); node.removeEventListener('pointermove', drag); }; }
	function key(event: KeyboardEvent, axis: 'h' | 's' | 'v' | 'a') { if (disabled || !['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)) return; event.preventDefault(); const direction = event.key === 'ArrowRight' || event.key === 'ArrowUp' ? 1 : -1; const amount = direction * (event.shiftKey ? 10 : 1); commit({ ...hsv, [axis]: axis === 'h' ? (hsv.h + amount + 360) % 360 : Math.min(1, Math.max(0, hsv[axis] + amount / 100)) }); }
	function textChange(event: Event) { textValue = (event.currentTarget as HTMLInputElement).value; const parsed = parseColor(textValue, hsv.h); if (!parsed) { invalid = true; return; } commit(parsed); }
</script>
<div class="rx-color-picker rx-color-picker--{size}" class:rx-color-picker--disabled={disabled} style={`${styleColor(color) ?? '--rx-color: var(--rx-primary)'}; --picked-hue:${hueColor}`}>
	<div class="rx-color-picker__area" aria-label="Saturation and brightness" role="slider" tabindex={disabled ? -1 : 0} aria-disabled={disabled} aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(hsv.s * 100)} aria-valuetext={`Saturation ${Math.round(hsv.s*100)}%, brightness ${Math.round(hsv.v*100)}%`} onkeydown={(e) => key(e, e.altKey ? 'v' : 's')} {@attach (node) => pointer(node, (x,y) => commit({...hsv,s:x,v:1-y}))}>
		<span class="rx-color-picker__area-knob" style={`left:${hsv.s*100}%;top:${(1-hsv.v)*100}%`}></span>
	</div>
	<div class="rx-color-picker__rail rx-color-picker__hue" role="slider" aria-label="Hue" tabindex={disabled ? -1 : 0} aria-valuemin="0" aria-valuemax="359" aria-valuenow={Math.round(hsv.h)} aria-valuetext={`${Math.round(hsv.h)} degrees`} onkeydown={(e)=>key(e,'h')} {@attach (node) => pointer(node, (x) => commit({...hsv,h:x*359}))}><span style={`left:${hsv.h/359*100}%`}></span></div>
	{#if alpha}<div class="rx-color-picker__rail rx-color-picker__alpha" style={`--picked:${hsvToHex({...hsv,a:1})}`} role="slider" aria-label="Alpha" tabindex={disabled ? -1 : 0} aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(hsv.a*100)} aria-valuetext={`${Math.round(hsv.a*100)}% opacity`} onkeydown={(e)=>key(e,'a')} {@attach (node) => pointer(node, (x) => commit({...hsv,a:x}))}><span style={`left:${hsv.a*100}%`}></span></div>{/if}
	{#if swatches.length}<div class="rx-color-picker__swatches" aria-label="Color presets">{#each swatches as swatch}<button type="button" disabled={disabled} aria-label={`Choose ${swatch}`} style={`background:${swatch}`} onclick={() => { const next=parseColor(swatch,hsv.h); if(next) commit(next); }}></button>{/each}</div>{/if}
	<label class="rx-color-picker__input" class:rx-color-picker__input--invalid={invalid}><span class="rx-color-picker__preview" style={`background:${hex}`}></span><input aria-label="Color value" aria-invalid={invalid} disabled={disabled} value={textValue} oninput={textChange} />{#if invalid}<small role="alert">Enter a valid hex or RGB color.</small>{/if}</label>
</div>
<style>
	.rx-color-picker{width:18rem;display:grid;gap:.75rem;padding:1rem;border:1px solid rgb(var(--rx-text)/.12);border-radius:var(--rx-radius);background:rgb(var(--rx-background));box-shadow:0 8px 28px rgb(var(--rx-dark)/.08)} .rx-color-picker--lg{width:22rem}.rx-color-picker--sm{width:14rem}.rx-color-picker--disabled{opacity:.55}.rx-color-picker__area{position:relative;aspect-ratio:1.65;border-radius:calc(var(--rx-radius)*.8);cursor:crosshair;background:linear-gradient(to top,rgb(var(--rx-dark)),transparent),linear-gradient(to right,rgb(var(--rx-light)),transparent),var(--picked-hue)} .rx-color-picker__area-knob,.rx-color-picker__rail>span{position:absolute;width:1rem;height:1rem;border:3px solid rgb(var(--rx-light));border-radius:50%;box-shadow:0 1px 5px rgb(var(--rx-dark)/.55);transform:translate(-50%,-50%)} .rx-color-picker__area-knob{background:transparent}.rx-color-picker__rail{position:relative;height:.75rem;border-radius:999px;cursor:pointer}.rx-color-picker__rail>span{top:50%;background:rgb(var(--rx-color))}.rx-color-picker__hue{background:linear-gradient(to right,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)}.rx-color-picker__alpha{background:linear-gradient(to right,transparent,var(--picked)),repeating-conic-gradient(rgb(var(--rx-text)/.12) 0 25%,transparent 0 50%) 0/10px 10px}.rx-color-picker__swatches{display:flex;flex-wrap:wrap;gap:.45rem}.rx-color-picker__swatches button{width:1.55rem;height:1.55rem;border:2px solid rgb(var(--rx-light));border-radius:50%;box-shadow:0 0 0 1px rgb(var(--rx-text)/.18);cursor:pointer}.rx-color-picker__input{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:.5rem}.rx-color-picker__input input{min-width:0;padding:.6rem .7rem;border:1px solid rgb(var(--rx-text)/.16);border-radius:calc(var(--rx-radius)*.65);background:transparent;color:rgb(var(--rx-text));font:inherit}.rx-color-picker__preview{width:1.8rem;height:1.8rem;border-radius:.45rem;border:1px solid rgb(var(--rx-text)/.15)}.rx-color-picker__input small{grid-column:1/-1;color:rgb(var(--rx-danger))}.rx-color-picker__input--invalid input{border-color:rgb(var(--rx-danger))}.rx-color-picker :focus-visible{outline:3px solid rgb(var(--rx-color)/.28);outline-offset:2px}@media(prefers-reduced-motion:reduce){.rx-color-picker *{scroll-behavior:auto!important}}
</style>
