<script lang="ts" module>
 import type { Snippet } from 'svelte'; import type { RxColor } from '$lib/registry/lib/color';
 export interface FileTreeNode {id:string;label:string;type:'file'|'directory';children?:FileTreeNode[];disabled?:boolean;icon?:Snippet}
 export interface FileTreeProps {nodes:FileTreeNode[];expanded?:string[];selected?:string;color?:RxColor;variant?:'default'|'compact'|'glow'|'guides'|'highlight'|'reveal';selectionMode?:'single'|'none';onExpandedChange?:(ids:string[])=>void;onSelectedChange?:(id:string|undefined)=>void;onActivate?:(node:FileTreeNode)=>void}
</script>
<script lang="ts">
 import { styleColor } from '$lib/registry/lib/color';
 let {nodes,expanded=$bindable([]),selected=$bindable(),color,variant='default',selectionMode='single',onExpandedChange,onSelectedChange,onActivate}:FileTreeProps=$props();
 let tree:HTMLElement;
 const flat=$derived.by(()=>{const out:{node:FileTreeNode;level:number;parent?:string}[]=[]; const walk=(list:FileTreeNode[],level:number,parent?:string)=>{for(const node of list){out.push({node,level,parent});if(node.type==='directory'&&expanded.includes(node.id))walk(node.children??[],level+1,node.id)}};walk(nodes,1);return out});
 $effect(()=>{const ids:string[]=[];const walk=(xs:FileTreeNode[])=>xs.forEach(n=>{ids.push(n.id);walk(n.children??[])});walk(nodes);const duplicates=ids.filter((id,i)=>ids.indexOf(id)!==i);if(duplicates.length)console.warn(`[FileTree] Node IDs must be unique. Duplicates: ${[...new Set(duplicates)].join(', ')}`)});
 function toggle(node:FileTreeNode){if(node.disabled||node.type!=='directory')return; expanded=expanded.includes(node.id)?expanded.filter(x=>x!==node.id):[...expanded,node.id];onExpandedChange?.(expanded)}
 function selectNode(node:FileTreeNode){if(node.disabled)return;if(selectionMode==='single'){selected=node.id;onSelectedChange?.(node.id)}}
 function activate(node:FileTreeNode){if(node.disabled)return;if(node.type==='directory')toggle(node);onActivate?.(node)}
 function focusAt(i:number){const enabled=flat.filter(x=>!x.node.disabled);enabled[Math.max(0,Math.min(i,enabled.length-1))] && tree.querySelector<HTMLElement>(`[data-id="${CSS.escape(enabled[Math.max(0,Math.min(i,enabled.length-1))].node.id)}"]`)?.focus()}
 function keydown(e:KeyboardEvent,node:FileTreeNode){const enabled=flat.filter(x=>!x.node.disabled);const i=enabled.findIndex(x=>x.node.id===node.id);const entry=flat.find(x=>x.node.id===node.id); if(e.key==='ArrowDown'){e.preventDefault();focusAt(i+1)}else if(e.key==='ArrowUp'){e.preventDefault();focusAt(i-1)}else if(e.key==='Home'){e.preventDefault();focusAt(0)}else if(e.key==='End'){e.preventDefault();focusAt(enabled.length-1)}else if(e.key==='ArrowRight'){e.preventDefault();if(node.type==='directory'&&!expanded.includes(node.id))toggle(node);else if(node.children?.length)tree.querySelector<HTMLElement>(`[data-id="${CSS.escape(node.children.find(x=>!x.disabled)?.id??'')}" ]`)?.focus()}else if(e.key==='ArrowLeft'){e.preventDefault();if(node.type==='directory'&&expanded.includes(node.id))toggle(node);else if(entry?.parent)tree.querySelector<HTMLElement>(`[data-id="${CSS.escape(entry.parent)}"]`)?.focus()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(node);activate(node)}}
</script>
<div bind:this={tree} class="rx-tree rx-tree--{variant}" role="tree" aria-label="Files" style={styleColor(color) ?? '--rx-color: var(--rx-primary)'}>
 {#snippet branch(list:FileTreeNode[],level:number)}{#each list as node (node.id)}<div role="treeitem" aria-level={level} aria-expanded={node.type==='directory'?expanded.includes(node.id):undefined} aria-selected={selectionMode==='single'?selected===node.id:undefined} aria-disabled={node.disabled||undefined} data-id={node.id} tabindex={!node.disabled&&(selected===node.id||(!selected&&flat.find(x=>!x.node.disabled)?.node.id===node.id))?0:-1} class:selected={selected===node.id} class:disabled={node.disabled} onkeydown={(e)=>{e.stopPropagation();keydown(e,node)}} onclick={()=>selectNode(node)} ondblclick={()=>activate(node)}>
  <span class="rx-tree__row" style={`--rx-level:${level}`}><button type="button" tabindex="-1" aria-label={node.type==='directory'?(expanded.includes(node.id)?'Collapse':'Expand'):undefined} disabled={node.disabled||node.type==='file'} onclick={(e)=>{e.stopPropagation();toggle(node)}}>{node.type==='directory'?(expanded.includes(node.id)?'⌄':'›'):''}</button><span class="rx-tree__icon" aria-hidden="true">{#if node.icon}{@render node.icon()}{:else}{node.type==='directory'?'▰':'▱'}{/if}</span><span>{node.label}</span></span>
  {#if node.type==='directory'&&expanded.includes(node.id)&&node.children?.length}<div role="group">{@render branch(node.children,level+1)}</div>{/if}
 </div>{/each}{/snippet}
 {@render branch(nodes,1)}
</div>
<style>.rx-tree{display:grid;color:rgb(var(--rx-text));font-size:.9rem}.rx-tree [role=treeitem]{outline:none}.rx-tree__row{display:flex;align-items:center;gap:.4rem;min-height:2.2rem;padding:.25rem .5rem .25rem calc(.4rem + (var(--rx-level) - 1)*1.15rem);border-radius:.45rem;cursor:pointer}.rx-tree__row button{display:grid;place-items:center;width:1.2rem;border:0;background:transparent;color:inherit}.rx-tree__icon{color:rgb(var(--rx-color))}.rx-tree [role=treeitem]:focus>.rx-tree__row{outline:2px solid rgb(var(--rx-color)/.5)}.rx-tree [role=treeitem].selected>.rx-tree__row{background:rgb(var(--rx-color)/.13);color:rgb(var(--rx-color))}.rx-tree [role=treeitem].disabled>.rx-tree__row{opacity:.45;cursor:not-allowed}.rx-tree--compact .rx-tree__row{min-height:1.7rem}.rx-tree--glow .selected>.rx-tree__row{box-shadow:0 0 1rem rgb(var(--rx-color)/.28)}.rx-tree--guides [role=group]{border-left:1px solid rgb(var(--rx-color)/.25);margin-left:1rem}.rx-tree--highlight [role=treeitem]:hover>.rx-tree__row{background:rgb(var(--rx-color)/.08)}.rx-tree--reveal .rx-tree__icon{opacity:.15;transition:opacity .2s}.rx-tree--reveal .rx-tree__row:hover .rx-tree__icon{opacity:1}@media(prefers-reduced-motion:reduce){.rx-tree__icon{transition-duration:0ms!important}}</style>
