<script lang="ts" module>
 import type { Snippet } from 'svelte'; import type { RxColor } from '$lib/registry/lib/color';
 export interface FileTreeNode {id:string;label:string;type:'file'|'directory';children?:FileTreeNode[];disabled?:boolean;icon?:Snippet}
 export interface FileTreeProps {nodes:FileTreeNode[];expanded?:string[];selected?:string;color?:RxColor;variant?:'default'|'compact'|'glow'|'guides'|'highlight'|'reveal';radius?:'subtle'|'rounded'|'pill'|'squircle';selectionMode?:'single'|'none';disabled?:boolean;ariaLabel?:string;onExpandedChange?:(ids:string[])=>void;onSelectedChange?:(id:string|undefined)=>void;onActivate?:(node:FileTreeNode)=>void}
</script>
<script lang="ts">
 import { styleColor } from '$lib/registry/lib/color';
 let {nodes,expanded=$bindable([]),selected=$bindable(),color,variant='default',radius='rounded',selectionMode='single',disabled=false,ariaLabel='Files',onExpandedChange,onSelectedChange,onActivate}:FileTreeProps=$props();
 let tree:HTMLElement;
 const flat=$derived.by(()=>{const out:{node:FileTreeNode;level:number;parent?:string}[]=[]; const walk=(list:FileTreeNode[],level:number,parent?:string)=>{for(const node of list){out.push({node,level,parent});if(node.type==='directory'&&expanded.includes(node.id))walk(node.children??[],level+1,node.id)}};walk(nodes,1);return out});
 $effect(()=>{const ids:string[]=[];const walk=(xs:FileTreeNode[])=>xs.forEach(n=>{ids.push(n.id);walk(n.children??[])});walk(nodes);const duplicates=ids.filter((id,i)=>ids.indexOf(id)!==i);if(duplicates.length)console.warn(`[FileTree] Node IDs must be unique. Duplicates: ${[...new Set(duplicates)].join(', ')}`)});
 function toggle(node:FileTreeNode){if(node.disabled||node.type!=='directory')return; expanded=expanded.includes(node.id)?expanded.filter(x=>x!==node.id):[...expanded,node.id];onExpandedChange?.(expanded)}
 function selectNode(node:FileTreeNode){if(node.disabled)return;if(selectionMode==='single'){selected=node.id;onSelectedChange?.(node.id)}}
 function activate(node:FileTreeNode){if(node.disabled)return;if(node.type==='directory')toggle(node);onActivate?.(node)}
 function focusAt(i:number){const enabled=flat.filter(x=>!x.node.disabled);enabled[Math.max(0,Math.min(i,enabled.length-1))] && tree.querySelector<HTMLElement>(`[data-id="${CSS.escape(enabled[Math.max(0,Math.min(i,enabled.length-1))].node.id)}"]`)?.focus()}
 function keydown(e:KeyboardEvent,node:FileTreeNode){const enabled=flat.filter(x=>!x.node.disabled);const i=enabled.findIndex(x=>x.node.id===node.id);const entry=flat.find(x=>x.node.id===node.id); if(e.key==='ArrowDown'){e.preventDefault();focusAt(i+1)}else if(e.key==='ArrowUp'){e.preventDefault();focusAt(i-1)}else if(e.key==='Home'){e.preventDefault();focusAt(0)}else if(e.key==='End'){e.preventDefault();focusAt(enabled.length-1)}else if(e.key==='ArrowRight'){e.preventDefault();if(node.type==='directory'&&!expanded.includes(node.id))toggle(node);else if(node.children?.length)tree.querySelector<HTMLElement>(`[data-id="${CSS.escape(node.children.find(x=>!x.disabled)?.id??'')}" ]`)?.focus()}else if(e.key==='ArrowLeft'){e.preventDefault();if(node.type==='directory'&&expanded.includes(node.id))toggle(node);else if(entry?.parent)tree.querySelector<HTMLElement>(`[data-id="${CSS.escape(entry.parent)}"]`)?.focus()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(node);activate(node)}}
 function fidelity(node:HTMLElement){let frame=0;const slider=node.querySelector<HTMLElement>('.rx-tree__slider');const measure=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const row=node.querySelector<HTMLElement>('[role=treeitem][aria-selected=true] > .rx-tree__row');if(!row||!slider){slider?.classList.remove('is-on');return}const body=node.querySelector<HTMLElement>('.rx-tree__body');if(!body)return;slider.style.width=`${row.offsetWidth}px`;slider.style.height=`${row.offsetHeight}px`;slider.style.transform=`translate3d(${row.offsetLeft}px,${row.offsetTop}px,0)`;slider.classList.add('is-on')})};const move=(e:PointerEvent)=>{const rect=node.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;node.style.setProperty('--rx-gx',`${x}px`);node.style.setProperty('--rx-gy',`${y}px`);node.style.setProperty('--rx-glow','1');const row=(e.target as Element).closest<HTMLElement>('.rx-tree__row');if(row){const rr=row.getBoundingClientRect();row.style.setProperty('--rx-mx',`${e.clientX-rr.left}px`);row.style.setProperty('--rx-my',`${e.clientY-rr.top}px`)}};const leave=()=>node.style.setProperty('--rx-glow','0');const down=(e:PointerEvent)=>{const row=(e.target as Element).closest<HTMLElement>('.rx-tree__row');if(!row)return;const rect=row.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,radius=Math.max(Math.hypot(x,y),Math.hypot(rect.width-x,y),Math.hypot(x,rect.height-y));const ripple=document.createElement('span');ripple.className='rx-tree__ripple';ripple.style.cssText=`left:${x}px;top:${y}px;width:${radius*2}px;height:${radius*2}px`;row.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove(),{once:true})};const ro=new ResizeObserver(measure);ro.observe(node);const mo=new MutationObserver(measure);mo.observe(node,{subtree:true,attributes:true,attributeFilter:['aria-selected','aria-expanded']});node.addEventListener('pointermove',move);node.addEventListener('pointerleave',leave);node.addEventListener('pointerdown',down);measure();return()=>{ro.disconnect();mo.disconnect();node.removeEventListener('pointermove',move);node.removeEventListener('pointerleave',leave);node.removeEventListener('pointerdown',down);cancelAnimationFrame(frame)}}
</script>
<div bind:this={tree} class="rx-tree rx-tree--{variant} rx-tree--r-{radius}" class:is-disabled={disabled} role="tree" aria-label={ariaLabel} aria-disabled={disabled || undefined} style={styleColor(color) ?? '--rx-color: var(--rx-primary)'} {@attach fidelity}>
 <span class="rx-tree__rim" aria-hidden="true"></span><div class="rx-tree__body"><span class="rx-tree__slider" aria-hidden="true"></span>
 {#snippet branch(list:FileTreeNode[],level:number,visible:boolean)}{#each list as node,i (node.id)}<div role="treeitem" aria-level={level} aria-expanded={node.type==='directory'?expanded.includes(node.id):undefined} aria-selected={selectionMode==='single'?selected===node.id:undefined} aria-disabled={node.disabled||undefined} aria-hidden={!visible || undefined} data-id={node.id} tabindex={visible&&!disabled&&!node.disabled&&(selected===node.id||(!selected&&flat.find(x=>!x.node.disabled)?.node.id===node.id))?0:-1} class:selected={selected===node.id} class:disabled={node.disabled} onkeydown={(e)=>{e.stopPropagation();keydown(e,node)}} onclick={()=>selectNode(node)} ondblclick={()=>activate(node)}>
  <span class="rx-tree__row" class:is-reveal={variant==='reveal'} style={`--rx-level:${level};--rx-index:${i}`}>
   {#if variant==='guides'}{#each Array(Math.max(0,level-1)) as _,guide}<span class="rx-tree__guide" class:is-lit={selected===node.id} style={`--rx-guide:${guide}`} aria-hidden="true"></span>{/each}{/if}
   {#if node.type==='directory'}<button class="rx-tree__chevron" class:is-open={expanded.includes(node.id)} type="button" tabindex="-1" aria-label={`${expanded.includes(node.id)?'Collapse':'Expand'} ${node.label}`} disabled={node.disabled} onclick={(e)=>{e.stopPropagation();toggle(node)}}><svg viewBox="0 0 14 14" aria-hidden="true"><path d="m5 3.5 3.5 3.5L5 10.5"/></svg></button>{:else}<span class="rx-tree__chevron is-ghost" aria-hidden="true"></span>{/if}
   <span class="rx-tree__icon" aria-hidden="true">{#if node.icon}{@render node.icon()}{:else if node.type==='directory'}<svg class="rx-tree__folder rx-tree__folder--closed" class:is-on={!expanded.includes(node.id)} viewBox="0 0 18 18"><path d="M2.2 5.2h5l1.4 1.6h7.2v7.7H2.2z"/></svg><svg class="rx-tree__folder rx-tree__folder--open" class:is-on={expanded.includes(node.id)} viewBox="0 0 18 18"><path d="M2.2 6.4h13.6l-1.5 8.1H3.7zM2.7 6.4V4.2h4.6l1.4 1.4"/></svg>{:else}<svg viewBox="0 0 18 18"><path d="M4 2.5h6l4 4v9H4zM10 2.5v4h4"/></svg>{/if}</span><span class="rx-tree__name">{node.label}</span><span class="rx-tree__halo" aria-hidden="true"></span>
  </span>
  {#if node.type==='directory'&&node.children?.length}<div class="rx-tree__collapse" class:is-open={expanded.includes(node.id)} role="group" aria-hidden={!expanded.includes(node.id) || undefined} inert={!expanded.includes(node.id) || undefined}><div class="rx-tree__collapse-inner"><div class="rx-tree__branch">{@render branch(node.children,level+1,visible&&expanded.includes(node.id))}</div></div></div>{/if}
 </div>{/each}{/snippet}
 {@render branch(nodes,1,true)}</div>
</div>
<style>
.rx-tree{--rx-tree-r:14px;position:relative;isolation:isolate;width:100%;max-width:340px;border:1px solid rgb(var(--rx-border));border-radius:var(--rx-tree-r);background:rgb(var(--rx-surface));color:rgb(var(--rx-text));font-size:13.5px}.rx-tree--r-subtle{--rx-tree-r:8px}.rx-tree--r-pill,.rx-tree--r-squircle{--rx-tree-r:22px}.rx-tree.is-disabled{opacity:.55;pointer-events:none}.rx-tree__body{position:relative;padding:8px;overflow:auto;overscroll-behavior:contain}.rx-tree [role=treeitem]{position:relative;z-index:1;outline:none}.rx-tree__row{--rx-mx:50%;--rx-my:50%;position:relative;z-index:1;overflow:hidden;display:flex;align-items:center;gap:8px;width:100%;padding:7px 9px 7px calc(9px + (var(--rx-level) - 1)*11px);border-radius:9px;color:rgb(var(--rx-text));cursor:pointer;user-select:none;transition:color 200ms cubic-bezier(.22,1,.36,1),transform 180ms cubic-bezier(.34,1.56,.64,1),background 160ms ease}.rx-tree [role=treeitem]:focus>.rx-tree__row{outline:2px solid rgb(var(--rx-color)/.7);outline-offset:-2px}.rx-tree [role=treeitem].disabled>.rx-tree__row{opacity:.45;cursor:not-allowed}.rx-tree__name{position:relative;z-index:2;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;opacity:.72;transition:opacity 180ms ease}.rx-tree .selected>.rx-tree__row .rx-tree__name{opacity:1;font-weight:600}.rx-tree__chevron{position:relative;z-index:2;display:inline-flex;flex:0 0 14px;width:14px;height:14px;padding:0;border:0;background:transparent;color:rgb(var(--rx-text-muted));transition:transform 360ms cubic-bezier(.34,1.56,.64,1)}.rx-tree__chevron svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:2.1;stroke-linecap:round;stroke-linejoin:round}.rx-tree__chevron.is-open{transform:rotate(90deg)}.rx-tree__chevron.is-ghost{visibility:hidden}.rx-tree__icon{position:relative;z-index:2;display:inline-flex;flex:0 0 18px;width:18px;height:18px;color:rgb(var(--rx-text-secondary))}.rx-tree__icon>svg{position:absolute;inset:0;width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.rx-tree__folder{opacity:0;filter:blur(3px);transform:scale(.5) rotate(-15deg);transition:opacity 280ms cubic-bezier(.22,1,.36,1),transform 400ms cubic-bezier(.25,1.6,.4,1),filter 280ms ease}.rx-tree__folder--open{color:rgb(var(--rx-color));transform:scale(.5) rotate(15deg)}.rx-tree__folder.is-on{opacity:1;filter:blur(0);transform:scale(1) rotate(0)}
.rx-tree__collapse{display:grid;grid-template-rows:0fr;overflow:hidden;transition:grid-template-rows 600ms cubic-bezier(.34,1.8,.42,1)}.rx-tree__collapse.is-open{grid-template-rows:1fr}.rx-tree__collapse-inner{min-height:0;overflow:hidden;opacity:0;filter:blur(14px);transform:translateY(-6px) scale(.97);transform-origin:top;transition:opacity 440ms cubic-bezier(.6,0,.9,.3),filter 460ms cubic-bezier(.4,0,.2,1),transform 480ms cubic-bezier(.22,1.2,.36,1)}.rx-tree__collapse.is-open>.rx-tree__collapse-inner{opacity:1;filter:blur(0);transform:none;transition:opacity 320ms ease 40ms,filter 420ms cubic-bezier(.4,0,.2,1) 40ms,transform 520ms cubic-bezier(.22,1.2,.36,1) 40ms}.rx-tree__branch{position:relative}.rx-tree__slider{position:absolute;left:0;top:0;z-index:0;border-radius:9px;background:rgb(var(--rx-surface-2));backdrop-filter:blur(6px);opacity:0;transform-origin:top left;pointer-events:none;transition:transform 360ms cubic-bezier(.34,1.56,.64,1),width 360ms cubic-bezier(.34,1.56,.64,1),height 360ms cubic-bezier(.34,1.56,.64,1),opacity 200ms ease}.rx-tree__slider.is-on{opacity:1}.rx-tree--highlight .rx-tree__slider{background:rgb(var(--rx-color)/.16);box-shadow:inset 0 0 0 1px rgb(var(--rx-color)/.35);transition-duration:340ms}.rx-tree--compact .rx-tree__body{padding:4px 6px}.rx-tree--compact .rx-tree__row{height:28px;padding-top:0;padding-bottom:0}.rx-tree--compact .rx-tree__slider{left:2px;width:2.5px!important;background:rgb(var(--rx-color));box-shadow:0 0 8px rgb(var(--rx-color));border-radius:999px}
.rx-tree__rim{position:absolute;inset:-1px;z-index:3;border-radius:inherit;padding:1px;background:radial-gradient(90px circle at var(--rx-gx,50%) var(--rx-gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.42) 30%,rgb(var(--rx-color)/.16) 58%,transparent 82%),radial-gradient(260px circle at var(--rx-gx,50%) var(--rx-gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.27) 42%,rgb(var(--rx-color)/.08) 66%,transparent 85%);mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask-composite:exclude;opacity:calc(var(--rx-glow,0)*.6);pointer-events:none;transition:opacity 140ms ease}.rx-tree__halo{position:absolute;inset:0;border-radius:inherit;opacity:0;background:radial-gradient(120px circle at var(--rx-mx) var(--rx-my),rgb(var(--rx-color)/.22),transparent 70%);transition:opacity 200ms ease;pointer-events:none}.rx-tree--glow .rx-tree__row:hover .rx-tree__halo,.rx-tree--glow [role=treeitem]:focus>.rx-tree__row .rx-tree__halo{opacity:1}.rx-tree--glow .rx-tree__row:hover{box-shadow:inset 0 0 0 1px rgb(var(--rx-color)/.4)}.rx-tree--glow .selected>.rx-tree__row{box-shadow:inset 0 0 0 1px rgb(var(--rx-color))}.rx-tree__guide{position:absolute;top:0;bottom:0;left:calc(9px + var(--rx-guide)*11px);width:1.5px;background:rgb(var(--rx-border));transition:background 220ms ease,box-shadow 220ms ease,width 220ms ease}.rx-tree__guide.is-lit{width:2px;background:rgb(var(--rx-color));box-shadow:0 0 6px rgb(var(--rx-color))}:global(.rx-tree__ripple){position:absolute;z-index:1;translate:-50% -50%;border-radius:50%;background:rgb(var(--rx-color)/.14);pointer-events:none;animation:rx-tree-ripple 600ms ease-out forwards}.rx-tree--reveal .rx-tree__row.is-reveal{animation:rx-tree-reveal 420ms cubic-bezier(.22,1,.36,1) both;animation-delay:calc(var(--rx-index)*45ms)}
@keyframes rx-tree-ripple{from{transform:scale(0);opacity:1}to{transform:scale(1);opacity:0}}@keyframes rx-tree-reveal{from{opacity:0;transform:translateX(-10px);filter:blur(4px)}to{opacity:1;transform:none;filter:blur(0)}}
@media(prefers-reduced-motion:reduce){.rx-tree__slider{transition:opacity 160ms ease;backdrop-filter:none}.rx-tree__chevron,.rx-tree__folder,.rx-tree__collapse,.rx-tree__collapse-inner,.rx-tree__row,.rx-tree__guide{transition:none!important}.rx-tree__collapse-inner{filter:none;transform:none}.rx-tree__name{opacity:1}:global(.rx-tree__ripple){display:none}.rx-tree--reveal .rx-tree__row{animation:none}}
</style>
