<script lang="ts" module>
 import type {Snippet} from 'svelte';import type {RxColor} from '$lib/registry/lib/color';export type SortDirection='asc'|'desc';export interface TableColumn<T>{id:string;header:string|Snippet;accessor?:keyof T|((row:T)=>unknown);cell?:(row:T)=>Snippet;sortable?:boolean;width?:string;align?:'left'|'center'|'right'}export interface TableProps<T extends Record<string,unknown>>{data:T[];columns:TableColumn<T>[];rowId:(row:T)=>string;color?:RxColor;variant?:'default'|'bordered'|'cards'|'glow'|'minimal'|'striped';sorting?:{id:string;direction:SortDirection}[];selected?:string[];expanded?:string[];selectable?:boolean;expandable?:boolean;expandedContent?:(row:T)=>Snippet;stickyHeader?:boolean;loading?:boolean;empty?:Snippet;page?:number;pageSize?:number;onSortingChange?:(value:{id:string;direction:SortDirection}[])=>void;onSelectedChange?:(ids:string[])=>void;onExpandedChange?:(ids:string[])=>void;onRowClick?:(row:T)=>void}
</script>
<script lang="ts" generics="T extends Record<string, unknown>">
 import {constructTable,createColumnHelper,createSortedRowModel,createPaginatedRowModel,createExpandedRowModel,rowSortingFeature,rowSelectionFeature,rowExpandingFeature,rowPaginationFeature,tableFeatures,type SortingState,type RowSelectionState,type ExpandedState} from '@tanstack/table-core';import {storeReactivityBindings} from '@tanstack/table-core/store-reactivity-bindings';import {styleColor} from '$lib/registry/lib/color';import {Checkbox} from '../checkbox';import {Skeleton} from '../skeleton';import {Pagination} from '../pagination';
 let{data,columns,rowId,color,variant='default',sorting=$bindable([]),selected=$bindable([]),expanded=$bindable([]),selectable=false,expandable=false,expandedContent,stickyHeader=false,loading=false,empty,page=$bindable(),pageSize,onSortingChange,onSelectedChange,onExpandedChange,onRowClick}:TableProps<T>=$props();
 const features=tableFeatures({coreReactivityFeature:storeReactivityBindings(),rowSortingFeature,rowSelectionFeature,rowExpandingFeature,rowPaginationFeature,sortedRowModel:createSortedRowModel(),expandedRowModel:createExpandedRowModel(),paginatedRowModel:createPaginatedRowModel()});const helper=createColumnHelper<typeof features,T>();const defs=$derived(columns.map(col=>helper.accessor((row:T)=>typeof col.accessor==='function'?col.accessor(row):col.accessor?row[col.accessor]:undefined,{id:col.id,enableSorting:col.sortable??false})));
 const tanSorting=$derived<SortingState>(sorting.map(x=>({id:x.id,desc:x.direction==='desc'})));const rowSelection=$derived<RowSelectionState>(Object.fromEntries(selected.map(id=>[id,true])));const expandedState=$derived<ExpandedState>(Object.fromEntries(expanded.map(id=>[id,true])));const pagination=$derived({pageIndex:Math.max(0,(page??1)-1),pageSize:pageSize??Math.max(1,data.length)});
 const table=$derived(constructTable({features,data,columns:defs,getRowId:rowId,getRowCanExpand:()=>expandable,state:{sorting:tanSorting,rowSelection,expanded:expandedState,pagination},enableRowSelection:selectable,onSortingChange:updater=>{const next=typeof updater==='function'?updater(tanSorting):updater;sorting=next.map(x=>({id:x.id,direction:x.desc?'desc':'asc'}));onSortingChange?.(sorting)},onRowSelectionChange:updater=>{const next=typeof updater==='function'?updater(rowSelection):updater;selected=Object.keys(next).filter(id=>next[id]);onSelectedChange?.(selected)},onExpandedChange:updater=>{const next=typeof updater==='function'?updater(expandedState):updater;expanded=next===true?table.getRowModel().rows.map(row=>row.id):Object.keys(next).filter(id=>next[id]);onExpandedChange?.(expanded)}}));
 function value(row:T,col:TableColumn<T>){if(!col.accessor)return '';return String(typeof col.accessor==='function'?col.accessor(row):row[col.accessor]??'')}
 function sort(col:TableColumn<T>){if(!col.sortable)return;table.getColumn(col.id)?.toggleSorting()}
 function ariaSort(col:TableColumn<T>){const state=sorting.find(x=>x.id===col.id);return state?(state.direction==='asc'?'ascending':'descending'):'none' as const}
 function rowClick(event:MouseEvent,row:T){const target=event.currentTarget as HTMLTableRowElement;if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const rect=target.getBoundingClientRect(),ripple=document.createElement('span');ripple.className='rx-table__ripple';ripple.style.left=`${event.clientX-rect.left}px`;ripple.style.top=`${event.clientY-rect.top}px`;target.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove(),{once:true})}onRowClick?.(row)}
 function illuminate(node:HTMLElement){const move=(event:PointerEvent)=>{const rect=node.getBoundingClientRect();node.style.setProperty('--rx-table-x',`${event.clientX-rect.left}px`);node.style.setProperty('--rx-table-y',`${event.clientY-rect.top}px`);const row=(event.target as Element).closest<HTMLTableRowElement>('tbody tr');if(row){const rr=row.getBoundingClientRect();row.style.setProperty('--rx-row-x',`${event.clientX-rr.left}px`);row.style.setProperty('--rx-row-y',`${event.clientY-rr.top}px`)}};node.addEventListener('pointermove',move,{passive:true});return()=>node.removeEventListener('pointermove',move)}
</script>
<div class="rx-table-wrap rx-table--{variant}" style={styleColor(color)??'--rx-color:var(--rx-primary)'} {@attach illuminate}><table><thead class:sticky={stickyHeader}><tr>{#if selectable}<th class="control"><Checkbox aria-label="Select all rows" checked={table.getIsAllPageRowsSelected()} indeterminate={table.getIsSomePageRowsSelected()} onCheckedChange={(v)=>table.toggleAllPageRowsSelected(v)}/></th>{/if}{#if expandable}<th class="control"><span class="sr-only">Expand</span></th>{/if}{#each columns as col}<th class:sticky={stickyHeader} style:width={col.width} style:text-align={col.align} aria-sort={col.sortable?ariaSort(col):undefined}>{#if col.sortable}<button type="button" onclick={()=>sort(col)}>{#if typeof col.header==='string'}{col.header}{:else}{@render col.header()}{/if}<span class="rx-table__sort" data-sort={ariaSort(col)} aria-hidden="true"><i></i><i></i></span></button>{:else if typeof col.header==='string'}{col.header}{:else}{@render col.header()}{/if}</th>{/each}</tr></thead><tbody>
{#if loading}{#each Array(3) as _}<tr>{#each Array(columns.length+(selectable?1:0)+(expandable?1:0)) as _}<td><Skeleton shape="text"/></td>{/each}</tr>{/each}
{:else if table.getRowModel().rows.length===0}<tr><td colspan={columns.length+(selectable?1:0)+(expandable?1:0)} class="empty">{#if empty}{@render empty()}{:else}No results.{/if}</td></tr>
{:else}{#each table.getRowModel().rows as row (row.id)}<tr class:selected={row.getIsSelected()} onclick={(event)=>rowClick(event,row.original)}>{#if selectable}<td class="control" onclick={(e)=>e.stopPropagation()}><Checkbox aria-label={`Select row ${row.id}`} checked={row.getIsSelected()} onCheckedChange={(v)=>row.toggleSelected(v)}/></td>{/if}{#if expandable}<td class="control"><button type="button" aria-label={`${row.getIsExpanded()?'Collapse':'Expand'} row ${row.id}`} aria-expanded={row.getIsExpanded()} onclick={(e)=>{e.stopPropagation();row.toggleExpanded()}}>›</button></td>{/if}{#each columns as col}<td style:text-align={col.align} data-label={typeof col.header==='string'?col.header:col.id}>{#if col.cell}{@render col.cell(row.original)()}{:else}{value(row.original,col)}{/if}</td>{/each}</tr>{#if expandable&&row.getIsExpanded()&&expandedContent}<tr class="expanded"><td colspan={columns.length+(selectable?1:0)+(expandable?1:0)}>{@render expandedContent(row.original)()}</td></tr>{/if}{/each}{/if}</tbody></table>{#if page!==undefined&&pageSize!==undefined}<Pagination bind:page count={data.length} perPage={pageSize}/>{/if}</div>
<style>
	.rx-table-wrap{position:relative;width:100%;overflow:auto;border-radius:var(--rx-radius)}.rx-table-wrap table{width:100%;border-collapse:collapse;text-align:left}.rx-table-wrap th,.rx-table-wrap td{position:relative;padding:.8rem 1rem;border-bottom:1px solid rgb(var(--rx-text)/.1)}.rx-table-wrap th{font-size:.75rem;text-transform:uppercase;letter-spacing:.04em;color:rgb(var(--rx-text)/.62);background:rgb(var(--rx-surface))}.rx-table-wrap th.sticky{position:sticky;top:0;z-index:2}.rx-table-wrap th button,.rx-table-wrap td.control button{display:inline-flex;align-items:center;gap:6px;border:0;background:transparent;color:inherit;font:inherit;font-weight:700;cursor:pointer}.rx-table-wrap tbody tr{position:relative;overflow:hidden;transition:background 180ms,box-shadow 220ms,transform 220ms cubic-bezier(.34,1.56,.64,1)}.rx-table-wrap tr.selected{background:rgb(var(--rx-color)/.09)}.rx-table-wrap .control{width:2.4rem;padding-left:.5rem;padding-right:.5rem}.rx-table-wrap .empty{text-align:center;padding:3rem;opacity:.6}.rx-table__sort{position:relative;width:9px;height:13px}.rx-table__sort i{position:absolute;left:1px;width:0;height:0;border-inline:4px solid transparent;opacity:.28;transition:opacity 180ms,transform 260ms cubic-bezier(.34,1.56,.64,1)}.rx-table__sort i:first-child{top:0;border-bottom:5px solid currentColor}.rx-table__sort i:last-child{bottom:0;border-top:5px solid currentColor}.rx-table__sort[data-sort=ascending] i:first-child,.rx-table__sort[data-sort=descending] i:last-child{opacity:1;transform:scale(1.22)}:global(.rx-table__ripple){position:absolute;z-index:0;width:14px;height:14px;border-radius:50%;translate:-50% -50%;background:rgb(var(--rx-color)/.2);pointer-events:none;animation:rx-table-ripple 620ms cubic-bezier(.22,1,.36,1) forwards}
	.rx-table--bordered th,.rx-table--bordered td{border:1px solid rgb(var(--rx-text)/.12)}.rx-table--striped tbody tr:nth-child(odd){background:rgb(var(--rx-color)/.045)}.rx-table--striped tbody tr:before{content:"";position:absolute;z-index:1;inset:0 auto 0 0;width:3px;background:rgb(var(--rx-color));transform:scaleY(0);transform-origin:center;transition:transform 260ms cubic-bezier(.34,1.56,.64,1)}.rx-table--striped tbody tr:hover:before,.rx-table--striped tbody tr.selected:before{transform:scaleY(1)}.rx-table--minimal th,.rx-table--minimal td{border:0}.rx-table--minimal td:after{content:"";position:absolute;inset:auto 1rem 5px;height:1px;background:rgb(var(--rx-color));transform:scaleX(0);transform-origin:left;transition:transform 260ms cubic-bezier(.22,1,.36,1)}.rx-table--minimal tr:hover td:after{transform:scaleX(1)}.rx-table--glow:before{content:"";position:absolute;z-index:0;inset:0;background:radial-gradient(280px circle at var(--rx-table-x,50%) var(--rx-table-y,50%),rgb(var(--rx-color)/.13),transparent 75%);pointer-events:none}.rx-table--glow tbody tr:hover{background:radial-gradient(220px circle at var(--rx-row-x,50%) var(--rx-row-y,50%),rgb(var(--rx-color)/.14),transparent 72%);box-shadow:inset 3px 0 rgb(var(--rx-color)/.75),inset -3px 0 rgb(var(--rx-color)/.12)}.rx-table-wrap :global(.rx-pagination){margin-top:1rem}.sr-only{position:absolute;clip:rect(0 0 0 0)}
	@media(max-width:640px){.rx-table--cards table,.rx-table--cards tbody{display:block}.rx-table--cards thead{position:absolute;clip:rect(0 0 0 0)}.rx-table--cards tr{display:grid;margin-bottom:1rem;border-radius:var(--rx-radius);background:rgb(var(--rx-surface));box-shadow:0 4px 14px -10px rgb(var(--rx-shadow)/.6);transition:transform 220ms cubic-bezier(.34,1.56,.64,1),box-shadow 220ms}.rx-table--cards tr:hover{transform:translateY(-3px);box-shadow:0 12px 26px -14px rgb(var(--rx-shadow)/.7)}.rx-table--cards td{display:grid;grid-template-columns:minmax(7rem,.4fr) 1fr;transition:transform 220ms}.rx-table--cards tr:hover td{transform:translateY(-2px)}.rx-table--cards td::before{content:attr(data-label);font-weight:700}}
	@keyframes rx-table-ripple{from{scale:.2;opacity:1}to{scale:38;opacity:0}}@media(prefers-reduced-motion:reduce){.rx-table-wrap :global(*){transition:none!important;animation:none!important}.rx-table--cards tr:hover,.rx-table--cards tr:hover td{transform:none}}
</style>
