<script lang="ts" module>
 import type {Snippet} from 'svelte';import type {RxColor} from '$lib/registry/lib/color';export type SortDirection='asc'|'desc';export interface TableColumn<T>{id:string;header:string|Snippet;accessor?:keyof T|((row:T)=>unknown);cell?:(row:T)=>Snippet;sortable?:boolean;width?:string;align?:'left'|'center'|'right'}export interface TableProps<T extends Record<string,unknown>>{data:T[];columns:TableColumn<T>[];rowId:(row:T)=>string;color?:RxColor;variant?:'default'|'bordered'|'cards'|'glow'|'minimal'|'striped';sorting?:{id:string;direction:SortDirection}[];selected?:string[];expanded?:string[];selectable?:boolean;expandable?:boolean;expandedContent?:(row:T)=>Snippet;stickyHeader?:boolean;loading?:boolean;empty?:Snippet;page?:number;pageSize?:number;onSortingChange?:(value:{id:string;direction:SortDirection}[])=>void;onSelectedChange?:(ids:string[])=>void;onExpandedChange?:(ids:string[])=>void;onRowClick?:(row:T)=>void}
</script>
<script lang="ts" generics="T extends Record<string, unknown>">
 import {constructTable,createColumnHelper,createSortedRowModel,createPaginatedRowModel,createExpandedRowModel,rowSortingFeature,rowSelectionFeature,rowExpandingFeature,rowPaginationFeature,tableFeatures,type SortingState,type RowSelectionState,type ExpandedState} from '@tanstack/table-core';import {storeReactivityBindings} from '@tanstack/table-core/store-reactivity-bindings';import {styleColor} from '$lib/registry/lib/color';import {Checkbox} from '../checkbox';import {Skeleton} from '../skeleton';import {Pagination} from '../pagination';
 let{data,columns,rowId,color,variant='default',sorting=$bindable([]),selected=$bindable([]),expanded=$bindable([]),selectable=false,expandable=false,expandedContent,stickyHeader=false,loading=false,empty,page=$bindable(),pageSize,onSortingChange,onSelectedChange,onExpandedChange,onRowClick}:TableProps<T>=$props();
 const features=tableFeatures({coreReactivityFeature:storeReactivityBindings(),rowSortingFeature,rowSelectionFeature,rowExpandingFeature,rowPaginationFeature,sortedRowModel:createSortedRowModel(),expandedRowModel:createExpandedRowModel(),paginatedRowModel:createPaginatedRowModel()});const helper=createColumnHelper<typeof features,T>();const defs=$derived(columns.map(col=>helper.accessor((row:T)=>typeof col.accessor==='function'?col.accessor(row):col.accessor?row[col.accessor]:undefined,{id:col.id,enableSorting:col.sortable??false})));
 const tanSorting=$derived<SortingState>(sorting.map(x=>({id:x.id,desc:x.direction==='desc'})));const rowSelection=$derived<RowSelectionState>(Object.fromEntries(selected.map(id=>[id,true])));const expandedState=$derived<ExpandedState>(Object.fromEntries(expanded.map(id=>[id,true])));const pagination=$derived({pageIndex:Math.max(0,(page??1)-1),pageSize:pageSize??Math.max(1,data.length)});
 const table=$derived(constructTable({features,data,columns:defs,getRowId:rowId,getRowCanExpand:()=>expandable,state:{sorting:tanSorting,rowSelection,expanded:expandedState,pagination},enableRowSelection:selectable,onSortingChange:updater=>{const next=typeof updater==='function'?updater(tanSorting):updater;sorting=next.map(x=>({id:x.id,direction:x.desc?'desc':'asc'}));onSortingChange?.(sorting)},onRowSelectionChange:updater=>{const next=typeof updater==='function'?updater(rowSelection):updater;selected=Object.keys(next).filter(id=>next[id]);onSelectedChange?.(selected)},onExpandedChange:updater=>{const next=typeof updater==='function'?updater(expandedState):updater;expanded=next===true?table.getRowModel().rows.map(row=>row.id):Object.keys(next).filter(id=>next[id]);onExpandedChange?.(expanded)}}));
 function value(row:T,col:TableColumn<T>){if(!col.accessor)return '';return String(typeof col.accessor==='function'?col.accessor(row):row[col.accessor]??'')}
 function sort(col:TableColumn<T>){if(!col.sortable)return;table.getColumn(col.id)?.toggleSorting()}
 function ariaSort(col:TableColumn<T>){const state=sorting.find(x=>x.id===col.id);return state?(state.direction==='asc'?'ascending':'descending'):'none' as const}
</script>
<div class="rx-table-wrap rx-table--{variant}" style={styleColor(color)??'--rx-color:var(--rx-primary)'}><table><thead class:sticky={stickyHeader}><tr>{#if selectable}<th class="control"><Checkbox aria-label="Select all rows" checked={table.getIsAllPageRowsSelected()} indeterminate={table.getIsSomePageRowsSelected()} onCheckedChange={(v)=>table.toggleAllPageRowsSelected(v)}/></th>{/if}{#if expandable}<th class="control"><span class="sr-only">Expand</span></th>{/if}{#each columns as col}<th class:sticky={stickyHeader} style:width={col.width} style:text-align={col.align} aria-sort={col.sortable?ariaSort(col):undefined}>{#if col.sortable}<button type="button" onclick={()=>sort(col)}>{#if typeof col.header==='string'}{col.header}{:else}{@render col.header()}{/if}<span aria-hidden="true">↕</span></button>{:else if typeof col.header==='string'}{col.header}{:else}{@render col.header()}{/if}</th>{/each}</tr></thead><tbody>
{#if loading}{#each Array(3) as _}<tr>{#each Array(columns.length+(selectable?1:0)+(expandable?1:0)) as _}<td><Skeleton shape="text"/></td>{/each}</tr>{/each}
{:else if table.getRowModel().rows.length===0}<tr><td colspan={columns.length+(selectable?1:0)+(expandable?1:0)} class="empty">{#if empty}{@render empty()}{:else}No results.{/if}</td></tr>
{:else}{#each table.getRowModel().rows as row (row.id)}<tr class:selected={row.getIsSelected()} onclick={()=>onRowClick?.(row.original)}>{#if selectable}<td class="control" onclick={(e)=>e.stopPropagation()}><Checkbox aria-label={`Select row ${row.id}`} checked={row.getIsSelected()} onCheckedChange={(v)=>row.toggleSelected(v)}/></td>{/if}{#if expandable}<td class="control"><button type="button" aria-label={`${row.getIsExpanded()?'Collapse':'Expand'} row ${row.id}`} aria-expanded={row.getIsExpanded()} onclick={(e)=>{e.stopPropagation();row.toggleExpanded()}}>›</button></td>{/if}{#each columns as col}<td style:text-align={col.align} data-label={typeof col.header==='string'?col.header:col.id}>{#if col.cell}{@render col.cell(row.original)()}{:else}{value(row.original,col)}{/if}</td>{/each}</tr>{#if expandable&&row.getIsExpanded()&&expandedContent}<tr class="expanded"><td colspan={columns.length+(selectable?1:0)+(expandable?1:0)}>{@render expandedContent(row.original)()}</td></tr>{/if}{/each}{/if}</tbody></table>{#if page!==undefined&&pageSize!==undefined}<Pagination bind:page count={data.length} perPage={pageSize}/>{/if}</div>
<style>.rx-table-wrap{width:100%;overflow:auto}.rx-table-wrap table{width:100%;border-collapse:collapse;text-align:left}.rx-table-wrap th,.rx-table-wrap td{padding:.8rem 1rem;border-bottom:1px solid rgb(var(--rx-text)/.1)}.rx-table-wrap th{font-size:.75rem;text-transform:uppercase;letter-spacing:.04em;color:rgb(var(--rx-text)/.62);background:rgb(var(--rx-surface))}.rx-table-wrap th.sticky{position:sticky;top:0;z-index:2}.rx-table-wrap th button,.rx-table-wrap td.control button{border:0;background:transparent;color:inherit;font:inherit;font-weight:700;cursor:pointer}.rx-table-wrap tr.selected{background:rgb(var(--rx-color)/.09)}.rx-table-wrap .control{width:2.4rem;padding-left:.5rem;padding-right:.5rem}.rx-table-wrap .empty{text-align:center;padding:3rem;opacity:.6}.rx-table--bordered th,.rx-table--bordered td{border:1px solid rgb(var(--rx-text)/.12)}.rx-table--striped tbody tr:nth-child(odd){background:rgb(var(--rx-color)/.045)}.rx-table--minimal th,.rx-table--minimal td{border:0}.rx-table--glow{border-radius:var(--rx-radius);box-shadow:0 0 1.5rem rgb(var(--rx-color)/.2)}.rx-table-wrap :global(.rx-pagination){margin-top:1rem}.sr-only{position:absolute;clip:rect(0 0 0 0)}@media(max-width:640px){.rx-table--cards table,.rx-table--cards tbody{display:block}.rx-table--cards thead{position:absolute;clip:rect(0 0 0 0)}.rx-table--cards tr{display:grid;margin-bottom:1rem;border-radius:var(--rx-radius);background:rgb(var(--rx-surface));box-shadow:var(--rx-shadow)}.rx-table--cards td{display:grid;grid-template-columns:minmax(7rem,.4fr) 1fr}.rx-table--cards td::before{content:attr(data-label);font-weight:700}}@media(prefers-reduced-motion:reduce){.rx-table-wrap :global(*){transition:none!important}}</style>
