<script lang="ts" module>import type { Snippet } from 'svelte'; export interface AccordionItemProps { value: string; title: string | Snippet; disabled?: boolean; icon?: Snippet; children: Snippet; }</script>
<script lang="ts">
	import { Accordion as Primitive } from 'bits-ui';
	import { getAccordionContext } from './context';
	let { value, title, disabled = false, icon, children }: AccordionItemProps = $props();
	const config = getAccordionContext();
</script>
<Primitive.Item {value} {disabled} class="rx-item" data-variant={config.variant} data-effect={config.effect} data-layout={config.layout}>
	<span class="rx-ring" aria-hidden="true"></span><span class="rx-fill" aria-hidden="true"></span><span class="rx-frost" aria-hidden="true"></span>
	<Primitive.Header class="rx-header">
		<Primitive.Trigger class="rx-trigger">{#if icon}<span class="rx-icon">{@render icon()}</span>{/if}<span class="rx-title">{#if typeof title === 'string'}{title}{:else}{@render title()}{/if}</span>{#if config.effect === 'slide'}<span class="rx-sign" aria-hidden="true"><span class="rx-sign-h"></span><span class="rx-sign-v"></span></span>{:else}<svg class="rx-chevron" aria-hidden="true" viewBox="0 0 20 20"><path d="m5 7.5 5 5 5-5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8"/></svg>{/if}</Primitive.Trigger>
	</Primitive.Header>
	<Primitive.Content class="rx-content"><div class="rx-clip"><div class="rx-inner">{#if config.effect === 'slide'}<span class="rx-accordion-slide-rail" aria-hidden="true"></span><span class="rx-copy">{@render children()}</span>{:else}{@render children()}{/if}</div></div></Primitive.Content>
</Primitive.Item>
<style>
	:global {
	@property --rx-spin{syntax:'<angle>';inherits:false;initial-value:0deg}
	.rx-item{position:relative;overflow:hidden;border:1px solid rgb(var(--rx-border));border-radius:var(--rx-acc-r);background:rgb(var(--rx-surface-2));transform-origin:center top;transition:border-color 240ms ease,transform 420ms cubic-bezier(.34,1.8,.42,1)}
	.rx-item[data-state=open]{border-color:color-mix(in srgb,var(--rx-acc) 45%,rgb(var(--rx-border)))}.rx-item[data-layout=contained]{border:0;border-radius:0;background:transparent}.rx-item[data-layout=contained]+.rx-item{border-top:1px solid rgb(var(--rx-border))}.rx-item[data-layout=line]{border:0;border-bottom:1px solid rgb(var(--rx-border));border-radius:0;background:transparent}
	.rx-header{position:relative;z-index:2;margin:0}.rx-trigger{position:relative;display:flex;width:100%;min-height:var(--rx-acc-h);align-items:center;gap:12px;border:0;padding:calc((var(--rx-acc-h) - 1.3em)/2) var(--rx-acc-pad);text-align:left;color:rgb(var(--rx-text));background:transparent;font:inherit;font-weight:600;cursor:pointer;user-select:none;transition:transform 320ms cubic-bezier(.34,1.8,.42,1),color 200ms ease}.rx-trigger:active:not(:disabled){transform:scale(.985)}.rx-trigger:focus-visible{outline:2px solid var(--rx-acc);outline-offset:-3px}.rx-trigger:disabled{opacity:.45;cursor:not-allowed}.rx-trigger[data-state=open]{color:var(--rx-acc)}.rx-title{z-index:2;flex:1;line-height:1.3}.rx-icon{z-index:2;display:inline-flex;color:var(--rx-acc)}
	.rx-chevron{z-index:2;width:1.2em;height:1.2em;color:rgb(var(--rx-text-muted));transition:transform 540ms cubic-bezier(.34,1.8,.42,1),color 200ms ease}.rx-trigger[data-state=open] .rx-chevron{transform:rotate(180deg);color:var(--rx-acc)}
	.rx-content{position:relative;z-index:2;display:grid;grid-template-rows:0fr;overflow:hidden;animation:none!important;transition:grid-template-rows 600ms cubic-bezier(.34,1.8,.42,1)}.rx-content[data-state=open]{grid-template-rows:1fr}.rx-clip{min-height:0;overflow:hidden}.rx-inner{position:relative;padding:2px var(--rx-acc-pad) calc(var(--rx-acc-h)/3.2);color:rgb(var(--rx-text-muted));line-height:1.55;opacity:0;filter:blur(6px);transform:translateY(-8px);transform-origin:top center;transition:opacity 300ms ease,filter 380ms ease,transform 520ms cubic-bezier(.22,1.2,.36,1)}.rx-content[data-state=open] .rx-inner{opacity:1;filter:blur(0);transform:none;transition-delay:60ms}.rx-item[data-layout=line] .rx-trigger{padding-left:0;padding-right:4px}.rx-item[data-layout=line] .rx-inner{padding-left:0}
	.rx-ring,.rx-fill,.rx-frost{position:absolute;inset:0;border-radius:inherit;pointer-events:none}.rx-ring{inset:-1px;padding:1.5px;background:conic-gradient(from var(--rx-spin,0deg),transparent 0deg,var(--rx-acc) 60deg,transparent 140deg,transparent 360deg);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask-composite:exclude;opacity:0;transition:opacity 300ms ease}.rx-item[data-effect=glow][data-state=open]>.rx-ring{opacity:1;animation:rx-acc-spin 3.2s linear infinite}
	.rx-fill{background:linear-gradient(to top,color-mix(in srgb,var(--rx-acc) 22%,transparent),color-mix(in srgb,var(--rx-acc) 6%,transparent));opacity:0;transform:scaleY(0);transform-origin:bottom;transition:transform 520ms cubic-bezier(.34,1.8,.42,1),opacity 280ms ease}.rx-item[data-variant=filled][data-state=open]>.rx-fill{opacity:1;transform:scaleY(1)}
	.rx-item[data-variant=ghost]{border-color:transparent;background:transparent}.rx-frost{background:color-mix(in srgb,rgb(var(--rx-surface-2)) 55%,transparent);opacity:0;transition:opacity 340ms ease}.rx-item[data-variant=ghost]:hover>.rx-frost{opacity:.7;backdrop-filter:blur(6px) saturate(1.2)}.rx-item[data-variant=ghost][data-state=open]>.rx-frost{opacity:1;backdrop-filter:blur(12px) saturate(1.4)}.rx-item[data-variant=ghost] .rx-inner{transition:opacity 340ms ease,filter 400ms ease}
	.rx-item[data-effect=bounce]:active:not([data-disabled]){transform:scale(.97)}.rx-item[data-effect=bounce] .rx-chevron{transition-duration:520ms}.rx-item[data-effect=bounce] .rx-trigger[data-state=open] .rx-chevron{animation:rx-acc-pop 520ms cubic-bezier(.2,2.2,.35,1)}.rx-item[data-effect=bounce] .rx-content{transition-duration:620ms;transition-timing-function:cubic-bezier(.2,2.2,.35,1)}.rx-item[data-effect=bounce] .rx-inner{transform:translateY(-10px) scale(.96);transition:opacity 300ms ease,transform 560ms cubic-bezier(.2,2.2,.35,1)}.rx-item[data-effect=bounce] .rx-content[data-state=open] .rx-inner{transform:none;transition-delay:70ms}
	.rx-sign{position:relative;flex:0 0 1.1em;width:1.1em;height:1.1em;color:rgb(var(--rx-text-muted));transition:color 200ms ease,transform 500ms cubic-bezier(.34,1.8,.42,1)}.rx-sign-h,.rx-sign-v{position:absolute;left:50%;top:50%;border-radius:2px;background:currentColor;transition:transform 460ms cubic-bezier(.34,1.8,.42,1),opacity 300ms ease}.rx-sign-h{width:.85em;height:2px;transform:translate(-50%,-50%)}.rx-sign-v{width:2px;height:.85em;transform:translate(-50%,-50%)}.rx-trigger[data-state=open] .rx-sign{transform:rotate(180deg);color:var(--rx-acc)}.rx-trigger[data-state=open] .rx-sign-v{opacity:0;transform:translate(-50%,-50%) scaleY(0)}.rx-item[data-effect=slide] .rx-inner{padding-left:calc(var(--rx-acc-pad) + 14px);filter:none;transform:none}.rx-accordion-slide-rail{position:absolute;left:var(--rx-acc-pad);top:4px;bottom:calc(var(--rx-acc-h)/3.2);width:2px;border-radius:2px;background:var(--rx-acc);transform:scaleY(0);transform-origin:top;transition:transform 460ms cubic-bezier(.34,1.8,.42,1)}.rx-copy{display:block;opacity:0;transform:translateX(-18px);transition:opacity 320ms ease,transform 540ms cubic-bezier(.34,1.8,.42,1)}.rx-content[data-state=open] .rx-accordion-slide-rail{transform:scaleY(1)}.rx-content[data-state=open] .rx-copy{opacity:1;transform:none;transition-delay:90ms}.rx-item[data-layout=line] .rx-accordion-slide-rail{left:0}
	@keyframes rx-acc-spin{to{--rx-spin:360deg}}@keyframes rx-acc-pop{0%{scale:.4}60%{scale:1.35}100%{scale:1}}
	@media(prefers-reduced-motion:reduce){.rx-content{transition:none}.rx-chevron,.rx-sign,.rx-sign-h,.rx-sign-v{transition:transform 200ms ease;animation:none!important}.rx-inner{filter:none;transform:none;transition:opacity 200ms ease}.rx-trigger:active,.rx-item[data-effect=bounce]:active{transform:none}.rx-item[data-effect=glow][data-state=open]>.rx-ring{animation:none}.rx-fill{transform:scaleY(1);transition:opacity 200ms ease}.rx-copy{transform:none;transition:opacity 200ms ease}.rx-accordion-slide-rail{transition:none}}
	}
	.rx-inner{color:rgb(var(--rx-text-secondary));opacity:1;transition:filter 380ms ease,transform 520ms cubic-bezier(.22,1.2,.36,1)}
	.rx-copy{opacity:1;transition:transform 540ms cubic-bezier(.34,1.8,.42,1)}
</style>
