<script lang="ts" module>
	import type{Snippet}from'svelte';import type{RxColor}from'$lib/registry/lib/color';
	export type DrawerPlacement='left'|'right'|'top'|'bottom';export type DrawerVariant='base'|'blur'|'bounce'|'glass'|'push'|'slide';export type DrawerFrost='subtle'|'default'|'heavy';export type DrawerBounce='gentle'|'springy';
	export interface DrawerProps{open?:boolean;placement?:DrawerPlacement;variant?:DrawerVariant;size?:string;color?:RxColor;overlay?:boolean;gradient?:boolean;preventClose?:boolean;closeHidden?:boolean;title?:string|Snippet;footer?:Snippet;children:Snippet;trigger?:Snippet;blurAmount?:number;frost?:DrawerFrost;bounce?:DrawerBounce;pushScale?:boolean;slideDepth?:number;onOpenChange?:(open:boolean)=>void}
</script>
<script lang="ts">
	import*as Sheet from'$lib/components/ui/sheet';import{styleColor}from'$lib/registry/lib/color';import{neighborLight}from'$lib/registry/attachments/neighbor-light';
	let{open=$bindable(false),placement='right',variant='base',size='380px',color,overlay=true,gradient=false,preventClose=false,closeHidden=false,title,footer,children,trigger,blurAmount=16,frost='heavy',bounce='gentle',pushScale=true,slideDepth=1,onOpenChange}:DrawerProps=$props();let panelElement=$state<HTMLElement|null>(null);
	const inlineStyle=$derived(`${styleColor(color)??'--rx-color:var(--rx-primary)'};--rx-drawer-size:${size};--rx-drawer-blur:${blurAmount}px;--rx-drawer-depth:${slideDepth};--rx-drawer-bounce:${bounce==='springy'?'820ms':'620ms'}`);
	function changed(value:boolean){open=value;onOpenChange?.(value)}function prevent(event:Event){if(preventClose)event.preventDefault()}
	$effect(()=>{if(!open||variant!=='push'||typeof document==='undefined')return;const moved:Array<{node:HTMLElement;transition:string;transform:string;origin:string}>=[];requestAnimationFrame(()=>{for(const node of Array.from(document.body.children)){if(!(node instanceof HTMLElement)||node.matches('[data-slot=sheet-overlay],[data-slot=sheet-content]')||node.querySelector('.rx-drawer'))continue;moved.push({node,transition:node.style.transition,transform:node.style.transform,origin:node.style.transformOrigin});const delta=placement==='left'?`translateX(${size})`:placement==='right'?`translateX(calc(-1 * ${size}))`:placement==='top'?`translateY(${size})`:`translateY(calc(-1 * ${size}))`;node.style.transition='transform 380ms cubic-bezier(.22,1,.36,1)';node.style.transformOrigin='center';node.style.transform=`${delta}${pushScale?' scale(.94)':''}`}});return()=>{for(const item of moved){item.node.style.transition=item.transition;item.node.style.transform=item.transform;item.node.style.transformOrigin=item.origin}}});
	$effect(()=>{const node=panelElement;if(!node||variant!=='base'||gradient)return;let frame=0;const move=(event:PointerEvent)=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const rect=node.getBoundingClientRect(),x=Math.max(rect.left,Math.min(event.clientX,rect.right)),y=Math.max(rect.top,Math.min(event.clientY,rect.bottom)),glow=Math.max(0,1-Math.hypot(event.clientX-x,event.clientY-y)/280);node.style.setProperty('--gx',`${event.clientX-rect.left}px`);node.style.setProperty('--gy',`${event.clientY-rect.top}px`);node.style.setProperty('--glow',glow.toFixed(3))})};document.addEventListener('pointermove',move,{passive:true});return()=>{document.removeEventListener('pointermove',move);cancelAnimationFrame(frame)}});
	$effect(()=>{const node=panelElement;if(!node||variant!=='base'||gradient)return;const destroy=neighborLight()(node);return typeof destroy==='function'?destroy:undefined});
</script>
<Sheet.Root bind:open onOpenChange={changed}>
	{#if trigger}<Sheet.Trigger class="rx-drawer__trigger">{@render trigger()}</Sheet.Trigger>{/if}
	<Sheet.Content bind:ref={panelElement} side={placement} showCloseButton={!preventClose&&!closeHidden} class={`rx-drawer rx-drawer--${variant} rx-drawer--frost-${frost}${!overlay?' rx-drawer--no-overlay':''}${gradient?' rx-drawer--gradient':''}`} data-rx-lamp style={inlineStyle} onEscapeKeydown={prevent} onInteractOutside={prevent}>
		<span class="rx-drawer__neighbor" aria-hidden="true"></span><span class="rx-drawer__glow" aria-hidden="true"></span><div class="rx-drawer__head">{#if typeof title==='string'}<Sheet.Title>{title}</Sheet.Title>{:else if title}<Sheet.Title>{@render title()}</Sheet.Title>{:else}<Sheet.Title class="sr-only">Drawer</Sheet.Title>{/if}</div><div class="rx-drawer__body">{@render children()}</div>{#if footer}<Sheet.Footer class="rx-drawer__foot">{@render footer()}</Sheet.Footer>{/if}
	</Sheet.Content>
</Sheet.Root>
<style>
	:global(body:has(.rx-drawer--no-overlay) [data-slot=sheet-overlay]),:global(body:has(.rx-drawer--gradient) [data-slot=sheet-overlay]){background:transparent;backdrop-filter:none}:global(body:has(.rx-drawer) [data-slot=sheet-overlay]){background:rgb(var(--rx-dark)/.5);backdrop-filter:blur(4px)}:global(body:has(.rx-drawer) [data-slot=sheet-overlay][data-state=open]){animation:rx-drawer-overlay-in 320ms ease both}:global(body:has(.rx-drawer) [data-slot=sheet-overlay][data-state=closed]){animation:rx-drawer-overlay-out 360ms ease 120ms both}
	:global(.rx-drawer){isolation:isolate;gap:0;border:0!important;border-radius:0;background:rgb(var(--rx-surface));color:rgb(var(--rx-text));box-shadow:0 24px 60px rgb(var(--rx-dark)/.45);overflow:hidden}:global(.rx-drawer[data-side=left]),:global(.rx-drawer[data-side=right]){width:min(calc(100vw - 48px),var(--rx-drawer-size))!important;max-width:none!important;height:100%}:global(.rx-drawer[data-side=top]),:global(.rx-drawer[data-side=bottom]){height:min(calc(100vh - 48px),var(--rx-drawer-size))!important;width:100%;max-height:none}:global(.rx-drawer[data-side=left]){border-right:1px solid rgb(var(--rx-border))!important}:global(.rx-drawer[data-side=right]){border-left:1px solid rgb(var(--rx-border))!important}:global(.rx-drawer[data-side=top]){border-bottom:1px solid rgb(var(--rx-border))!important}:global(.rx-drawer[data-side=bottom]){border-top:1px solid rgb(var(--rx-border))!important}
	:global(.rx-drawer__glow){position:absolute;inset:0;z-index:1;border-radius:inherit;padding:1px;pointer-events:none;background:radial-gradient(90px circle at var(--gx,50%) var(--gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.42) 30%,rgb(var(--rx-color)/.16) 58%,transparent 82%),radial-gradient(280px circle at var(--gx,50%) var(--gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.27) 42%,rgb(var(--rx-color)/.08) 66%,transparent 85%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask-composite:exclude;opacity:calc(var(--glow,0)*.6);transition:opacity 140ms}:global(.rx-drawer:not(.rx-drawer--base) .rx-drawer__glow),:global(.rx-drawer--gradient .rx-drawer__glow){display:none}:global(.rx-drawer__neighbor){position:absolute;inset:-1px;z-index:1;border-radius:inherit;padding:1px;pointer-events:none;background:var(--rx-neighbor-ring,none);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:var(--rx-neighbor-lit,0);transition:opacity 140ms}:global(.rx-drawer__neighbor::after){content:'';position:absolute;inset:1px;border-radius:inherit;background:var(--rx-neighbor-fill,none);opacity:.3}:global(.rx-drawer:not(.rx-drawer--base) .rx-drawer__neighbor),:global(.rx-drawer--gradient .rx-drawer__neighbor){display:none}
	:global(.rx-drawer [data-slot=sheet-close]){z-index:4;top:14px;right:14px;width:30px;height:30px;color:rgb(var(--rx-text));background:transparent}:global(.rx-drawer [data-slot=sheet-close]:hover){background:rgb(var(--rx-text)/.08)}:global(.rx-drawer__head){position:relative;z-index:2;display:flex;min-height:67px;align-items:center;padding:18px 54px 18px 20px;border-bottom:1px solid rgb(var(--rx-border));font-size:16px;font-weight:600}:global(.rx-drawer__body){position:relative;z-index:2;min-height:0;flex:1;overflow-y:auto;padding:20px;color:rgb(var(--rx-text-secondary));font-size:14px;line-height:1.55}:global(.rx-drawer__foot){position:relative;z-index:2;display:flex;flex-direction:row;justify-content:flex-end;gap:10px;padding:16px 20px;border-top:1px solid rgb(var(--rx-border))}
	:global(.rx-drawer--gradient){border:0!important;box-shadow:none;overflow:visible}:global(.rx-drawer--gradient::before){content:'';position:absolute;z-index:-1;pointer-events:none}:global(.rx-drawer--gradient[data-side=right]::before){inset:0 100% 0 auto;width:140px;background:linear-gradient(to left,rgb(var(--rx-surface)),transparent)}:global(.rx-drawer--gradient[data-side=left]::before){inset:0 auto 0 100%;width:140px;background:linear-gradient(to right,rgb(var(--rx-surface)),transparent)}:global(.rx-drawer--gradient[data-side=top]::before){inset:100% 0 auto;height:140px;background:linear-gradient(to bottom,rgb(var(--rx-surface)),transparent)}:global(.rx-drawer--gradient[data-side=bottom]::before){inset:auto 0 100%;height:140px;background:linear-gradient(to top,rgb(var(--rx-surface)),transparent)}
	:global(.rx-drawer--glass){background:rgb(var(--rx-surface)/.48);backdrop-filter:blur(18px) saturate(160%);box-shadow:0 24px 60px rgb(var(--rx-dark)/.4),inset 0 1px 0 rgb(var(--rx-light)/.08)}:global(.rx-drawer--glass.rx-drawer--frost-subtle){background:rgb(var(--rx-surface)/.72);backdrop-filter:blur(10px) saturate(130%)}:global(.rx-drawer--glass.rx-drawer--frost-heavy){background:rgb(var(--rx-surface)/.48);backdrop-filter:blur(24px) saturate(180%)}
	:global(.rx-drawer[data-side=right]){--rx-drawer-from:translateX(100%);--rx-drawer-blur-from:translateX(8%)}:global(.rx-drawer[data-side=left]){--rx-drawer-from:translateX(-100%);--rx-drawer-blur-from:translateX(-8%)}:global(.rx-drawer[data-side=top]){--rx-drawer-from:translateY(-100%);--rx-drawer-blur-from:translateY(-8%)}:global(.rx-drawer[data-side=bottom]){--rx-drawer-from:translateY(100%);--rx-drawer-blur-from:translateY(8%)}
	:global(.rx-drawer--base[data-state=open][data-side=left]),:global(.rx-drawer--base[data-state=open][data-side=right]){animation:rx-drawer-base-transform 440ms cubic-bezier(.22,1,.36,1) both,rx-drawer-base-x-size 560ms cubic-bezier(.34,2.5,.45,1) both}:global(.rx-drawer--base[data-state=open][data-side=top]),:global(.rx-drawer--base[data-state=open][data-side=bottom]){animation:rx-drawer-base-transform 440ms cubic-bezier(.22,1,.36,1) both,rx-drawer-base-y-size 560ms cubic-bezier(.34,2.5,.45,1) both}:global(.rx-drawer--base[data-state=closed][data-side=right]){animation:rx-drawer-wall-right 500ms cubic-bezier(.4,0,.5,1) both}:global(.rx-drawer--base[data-state=closed][data-side=left]){animation:rx-drawer-wall-left 500ms cubic-bezier(.4,0,.5,1) both}:global(.rx-drawer--base[data-state=closed][data-side=top]){animation:rx-drawer-wall-top 500ms cubic-bezier(.4,0,.5,1) both}:global(.rx-drawer--base[data-state=closed][data-side=bottom]){animation:rx-drawer-wall-bottom 500ms cubic-bezier(.4,0,.5,1) both}
	:global(.rx-drawer--bounce[data-state=open][data-side=right]){animation:rx-drawer-bounce-right var(--rx-drawer-bounce) linear both}:global(.rx-drawer--bounce[data-state=open][data-side=left]){animation:rx-drawer-bounce-left var(--rx-drawer-bounce) linear both}:global(.rx-drawer--bounce[data-state=open][data-side=top]){animation:rx-drawer-bounce-top var(--rx-drawer-bounce) linear both}:global(.rx-drawer--bounce[data-state=open][data-side=bottom]){animation:rx-drawer-bounce-bottom var(--rx-drawer-bounce) linear both}:global(.rx-drawer--bounce[data-state=closed]){animation:rx-drawer-leave 300ms cubic-bezier(.4,0,1,1) both}:global(.rx-drawer--blur[data-state=open]){animation:rx-drawer-blur-in 420ms cubic-bezier(.22,1,.36,1) both}:global(.rx-drawer--blur[data-state=closed]){animation:rx-drawer-blur-out 300ms ease both}:global(.rx-drawer--glass[data-state=open]),:global(.rx-drawer--push[data-state=open]){animation:rx-drawer-slide-in 380ms cubic-bezier(.22,1,.36,1) both}:global(.rx-drawer--glass[data-state=closed]),:global(.rx-drawer--push[data-state=closed]){animation:rx-drawer-leave 380ms cubic-bezier(.22,1,.36,1) both}:global(.rx-drawer--slide[data-state=open]){animation:rx-drawer-depth-in 320ms cubic-bezier(.22,1,.36,1) both}:global(.rx-drawer--slide[data-state=closed]){animation:rx-drawer-depth-out 320ms cubic-bezier(.22,1,.36,1) both}
	@keyframes rx-drawer-overlay-in{from{opacity:0}to{opacity:1}}@keyframes rx-drawer-overlay-out{to{opacity:0}}@keyframes rx-drawer-base-transform{from{transform:var(--rx-drawer-from)}to{transform:none}}@keyframes rx-drawer-base-x-size{from{width:300px}to{width:min(calc(100vw - 48px),var(--rx-drawer-size))}}@keyframes rx-drawer-base-y-size{from{height:300px}to{height:min(calc(100vh - 48px),var(--rx-drawer-size))}}@keyframes rx-drawer-wall-right{0%{transform:translateX(0)}60%{transform:translateX(100%)}78%{transform:translateX(90%)}100%{transform:translateX(100%)}}@keyframes rx-drawer-wall-left{0%{transform:translateX(0)}60%{transform:translateX(-100%)}78%{transform:translateX(-90%)}100%{transform:translateX(-100%)}}@keyframes rx-drawer-wall-top{0%{transform:translateY(0)}60%{transform:translateY(-100%)}78%{transform:translateY(-90%)}100%{transform:translateY(-100%)}}@keyframes rx-drawer-wall-bottom{0%{transform:translateY(0)}60%{transform:translateY(100%)}78%{transform:translateY(90%)}100%{transform:translateY(100%)}}@keyframes rx-drawer-bounce-right{0%{transform:translateX(100%)}55%{transform:translateX(-6%)}72%{transform:translateX(3%)}86%{transform:translateX(-1.5%)}100%{transform:none}}@keyframes rx-drawer-bounce-left{0%{transform:translateX(-100%)}55%{transform:translateX(6%)}72%{transform:translateX(-3%)}86%{transform:translateX(1.5%)}100%{transform:none}}@keyframes rx-drawer-bounce-top{0%{transform:translateY(-100%)}55%{transform:translateY(6%)}72%{transform:translateY(-3%)}86%{transform:translateY(1.5%)}100%{transform:none}}@keyframes rx-drawer-bounce-bottom{0%{transform:translateY(100%)}55%{transform:translateY(-6%)}72%{transform:translateY(3%)}86%{transform:translateY(-1.5%)}100%{transform:none}}@keyframes rx-drawer-leave{to{transform:var(--rx-drawer-from)}}@keyframes rx-drawer-blur-in{from{filter:blur(var(--rx-drawer-blur));opacity:0;transform:var(--rx-drawer-blur-from)}to{filter:none;opacity:1;transform:none}}@keyframes rx-drawer-blur-out{to{filter:blur(var(--rx-drawer-blur));opacity:0;transform:var(--rx-drawer-blur-from)}}@keyframes rx-drawer-slide-in{from{opacity:.4;transform:var(--rx-drawer-from)}to{opacity:1;transform:none}}@keyframes rx-drawer-depth-in{from{transform:var(--rx-drawer-from);scale:var(--rx-drawer-depth)}to{transform:none;scale:1}}@keyframes rx-drawer-depth-out{to{transform:var(--rx-drawer-from);scale:var(--rx-drawer-depth)}}
	@media(prefers-reduced-motion:reduce){:global(.rx-drawer),:global(body:has(.rx-drawer) [data-slot=sheet-overlay]){animation-duration:1ms!important;transition-duration:1ms!important;filter:none!important;transform:none!important;scale:1!important}}@media(forced-colors:active){:global(.rx-drawer){border:1px solid CanvasText!important;box-shadow:none}}
</style>
