<script lang="ts" module>
	import type { Snippet } from 'svelte'; import type { RxColor } from '../../lib/color';
	export interface UploadFile { id: string; file: File; status: 'queued' | 'uploading' | 'done' | 'error'; progress: number; previewUrl?: string }
	export interface UploadRejection { file: File; reason: 'size' | 'type' | 'count' }
	export interface UploadProps { files?: UploadFile[]; accept?: string; multiple?: boolean; maxSize?: number; maxFiles?: number; color?: RxColor; disabled?: boolean; label?: string | Snippet; onFilesAdded?: (added: UploadFile[]) => void; onFileRemoved?: (file: UploadFile) => void; onRejected?: (rejections: UploadRejection[]) => void }
</script>
<script lang="ts">
	import { styleColor } from '../../lib/color'; import { RX_DURATION, RX_EASE } from '../../lib/easing';
	let { files = $bindable([]), accept, multiple = false, maxSize, maxFiles, color, disabled = false, label = 'Drop files here or click to browse', onFilesAdded, onFileRemoved, onRejected }: UploadProps = $props();
	let input: HTMLInputElement, dragging = $state(false), message = $state(''), messageTimer: ReturnType<typeof setTimeout> | undefined;
	const ownedUrls = new Set<string>();
	$effect(() => () => { for (const url of ownedUrls) URL.revokeObjectURL(url); ownedUrls.clear(); if (messageTimer) clearTimeout(messageTimer); });
	function accepts(file: File) { if (!accept) return true; return accept.split(',').some((entry) => { const rule=entry.trim().toLowerCase(); const type=file.type.toLowerCase(); const name=file.name.toLowerCase(); return rule.startsWith('.') ? name.endsWith(rule) : rule.endsWith('/*') ? type.startsWith(rule.slice(0,-1)) : type === rule; }); }
	function showRejections(rejections: UploadRejection[]) { if (!rejections.length) return; onRejected?.(rejections); message = rejections.map(({file,reason}) => `${file.name}: ${reason === 'size' ? 'file is too large' : reason === 'type' ? 'unsupported file type' : 'file limit reached'}`).join('. '); if(messageTimer) clearTimeout(messageTimer); messageTimer=setTimeout(()=>message='',4000); }
	function add(selected: File[]) { if (disabled) return; const added: UploadFile[]=[]; const rejected: UploadRejection[]=[]; let available = maxFiles === undefined ? Infinity : Math.max(0,maxFiles-files.length); for (const file of selected) { if(maxSize!==undefined && file.size>maxSize){rejected.push({file,reason:'size'});continue} if(!accepts(file)){rejected.push({file,reason:'type'});continue} if(available<=0 || (!multiple && files.length+added.length>=1)){rejected.push({file,reason:'count'});continue} const previewUrl=file.type.startsWith('image/') ? URL.createObjectURL(file) : undefined; if(previewUrl) ownedUrls.add(previewUrl); added.push({id:globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${added.length}`,file,status:'queued',progress:0,previewUrl}); available--; } if(added.length){files=[...files,...added];onFilesAdded?.(added)} showRejections(rejected); if(input) input.value=''; }
	function remove(item: UploadFile) { files=files.filter((entry)=>entry.id!==item.id); if(item.previewUrl && ownedUrls.delete(item.previewUrl)) URL.revokeObjectURL(item.previewUrl); onFileRemoved?.(item); }
	function drop(event: DragEvent){event.preventDefault();dragging=false;add([...event.dataTransfer?.files ?? []])}
	function zoneKey(event: KeyboardEvent){if(!disabled&&(event.key==='Enter'||event.key===' ')){event.preventDefault();input.click()}}
	const extension=(name:string)=>name.includes('.') ? name.split('.').pop()?.slice(0,5).toUpperCase() : 'FILE';
</script>
<div class="rx-upload" style={`${styleColor(color) ?? '--rx-color: var(--rx-primary)'};--rx-duration:${RX_DURATION.base}ms;--rx-ease:${RX_EASE}`}>
	<input bind:this={input} class="rx-upload__native" type="file" {accept} {multiple} {disabled} onchange={(e)=>add([...(e.currentTarget.files??[])])}/>
	<div class="rx-upload__zone" class:rx-upload__zone--dragging={dragging} class:rx-upload__zone--disabled={disabled} role="button" tabindex={disabled?-1:0} aria-disabled={disabled} onkeydown={zoneKey} onclick={()=>!disabled&&input.click()} ondragover={(e)=>{e.preventDefault();if(!disabled)dragging=true}} ondragleave={()=>dragging=false} ondrop={drop}>
		<span class="rx-upload__icon" aria-hidden="true">↑</span>{#if typeof label === 'string'}<span>{label}</span>{:else}{@render label()}{/if}{#if accept}<small>{accept}</small>{/if}
	</div>
	{#if message}<p class="rx-upload__message" role="alert">{message}</p>{/if}
	{#if files.length}<div class="rx-upload__grid">{#each files as item (item.id)}<article class="rx-upload__file">
		{#if item.previewUrl}<img src={item.previewUrl} alt="" />{:else}<span class="rx-upload__extension">{extension(item.file.name)}</span>{/if}
		<div class="rx-upload__meta"><strong title={item.file.name}>{item.file.name}</strong><small>{(item.file.size/1024).toFixed(1)} KB · {item.status}</small><div class="rx-upload__progress" role="progressbar" aria-label={`${item.file.name} progress`} aria-valuenow={item.progress} aria-valuemin="0" aria-valuemax="100"><span style={`width:${Math.min(100,Math.max(0,item.progress))}%`}></span></div></div>
		<button type="button" aria-label={`Remove ${item.file.name}`} disabled={disabled} onclick={()=>remove(item)}>×</button>
	</article>{/each}</div>{/if}
</div>
<style>
	.rx-upload{display:grid;gap:.8rem}.rx-upload__native{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.rx-upload__zone{display:grid;place-items:center;gap:.35rem;min-height:9rem;padding:1.25rem;border:2px dashed rgb(var(--rx-text)/.2);border-radius:var(--rx-radius);background:rgb(var(--rx-text)/.025);cursor:pointer;text-align:center;transition:border-color var(--rx-duration) var(--rx-ease),box-shadow var(--rx-duration) var(--rx-ease),background var(--rx-duration) var(--rx-ease)}.rx-upload__zone:hover,.rx-upload__zone--dragging{border-color:rgb(var(--rx-color));background:rgb(var(--rx-color)/.07);box-shadow:0 0 0 4px rgb(var(--rx-color)/.12)}.rx-upload__zone:focus-visible{outline:3px solid rgb(var(--rx-color)/.28);outline-offset:2px}.rx-upload__zone--disabled{opacity:.55;cursor:not-allowed}.rx-upload__icon{display:grid;place-items:center;width:2.5rem;height:2.5rem;border-radius:50%;background:rgb(var(--rx-color)/.13);color:rgb(var(--rx-color));font-size:1.5rem;font-weight:700}.rx-upload__zone small{color:rgb(var(--rx-text)/.58)}.rx-upload__message{margin:0;color:rgb(var(--rx-danger));font-size:.85rem}.rx-upload__grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(13rem,1fr));gap:.7rem}.rx-upload__file{position:relative;display:grid;grid-template-columns:3.4rem 1fr auto;align-items:center;gap:.65rem;padding:.65rem;border:1px solid rgb(var(--rx-text)/.1);border-radius:calc(var(--rx-radius)*.8);background:rgb(var(--rx-background));overflow:hidden}.rx-upload__file img,.rx-upload__extension{width:3.4rem;height:3.4rem;border-radius:.55rem;object-fit:cover}.rx-upload__extension{display:grid;place-items:center;background:rgb(var(--rx-color)/.12);color:rgb(var(--rx-color));font-size:.65rem;font-weight:800}.rx-upload__meta{min-width:0;display:grid;gap:.25rem}.rx-upload__meta strong,.rx-upload__meta small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rx-upload__meta small{color:rgb(var(--rx-text)/.58);font-size:.72rem}.rx-upload__progress{height:.3rem;border-radius:999px;background:rgb(var(--rx-text)/.1);overflow:hidden}.rx-upload__progress span{display:block;height:100%;background:rgb(var(--rx-color));transition:width var(--rx-duration) var(--rx-ease)}.rx-upload__file button{align-self:start;border:0;background:transparent;color:rgb(var(--rx-text)/.55);font-size:1.2rem;cursor:pointer}@media(prefers-reduced-motion:reduce){.rx-upload__zone,.rx-upload__progress span{transition-duration:0ms}}
</style>
