<script lang="ts" module>
	import type { Snippet } from 'svelte'; import type { TransitionConfig } from 'svelte/transition'; import type { RxColor } from '$lib/registry/lib/color';
	export interface UploadFile { id: string; file: File; status: 'queued' | 'uploading' | 'done' | 'error'; progress: number; previewUrl?: string }
	export interface UploadRejection { file: File; reason: 'size' | 'type' | 'count' }
	export interface UploadProps { files?: UploadFile[]; accept?: string; multiple?: boolean; maxSize?: number; maxFiles?: number; color?: RxColor; variant?: 'base'|'button'|'compact'|'dropzone'|'gallery'|'glow'; disabled?: boolean; label?: string | Snippet; onFilesAdded?: (added: UploadFile[]) => void; onFileRemoved?: (file: UploadFile) => void; onRejected?: (rejections: UploadRejection[]) => void }
	/** @internal Source entrance geometry without semantic-content opacity fading. */
	export function uploadFileMotion(_node:Element):TransitionConfig{return{duration:400,css:(t)=>`filter:blur(${((1-t)*8).toFixed(2)}px);transform:translateY(${((1-t)*-16).toFixed(2)}px) scale(${(.9+t*.1).toFixed(3)})`}}
</script>
<script lang="ts">
	import { styleColor } from '$lib/registry/lib/color'; import { RX_DURATION, RX_EASE } from '$lib/registry/lib/easing'; import { proximityGlow } from '$lib/registry/attachments/proximity-glow'; import { neighborLight } from '$lib/registry/attachments/neighbor-light';
	let { files = $bindable([]), accept, multiple = false, maxSize, maxFiles, color, variant='base', disabled = false, label = 'Drop files here or click to browse', onFilesAdded, onFileRemoved, onRejected }: UploadProps = $props();
	let input: HTMLInputElement, dragging = $state(false), message = $state(''), messageTimer: ReturnType<typeof setTimeout> | undefined;
	const ownedUrls = new Set<string>();
	const attachGlow = $derived(proximityGlow({ radius: 200, disabled: () => disabled }));
	const attachNeighbor = $derived(neighborLight({ disabled: () => disabled }));
	$effect(() => () => { for (const url of ownedUrls) URL.revokeObjectURL(url); ownedUrls.clear(); if (messageTimer) clearTimeout(messageTimer); });
	function accepts(file: File) { if (!accept) return true; return accept.split(',').some((entry) => { const rule=entry.trim().toLowerCase(); const type=file.type.toLowerCase(); const name=file.name.toLowerCase(); return rule.startsWith('.') ? name.endsWith(rule) : rule.endsWith('/*') ? type.startsWith(rule.slice(0,-1)) : type === rule; }); }
	function showRejections(rejections: UploadRejection[]) { if (!rejections.length) return; onRejected?.(rejections); message = rejections.map(({file,reason}) => `${file.name}: ${reason === 'size' ? 'file is too large' : reason === 'type' ? 'unsupported file type' : 'file limit reached'}`).join('. '); if(messageTimer) clearTimeout(messageTimer); messageTimer=setTimeout(()=>message='',4000); }
	function add(selected: File[]) { if (disabled) return; const added: UploadFile[]=[]; const rejected: UploadRejection[]=[]; let available = maxFiles === undefined ? Infinity : Math.max(0,maxFiles-files.length); for (const file of selected) { if(maxSize!==undefined && file.size>maxSize){rejected.push({file,reason:'size'});continue} if(!accepts(file)){rejected.push({file,reason:'type'});continue} if(available<=0 || (!multiple && files.length+added.length>=1)){rejected.push({file,reason:'count'});continue} const previewUrl=file.type.startsWith('image/') ? URL.createObjectURL(file) : undefined; if(previewUrl) ownedUrls.add(previewUrl); added.push({id:globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${added.length}`,file,status:'queued',progress:0,previewUrl}); available--; } if(added.length){files=[...files,...added];onFilesAdded?.(added)} showRejections(rejected); if(input) input.value=''; }
	function remove(item: UploadFile) { files=files.filter((entry)=>entry.id!==item.id); if(item.previewUrl && ownedUrls.delete(item.previewUrl)) URL.revokeObjectURL(item.previewUrl); onFileRemoved?.(item); }
	function drop(event: DragEvent){event.preventDefault();dragging=false;add([...event.dataTransfer?.files ?? []])}
	function zoneKey(event: KeyboardEvent){if(!disabled&&(event.key==='Enter'||event.key===' ')){event.preventDefault();input.click()}}
	const extension=(name:string)=>name.includes('.') ? name.split('.').pop()?.slice(0,5).toUpperCase() : 'FILE';
</script>
<div class="rx-upload rx-upload--{variant}" class:rx-upload--has-files={files.length>0} style={`${styleColor(color) ?? '--rx-color: var(--rx-primary)'};--rx-duration:${RX_DURATION.base}ms;--rx-ease:${RX_EASE}`} data-rx-lamp {@attach attachGlow} {@attach attachNeighbor}>
	<input bind:this={input} class="rx-upload__native" type="file" {accept} {multiple} {disabled} aria-label="Choose files to upload" onchange={(e)=>add([...(e.currentTarget.files??[])])}/>
	<div class="rx-upload__zone" class:rx-upload__zone--dragging={dragging} class:rx-upload__zone--disabled={disabled} role="button" tabindex={disabled?-1:0} aria-disabled={disabled} onkeydown={zoneKey} onclick={()=>!disabled&&input.click()} ondragover={(e)=>{e.preventDefault();if(!disabled)dragging=true}} ondragleave={()=>dragging=false} ondrop={drop}>
		<span class="rx-upload__pointer-ring" aria-hidden="true"></span><span class="rx-upload__neighbor" aria-hidden="true"></span><span class="rx-upload__orbit" aria-hidden="true"></span><span class="rx-upload__glow-ring" aria-hidden="true"></span><span class="rx-upload__sheen" aria-hidden="true"></span>
		<span class="rx-upload__icon" aria-hidden="true">↑</span>{#if typeof label === 'string'}<span>{label}</span>{:else}{@render label()}{/if}{#if accept}<small>{accept}</small>{/if}
	</div>
	{#if message}<p class="rx-upload__message" role="alert">{message}</p>{/if}
	{#if files.length}<div class="rx-upload__grid">{#each files as item (item.id)}<article class="rx-upload__file" transition:uploadFileMotion>
		{#if item.previewUrl}<img src={item.previewUrl} alt="" />{:else}<span class="rx-upload__extension" style="color:hsl(from rgb(var(--rx-color)) h s min(l, 28%))">{extension(item.file.name)}</span>{/if}
		<div class="rx-upload__meta"><strong title={item.file.name}>{item.file.name}</strong><small style="color:rgb(var(--rx-text) / .78)">{(item.file.size/1024).toFixed(1)} KB · {item.status}</small><div class="rx-upload__progress" role="progressbar" aria-label={`${item.file.name} progress`} aria-valuenow={item.progress} aria-valuemin="0" aria-valuemax="100"><span style={`width:${Math.min(100,Math.max(0,item.progress))}%`}></span></div></div>
		<button type="button" aria-label={`Remove ${item.file.name}`} disabled={disabled} onclick={()=>remove(item)}>×</button>
	</article>{/each}</div>{/if}
</div>
<style>
	.rx-upload{display:grid;gap:.8rem}.rx-upload__native{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.rx-upload__zone{display:grid;place-items:center;gap:.35rem;min-height:9rem;padding:1.25rem;border:2px dashed rgb(var(--rx-text)/.2);border-radius:var(--rx-radius);background:rgb(var(--rx-text)/.025);cursor:pointer;text-align:center;transition:border-color var(--rx-duration) var(--rx-ease),box-shadow var(--rx-duration) var(--rx-ease),background var(--rx-duration) var(--rx-ease)}.rx-upload__zone:hover,.rx-upload__zone--dragging{border-color:rgb(var(--rx-color));background:rgb(var(--rx-color)/.07);box-shadow:0 0 0 4px rgb(var(--rx-color)/.12)}.rx-upload__zone:focus-visible{outline:3px solid rgb(var(--rx-color)/.28);outline-offset:2px}.rx-upload__zone--disabled{opacity:.55;cursor:not-allowed}.rx-upload__icon{display:grid;place-items:center;width:2.5rem;height:2.5rem;border-radius:50%;background:rgb(var(--rx-color)/.13);color:rgb(var(--rx-color));font-size:1.5rem;font-weight:700}.rx-upload__zone small{color:rgb(var(--rx-text-secondary))}.rx-upload__message{margin:0;color:rgb(var(--rx-danger));font-size:.85rem}.rx-upload__grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(13rem,1fr));gap:.7rem}.rx-upload__file{position:relative;display:grid;grid-template-columns:3.4rem 1fr auto;align-items:center;gap:.65rem;padding:.65rem;border:1px solid rgb(var(--rx-text)/.1);border-radius:calc(var(--rx-radius)*.8);background:rgb(var(--rx-background));overflow:hidden}.rx-upload__file img,.rx-upload__extension{width:3.4rem;height:3.4rem;border-radius:.55rem;object-fit:cover}.rx-upload__extension{display:grid;place-items:center;background:rgb(var(--rx-color)/.12);color:rgb(var(--rx-color));font-size:.65rem;font-weight:800}.rx-upload__meta{min-width:0;display:grid;gap:.25rem}.rx-upload__meta strong,.rx-upload__meta small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rx-upload__meta small{color:rgb(var(--rx-text)/.58);font-size:.72rem}.rx-upload__progress{height:.3rem;border-radius:999px;background:rgb(var(--rx-text)/.1);overflow:hidden}.rx-upload__progress span{display:block;height:100%;background:rgb(var(--rx-color));transition:width var(--rx-duration) var(--rx-ease)}.rx-upload__file button{align-self:start;border:0;background:transparent;color:rgb(var(--rx-text)/.55);font-size:1.2rem;cursor:pointer}@media(prefers-reduced-motion:reduce){.rx-upload__zone,.rx-upload__progress span{transition-duration:0ms}}
	.rx-upload{transition:grid-template-rows 620ms cubic-bezier(.34,1.56,.64,1)}.rx-upload__zone{position:relative;isolation:isolate;overflow:hidden;transition:transform 320ms cubic-bezier(.34,1.56,.64,1),border-color 220ms cubic-bezier(.22,1,.36,1),box-shadow 220ms,background 220ms}.rx-upload__zone:hover{transform:scale(1.012)}.rx-upload__zone:hover .rx-upload__icon{transform:translateY(-4px) scale(1.08)}.rx-upload__icon{position:relative;z-index:2;transition:transform 320ms cubic-bezier(.34,1.56,.64,1)}.rx-upload__zone>span:not(.rx-upload__pointer-ring):not(.rx-upload__orbit):not(.rx-upload__glow-ring):not(.rx-upload__sheen){position:relative;z-index:2}.rx-upload__pointer-ring{position:absolute;inset:-1px;z-index:1;border-radius:inherit;padding:1px;pointer-events:none;background:radial-gradient(60px circle at var(--rx-gx,50%) var(--rx-gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.42) 30%,rgb(var(--rx-color)/.16) 58%,transparent 82%),radial-gradient(200px circle at var(--rx-gx,50%) var(--rx-gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.27) 42%,rgb(var(--rx-color)/.08) 66%,transparent 85%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:calc(var(--rx-glow,0)*.63);transition:opacity 140ms}.rx-upload__grid{animation:rx-upload-list-in 580ms cubic-bezier(.34,1.56,.64,1)}.rx-upload__file{animation:rx-upload-file-in 400ms cubic-bezier(.22,1,.36,1)}@keyframes rx-upload-list-in{from{transform:translateY(-10px)}}@keyframes rx-upload-file-in{from{filter:blur(8px);transform:translateY(-16px) scale(.9)}}
	.rx-upload__neighbor{position:absolute;inset:-1px;z-index:1;border-radius:inherit;padding:1px;pointer-events:none;background:var(--rx-neighbor-ring,none);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:var(--rx-neighbor-lit,0);transition:opacity 140ms}.rx-upload__neighbor::after{content:'';position:absolute;inset:1px;border-radius:inherit;background:var(--rx-neighbor-fill,none);opacity:.3}
	.rx-upload--button .rx-upload__zone{min-height:48px;display:flex;justify-content:center;border:0;background:rgb(var(--rx-color));color:rgb(var(--rx-light));box-shadow:0 3px 12px rgb(var(--rx-color)/.24)}.rx-upload--button .rx-upload__zone:hover{filter:brightness(1.06);box-shadow:0 6px 20px rgb(var(--rx-color)/.4)}.rx-upload__sheen{display:none;position:absolute;inset:0;background:linear-gradient(115deg,transparent 30%,rgb(var(--rx-light)/.35) 50%,transparent 70%);transform:translateX(-120%)}.rx-upload--button .rx-upload__sheen{display:block}.rx-upload--button .rx-upload__zone:hover .rx-upload__sheen{animation:rx-upload-sheen 720ms cubic-bezier(.3,.7,.3,1)}@keyframes rx-upload-sheen{to{transform:translateX(120%)}}
	.rx-upload--compact .rx-upload__zone{min-height:54px;display:flex;justify-content:flex-start;border-style:solid}.rx-upload--compact .rx-upload__icon{width:32px;height:32px}.rx-upload--compact .rx-upload__zone::after{content:'';position:absolute;left:0;bottom:0;width:100%;height:2px;background:rgb(var(--rx-color));transform:scaleX(0);transform-origin:left;transition:transform 320ms cubic-bezier(.22,1,.36,1)}.rx-upload--compact.rx-upload--has-files .rx-upload__zone::after{transform:scaleX(1)}
	.rx-upload__orbit{display:none;position:absolute;width:85%;height:180%;border-radius:50%;background:radial-gradient(closest-side,rgb(var(--rx-color)/.3),transparent 70%);filter:blur(18px);animation:rx-upload-orbit 7s ease-in-out infinite}.rx-upload--dropzone .rx-upload__orbit{display:block}@keyframes rx-upload-orbit{0%,100%{transform:translate(-18%,-12%)}33%{transform:translate(18%,-4%)}66%{transform:translate(-4%,18%)}}.rx-upload--dropzone .rx-upload__zone--dragging{transform:translateY(-2px) scale(1.02);box-shadow:0 0 0 4px rgb(var(--rx-color)/.22)}.rx-upload--dropzone .rx-upload__zone--dragging .rx-upload__icon{transform:translateY(-5px) scale(1.12)}
	.rx-upload--gallery .rx-upload__grid{grid-template-columns:repeat(auto-fill,minmax(8rem,1fr))}.rx-upload--gallery .rx-upload__file{display:flex;min-height:8rem;align-items:flex-end}.rx-upload--gallery .rx-upload__file img{position:absolute;inset:0;width:100%;height:100%}.rx-upload--gallery .rx-upload__file::after{content:'';position:absolute;inset:35% 0 0;background:linear-gradient(to top,rgb(var(--rx-dark)/.75),transparent)}.rx-upload--gallery .rx-upload__meta,.rx-upload--gallery .rx-upload__file button{position:relative;z-index:2;color:rgb(var(--rx-light))}.rx-upload--gallery .rx-upload__file button{opacity:0;transform:translateY(4px) scale(.8);transition:opacity 200ms,transform 200ms}.rx-upload--gallery .rx-upload__file:hover button{opacity:1;transform:none}
	.rx-upload__glow-ring{display:none;position:absolute;inset:0;padding:2px;border-radius:inherit;background:conic-gradient(from var(--glw-a,0deg),transparent 0deg,rgb(var(--rx-color)) 60deg,transparent 140deg,rgb(var(--rx-color)) 220deg,transparent 300deg);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:.5;animation:rx-upload-glow 4s linear infinite}.rx-upload--glow .rx-upload__glow-ring{display:block}.rx-upload--glow .rx-upload__zone--dragging{box-shadow:0 0 34px rgb(var(--rx-color)/.32),inset 0 0 22px rgb(var(--rx-color)/.14)}.rx-upload--glow .rx-upload__zone--dragging .rx-upload__glow-ring{animation-duration:1.333s}@keyframes rx-upload-glow{to{transform:rotate(1turn)}}
	@media(prefers-reduced-motion:reduce){.rx-upload,.rx-upload__zone,.rx-upload__icon,.rx-upload__file,.rx-upload__grid,.rx-upload__progress span{transition-duration:0ms;animation:none}.rx-upload__orbit,.rx-upload__glow-ring,.rx-upload__sheen{animation:none}}
</style>
