<script lang="ts" module>
	import type {Snippet} from 'svelte';
	import type {HTMLAnchorAttributes} from 'svelte/elements';
	import type {RxColor} from '$lib/registry/lib/color';
	export interface NavMenuItem {value?:string;label:string;href?:string;icon?:Snippet;description?:string;children?:NavMenuItem[];content?:Snippet;disabled?:boolean;}
	export interface NavMenuProps {items:NavMenuItem[];value?:string;active?:string;color?:RxColor;variant?:'default'|'glow'|'mega'|'pill'|'spotlight'|'underline';surface?:'solid'|'ghost';tone?:'default'|'danger'|'warn'|'success';radius?:'subtle'|'rounded'|'pill'|'squircle';orientation?:'horizontal'|'vertical';bounce?:number;intensity?:number;stagger?:number;fill?:number;spotlight?:number;thickness?:number;disabled?:boolean;onValueChange?:(value:string)=>void;onSelect?:(item:NavMenuItem)=>void;}
</script>

<script lang="ts">
	import * as NavigationMenu from '$lib/components/ui/navigation-menu/index.js';
	import {styleColor} from '$lib/registry/lib/color';
	let {items,value=$bindable(''),active='',color,variant='default',surface='solid',tone='default',radius='rounded',orientation='horizontal',bounce=.55,intensity=.7,stagger=40,fill=1,spotlight=120,thickness=2,disabled=false,onValueChange,onSelect}:NavMenuProps=$props();
	function changed(next:string){value=next;onValueChange?.(next)}
	const itemValue=(item:NavMenuItem,index:number)=>item.value??`item-${index}`;
	function selected(item:NavMenuItem,event:MouseEvent){if(item.disabled||disabled){event.preventDefault();return}onSelect?.(item)}
	function menuMotion(node:HTMLElement){
		const foundList=node.querySelector<HTMLElement>('[data-rx-nav-list]'),foundIndicator=node.querySelector<HTMLElement>('[data-rx-nav-indicator]');if(!foundList||!foundIndicator)return;const list:HTMLElement=foundList,indicator:HTMLElement=foundIndicator;
		let frame=0,active:HTMLElement|null=null;
		function position(target:HTMLElement|null){if(!target)return;active=target;const outer=list.getBoundingClientRect(),rect=target.getBoundingClientRect();indicator.style.setProperty('--indicator-x',`${rect.left-outer.left}px`);indicator.style.setProperty('--indicator-y',`${rect.top-outer.top}px`);indicator.style.setProperty('--indicator-w',`${rect.width}px`);indicator.style.setProperty('--indicator-h',`${rect.height}px`);indicator.dataset.ready='true'}
		function current(){position(list.querySelector<HTMLElement>('[data-popup-open],[data-open],[data-active="true"]')??active)}
		function over(event:Event){const target=(event.target as Element|null)?.closest<HTMLElement>('.rx-nav__trigger');if(target)position(target);const link=(event.target as Element|null)?.closest<HTMLElement>('.rx-nav__card');if(link){const panel=link.closest<HTMLElement>('.rx-nav__content'),highlight=panel?.querySelector<HTMLElement>('[data-rx-nav-highlight]');if(highlight&&panel){const pr=panel.getBoundingClientRect(),rect=link.getBoundingClientRect();highlight.style.setProperty('--highlight-x',`${rect.left-pr.left}px`);highlight.style.setProperty('--highlight-y',`${rect.top-pr.top}px`);highlight.style.setProperty('--highlight-w',`${rect.width}px`);highlight.style.setProperty('--highlight-h',`${rect.height}px`);highlight.dataset.ready='true'}}}
		function leave(event:Event){if(!node.contains((event as FocusEvent).relatedTarget as Node)){current();node.querySelectorAll<HTMLElement>('[data-rx-nav-highlight]').forEach(layer=>layer.dataset.ready='false')}}
		function move(event:PointerEvent){const root=node.getBoundingClientRect();node.style.setProperty('--pointer-x',`${event.clientX-root.left}px`);node.style.setProperty('--pointer-y',`${event.clientY-root.top}px`);const trigger=(event.target as Element|null)?.closest<HTMLElement>('.rx-nav__trigger');if(trigger){const rect=trigger.getBoundingClientRect();trigger.style.setProperty('--trigger-x',`${event.clientX-rect.left}px`);trigger.style.setProperty('--trigger-y',`${event.clientY-rect.top}px`)}const panel=(event.target as Element|null)?.closest<HTMLElement>('.rx-nav__content');if(panel){const rect=panel.getBoundingClientRect();panel.style.setProperty('--panel-x',`${event.clientX-rect.left}px`);panel.style.setProperty('--panel-y',`${event.clientY-rect.top}px`)}const card=(event.target as Element|null)?.closest<HTMLElement>('.rx-nav__card');if(card){const rect=card.getBoundingClientRect();card.style.setProperty('--link-x',`${event.clientX-rect.left}px`);card.style.setProperty('--link-y',`${event.clientY-rect.top}px`)}}
		function update(){frame=0;current()}
		function queue(){if(!frame)frame=requestAnimationFrame(update)}
		list.addEventListener('pointerover',over);list.addEventListener('focusin',over);node.addEventListener('pointerover',over);node.addEventListener('focusin',over);node.addEventListener('pointermove',move,{passive:true});node.addEventListener('pointerleave',leave);node.addEventListener('focusout',leave);window.addEventListener('resize',queue,{passive:true});const observer=new MutationObserver(queue);observer.observe(node,{subtree:true,attributes:true,attributeFilter:['data-state','data-open','data-popup-open','data-active']});queue();
		return()=>{list.removeEventListener('pointerover',over);list.removeEventListener('focusin',over);node.removeEventListener('pointerover',over);node.removeEventListener('focusin',over);node.removeEventListener('pointermove',move);node.removeEventListener('pointerleave',leave);node.removeEventListener('focusout',leave);window.removeEventListener('resize',queue);observer.disconnect();if(frame)cancelAnimationFrame(frame)}
	}
</script>

<div class="rx-nav__stage rx-nav--{variant} rx-nav--{orientation} rx-nav--{surface} rx-nav--r-{radius} rx-nav--t-{tone}" class:is-disabled={disabled} aria-disabled={disabled?'true':undefined} style={`${styleColor(color)??`--rx-color:var(--rx-${tone==='default'?'primary':tone})`};--rx-nav-spring:cubic-bezier(.34,${Math.min(1.9,1+Math.max(0,Math.min(1,bounce))*.9)},.4,1);--rx-nav-intensity:${Math.max(0,Math.min(1,intensity))};--rx-nav-fill:${Math.max(0,Math.min(1,fill))};--rx-nav-spot:${Math.max(40,spotlight)}px;--rx-nav-bar:${Math.max(1,thickness)}px;--rx-nav-stagger:${Math.max(0,stagger)}ms`} {@attach menuMotion}>
	<NavigationMenu.Root {value} orientation={orientation} onValueChange={changed} class="rx-nav rx-nav--{variant} rx-nav--{orientation}">
		<span class="rx-nav__spotlight" aria-hidden="true"></span><span class="rx-nav__indicator" data-rx-nav-indicator data-ready="false" aria-hidden="true"></span>
		<NavigationMenu.List class="rx-nav__list" data-rx-nav-list>
			{#each items as item,i(item.value??item.label)}<NavigationMenu.Item value={itemValue(item,i)}>
				{#if item.children?.length||item.content}
					<NavigationMenu.Trigger class="rx-nav__trigger" disabled={disabled||item.disabled} data-active={active===itemValue(item,i)?'true':undefined}>{#if item.icon}<span aria-hidden="true">{@render item.icon()}</span>{/if}{item.label}</NavigationMenu.Trigger>
					<NavigationMenu.Content class="rx-nav__content"><span class="rx-nav__panel-glow" aria-hidden="true"></span><span class="rx-nav__highlight" data-rx-nav-highlight data-ready="false" aria-hidden="true"></span>{#if item.content}{@render item.content()}{:else}<ul class="rx-nav__grid">{#each item.children??[] as menuChild,j(menuChild.label)}<li style={`--card-index:${j}`}><NavigationMenu.Link>{#snippet child({props}: {props: HTMLAnchorAttributes})}<a {...props} class="rx-nav__card" href={menuChild.href??'#'} aria-disabled={disabled||menuChild.disabled?'true':undefined} tabindex={disabled||menuChild.disabled?-1:undefined} onclick={(event)=>selected(menuChild,event)}>{#if menuChild.icon}<span class="rx-nav__card-icon" aria-hidden="true">{@render menuChild.icon()}</span>{/if}<strong>{menuChild.label}</strong>{#if menuChild.description}<span>{menuChild.description}</span>{/if}</a>{/snippet}</NavigationMenu.Link></li>{/each}</ul>{/if}</NavigationMenu.Content>
				{:else}<NavigationMenu.Link>{#snippet child({props}: {props: HTMLAnchorAttributes})}<a {...props} class="rx-nav__trigger" href={item.href??'#'} data-active={active===itemValue(item,i)?'true':undefined} aria-disabled={disabled||item.disabled?'true':undefined} tabindex={disabled||item.disabled?-1:undefined} onclick={(event)=>selected(item,event)}>{#if item.icon}<span aria-hidden="true">{@render item.icon()}</span>{/if}{item.label}</a>{/snippet}</NavigationMenu.Link>{/if}
			</NavigationMenu.Item>{/each}
		</NavigationMenu.List>
	</NavigationMenu.Root>
</div>

<style>
	.rx-nav__stage{position:relative;isolation:isolate;padding:5px;border-radius:16px}.rx-nav__spotlight{position:absolute;inset:-1px;z-index:-1;border-radius:inherit;background:radial-gradient(120px circle at var(--pointer-x,50%) var(--pointer-y,50%),rgb(var(--rx-color)/.18),transparent 72%);opacity:0;transition:opacity 180ms}.rx-nav--spotlight:is(:hover,:focus-within)>.rx-nav__spotlight{opacity:1}.rx-nav__indicator{position:absolute;left:var(--indicator-x,0);top:var(--indicator-y,0);z-index:-1;width:var(--indicator-w,0);height:var(--indicator-h,0);border-radius:11px;background:rgb(var(--rx-color)/.1);opacity:0;pointer-events:none;transition:all 420ms linear(0,.01,.055,.16,.31,.48,.65,.79,.9,.972,1.012,1.035,1.041,1.034,1.022,1.01,1.002,.998,1)}.rx-nav__indicator:global([data-ready=true]){opacity:1}
	:global(.rx-nav__list){position:relative;z-index:1;display:flex;gap:3px;margin:0;padding:0;list-style:none}:global(.rx-nav--vertical .rx-nav__list){flex-direction:column}:global(.rx-nav__trigger){position:relative;display:flex;align-items:center;gap:7px;height:40px;padding:0 14px;border:0;border-radius:11px;color:rgb(var(--rx-text)/.66);background:transparent;font:inherit;font-size:14px;text-decoration:none;white-space:nowrap;transition:color 180ms,transform 260ms cubic-bezier(.22,1,.36,1),text-shadow 180ms}:global(.rx-nav__trigger:is(:hover,:focus-visible,[data-popup-open],[data-open])){color:rgb(var(--rx-color));background:transparent;outline:none}:global(.rx-nav__trigger:active){transform:scale(.96)}
	:global([data-slot=navigation-menu-viewport]){border:1px solid rgb(var(--rx-text)/.09);border-radius:16px!important;background:rgb(var(--rx-bg)/.86)!important;box-shadow:0 26px 70px -26px rgb(var(--rx-dark)/.64)!important;backdrop-filter:blur(12px);transform-origin:top center}:global([data-slot=navigation-menu-viewport][data-open]){animation:rx-nav-viewport-in 320ms cubic-bezier(.22,1,.36,1)!important}:global([data-slot=navigation-menu-viewport][data-closed]){animation:rx-nav-viewport-out 260ms cubic-bezier(.4,0,1,1)!important}@keyframes rx-nav-viewport-in{from{opacity:0;transform:scale(.96);filter:blur(10px)}to{opacity:1;transform:none;filter:none}}@keyframes rx-nav-viewport-out{from{opacity:1;transform:none;filter:none}to{opacity:0;transform:scale(.96);filter:blur(10px)}}
	:global(.rx-nav__content){position:relative!important;min-width:20rem;padding:10px!important;background:radial-gradient(320px circle at var(--panel-x,50%) var(--panel-y,30%),rgb(var(--rx-color)/.08),transparent 72%);overflow:hidden!important}:global(.rx-nav__content[data-motion=from-end]){animation:rx-nav-from-end 320ms cubic-bezier(.22,1,.36,1)!important}:global(.rx-nav__content[data-motion=from-start]){animation:rx-nav-from-start 320ms cubic-bezier(.22,1,.36,1)!important}:global(.rx-nav__content[data-motion=to-end]){animation:rx-nav-to-end 260ms cubic-bezier(.4,0,1,1)!important}:global(.rx-nav__content[data-motion=to-start]){animation:rx-nav-to-start 260ms cubic-bezier(.4,0,1,1)!important}@keyframes rx-nav-from-end{from{opacity:0;transform:translateX(34px) scale(.92);filter:blur(10px)}}@keyframes rx-nav-from-start{from{opacity:0;transform:translateX(-34px) scale(.92);filter:blur(10px)}}@keyframes rx-nav-to-end{to{opacity:0;transform:translateX(34px) scale(.92);filter:blur(10px)}}@keyframes rx-nav-to-start{to{opacity:0;transform:translateX(-34px) scale(.92);filter:blur(10px)}}
	.rx-nav__panel-glow{position:absolute;inset:0;pointer-events:none;background:radial-gradient(55% 80% at 50% 0%,rgb(var(--rx-color)/.12),transparent 72%);opacity:0}.rx-nav__highlight{position:absolute;left:var(--highlight-x,0);top:var(--highlight-y,0);width:var(--highlight-w,0);height:var(--highlight-h,0);border:1px solid rgb(var(--rx-color)/.14);border-radius:11px;background:rgb(var(--rx-color)/.075);opacity:0;pointer-events:none;transition:all 360ms cubic-bezier(.22,1,.36,1)}.rx-nav__highlight:global([data-ready=true]){opacity:1}:global(.rx-nav__grid){position:relative;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px;margin:0;padding:0;list-style:none}:global(.rx-nav__grid li){position:relative}:global(.rx-nav__card){position:relative;z-index:1;display:grid;grid-template-columns:auto 1fr;gap:2px 10px;min-height:62px;padding:11px!important;border-radius:11px!important;color:rgb(var(--rx-text));background:transparent!important;text-decoration:none;outline:0}:global(.rx-nav__card>strong){grid-column:2}:global(.rx-nav__card>span:not(.rx-nav__card-icon)){grid-column:2;color:rgb(var(--rx-text)/.55);font-size:12px;line-height:1.35}:global(.rx-nav__card-icon){grid-row:1/3;display:grid;place-items:center;color:rgb(var(--rx-color))}:global(.rx-nav__card:focus-visible){box-shadow:inset 0 0 0 2px rgb(var(--rx-color))}
	.rx-nav--pill>.rx-nav__indicator{background:rgb(var(--rx-color));box-shadow:0 10px 24px -9px rgb(var(--rx-color)/.58)}.rx-nav--pill :global(.rx-nav__trigger:is(:hover,:focus-visible,[data-popup-open],[data-open])){color:var(--rx-color-foreground,rgb(var(--rx-bg)))}.rx-nav--underline>.rx-nav__indicator{top:auto!important;bottom:1px;height:2px!important;border-radius:999px;background:rgb(var(--rx-color));box-shadow:0 0 12px rgb(var(--rx-color)/.55)}.rx-nav--underline :global(.rx-nav__trigger){border-radius:0}.rx-nav--spotlight{border:1px solid rgb(var(--rx-text)/.08);background:rgb(var(--rx-bg)/.68);backdrop-filter:blur(14px)}
	.rx-nav--glow{border:1px solid rgb(var(--rx-color)/.18);background:rgb(var(--rx-color)/.035);box-shadow:inset 0 0 24px rgb(var(--rx-color)/.04)}.rx-nav--glow :global(.rx-nav__trigger:is(:hover,[data-popup-open],[data-open])){text-shadow:0 0 13px rgb(var(--rx-color)/.7)}.rx-nav--glow .rx-nav__panel-glow{opacity:1;animation:rx-nav-breathe 2.4s ease-in-out infinite}@keyframes rx-nav-breathe{50%{opacity:.42;filter:saturate(1.5)}}.rx-nav--mega :global(.rx-nav__content){min-width:min(44rem,90vw)}.rx-nav--mega :global(.rx-nav__grid){grid-template-columns:repeat(3,minmax(0,1fr))}.rx-nav--mega :global(.rx-nav__content[data-motion^=from-] .rx-nav__grid li){animation:rx-nav-card-in 420ms cubic-bezier(.22,1,.36,1) both;animation-delay:calc(var(--card-index)*45ms)}@keyframes rx-nav-card-in{from{opacity:0;transform:translateY(16px) scale(.96);filter:blur(7px)}}
	.rx-nav--r-subtle{--nav-r:10px}.rx-nav--r-rounded{--nav-r:14px}.rx-nav--r-pill,.rx-nav--r-squircle{--nav-r:22px}.rx-nav__stage :global(.rx-nav__trigger){border-radius:var(--nav-r,14px);height:36px}.rx-nav__stage :global([data-slot=navigation-menu-viewport]){border-radius:var(--nav-r,14px)!important;transition:width 420ms var(--rx-nav-spring),height 420ms var(--rx-nav-spring),opacity 220ms ease,transform 420ms var(--rx-nav-spring)}.rx-nav--ghost{border-color:transparent;background:transparent;box-shadow:none}.rx-nav--ghost :global(.rx-nav__list){background:transparent}.rx-nav__stage.is-disabled{opacity:.55;pointer-events:none}
	.rx-nav--glow>.rx-nav__indicator,.rx-nav--mega>.rx-nav__indicator,.rx-nav--spotlight>.rx-nav__indicator{display:none}.rx-nav--pill>.rx-nav__indicator{transition:transform 360ms var(--rx-nav-spring),left 360ms var(--rx-nav-spring),top 360ms var(--rx-nav-spring),width 360ms var(--rx-nav-spring),height 360ms var(--rx-nav-spring),opacity 200ms ease;background:rgb(var(--rx-color)/var(--rx-nav-fill))}.rx-nav--underline>.rx-nav__indicator{height:var(--rx-nav-bar)!important;transition:transform 340ms var(--rx-nav-spring),left 340ms var(--rx-nav-spring),width 340ms var(--rx-nav-spring),opacity 180ms ease}
	.rx-nav--glow :global(.rx-nav__trigger)::before,.rx-nav--glow :global(.rx-nav__trigger)::after{content:'';position:absolute;inset:0;z-index:-1;border-radius:inherit;pointer-events:none;opacity:0}.rx-nav--glow :global(.rx-nav__trigger)::before{background:radial-gradient(circle,rgb(var(--rx-color)/calc(var(--rx-nav-intensity)*.3)),transparent 72%);box-shadow:0 0 calc(12px*var(--rx-nav-intensity)) rgb(var(--rx-color)/.45),inset 0 0 0 1px rgb(var(--rx-color)/.55);transition:opacity 240ms ease}.rx-nav--glow :global(.rx-nav__trigger:is([data-popup-open],[data-open]))::before{opacity:1}.rx-nav--glow :global(.rx-nav__trigger)::after{box-shadow:0 0 calc(22px*var(--rx-nav-intensity)) rgb(var(--rx-color)/.7),inset 0 0 0 1px rgb(var(--rx-color)/.7)}.rx-nav--glow :global(.rx-nav__trigger:is([data-popup-open],[data-open]))::after{animation:rx-nav-breathe 2.4s ease-in-out infinite}
	.rx-nav--spotlight>.rx-nav__spotlight{background:radial-gradient(var(--rx-nav-spot) circle at var(--pointer-x,50%) var(--pointer-y,50%),rgb(var(--rx-color)/.32),transparent 70%)}.rx-nav--spotlight :global(.rx-nav__content){background:radial-gradient(var(--rx-nav-spot) circle at var(--panel-x,50%) var(--panel-y,30%),rgb(var(--rx-color)/.22),transparent 70%)}:global(.rx-nav__card>strong),:global(.rx-nav__card>span:not(.rx-nav__card-icon)){background:radial-gradient(90px circle at var(--link-x,50%) var(--link-y,50%),rgb(var(--rx-text)),rgb(var(--rx-text)) 25%,rgb(var(--rx-text)/.58) 100%);background-clip:text;-webkit-background-clip:text;-webkit-text-fill-color:transparent}
	.rx-nav--mega :global(.rx-nav__content[data-motion^=from-] .rx-nav__grid li){animation-delay:calc(var(--card-index)*var(--rx-nav-stagger))}@keyframes rx-nav-card-in{from{opacity:0;transform:translateY(10px)}}
	.rx-nav--default :global(.rx-nav__content[data-motion=from-end]){animation:rx-nav-from-end 480ms var(--rx-nav-spring)!important}.rx-nav--default :global(.rx-nav__content[data-motion=from-start]){animation:rx-nav-from-start 480ms var(--rx-nav-spring)!important}.rx-nav--default :global(.rx-nav__content[data-motion=to-end]){animation:rx-nav-to-end 420ms var(--rx-nav-spring)!important}.rx-nav--default :global(.rx-nav__content[data-motion=to-start]){animation:rx-nav-to-start 420ms var(--rx-nav-spring)!important}.rx-nav__stage:not(.rx-nav--default,.rx-nav--mega) :global(.rx-nav__content[data-motion=from-end]){animation:rx-nav-simple-from-end 320ms var(--rx-nav-spring)!important}.rx-nav__stage:not(.rx-nav--default,.rx-nav--mega) :global(.rx-nav__content[data-motion=from-start]){animation:rx-nav-simple-from-start 320ms var(--rx-nav-spring)!important}.rx-nav__stage:not(.rx-nav--default,.rx-nav--mega) :global(.rx-nav__content[data-motion=to-end]){animation:rx-nav-simple-to-end 260ms var(--rx-nav-spring)!important}.rx-nav__stage:not(.rx-nav--default,.rx-nav--mega) :global(.rx-nav__content[data-motion=to-start]){animation:rx-nav-simple-to-start 260ms var(--rx-nav-spring)!important}.rx-nav--mega :global(.rx-nav__content[data-motion=from-end]){animation:rx-nav-mega-from-end 340ms var(--rx-nav-spring)!important}.rx-nav--mega :global(.rx-nav__content[data-motion=from-start]){animation:rx-nav-mega-from-start 340ms var(--rx-nav-spring)!important}.rx-nav--mega :global(.rx-nav__content[data-motion=to-end]){animation:rx-nav-mega-to-end 260ms var(--rx-nav-spring)!important}.rx-nav--mega :global(.rx-nav__content[data-motion=to-start]){animation:rx-nav-mega-to-start 260ms var(--rx-nav-spring)!important}@keyframes rx-nav-simple-from-end{from{opacity:0;transform:translateX(24px)}}@keyframes rx-nav-simple-from-start{from{opacity:0;transform:translateX(-24px)}}@keyframes rx-nav-simple-to-end{to{opacity:0;transform:translateX(24px)}}@keyframes rx-nav-simple-to-start{to{opacity:0;transform:translateX(-24px)}}@keyframes rx-nav-mega-from-end{from{opacity:0;transform:translateX(28px)}}@keyframes rx-nav-mega-from-start{from{opacity:0;transform:translateX(-28px)}}@keyframes rx-nav-mega-to-end{to{opacity:0;transform:translateX(28px)}}@keyframes rx-nav-mega-to-start{to{opacity:0;transform:translateX(-28px)}}
	.rx-nav__stage :global(.rx-nav__content){width:min(27.5rem,90vw);min-width:0}.rx-nav--mega :global(.rx-nav__content){width:min(35rem,90vw);min-width:0}.rx-nav--glow .rx-nav__panel-glow{opacity:.35;animation:none}:global(.rx-nav--glow [data-slot=navigation-menu-viewport]){border-color:rgb(var(--rx-color)/calc(var(--rx-nav-intensity)*.55));box-shadow:0 18px 40px -20px rgb(var(--rx-dark)/.6),0 0 calc(28px*var(--rx-nav-intensity)) -6px rgb(var(--rx-color)/.6)!important}
	.rx-nav--default :global(.rx-nav__trigger){background:radial-gradient(120px circle at var(--trigger-x,50%) var(--trigger-y,50%),rgb(var(--rx-text)),rgb(var(--rx-text)) 22%,rgb(var(--rx-text)/.52) 100%);background-clip:text;-webkit-background-clip:text;-webkit-text-fill-color:transparent}.rx-nav--default :global(.rx-nav__trigger:is([data-popup-open],[data-open])){background:none;color:rgb(var(--rx-text));-webkit-text-fill-color:rgb(var(--rx-text))}
	@media(prefers-reduced-motion:reduce){.rx-nav__indicator,.rx-nav__highlight,.rx-nav__spotlight,:global(.rx-nav__trigger){transition:none!important}.rx-nav__panel-glow,:global([data-slot=navigation-menu-viewport]),:global(.rx-nav__content),:global(.rx-nav__grid li){animation:none!important;filter:none!important;transform:none!important}}
</style>
