<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { RxColor } from '$lib/registry/lib/color';
	export interface InlineOverflowItem { label:string; value?:string; danger?:boolean; disabled?:boolean; content?:Snippet; onclick?:(item:InlineOverflowItem,index:number)=>void }
	export interface InlineOverflowProps { items:Array<InlineOverflowItem|Snippet|string>; visible?:number; open?:boolean; size?:'sm'|'md'|'lg'; radius?:'pill'|'rounded'|'squircle'; color?:RxColor; stiffness?:number; damping?:number; stagger?:number; lag?:number; blur?:number; squash?:number; disabled?:boolean; onOpenChange?:(open:boolean)=>void; onSelect?:(item:InlineOverflowItem,index:number)=>void }
</script>
<script lang="ts">
	import { styleColor } from '$lib/registry/lib/color';
	let {items,visible=2,open=$bindable(false),size='md',radius='pill',color,stiffness=260,damping=17,stagger=45,lag=.45,blur=5,squash=.045,disabled=false,onOpenChange,onSelect}:InlineOverflowProps=$props();
	class Spring{x=0;v=0;target=0;k:number;d:number;constructor(k:number,d:number){this.k=k;this.d=d}step(dt:number){const half=dt/2;for(let i=0;i<2;i++){const force=-this.k*(this.x-this.target)-this.d*this.v;this.v+=force*half;this.x+=this.v*half}}get settled(){return Math.abs(this.v)<.002&&Math.abs(this.x-this.target)<.002}snap(){this.x=this.target;this.v=0}}
	let root:HTMLElement;let measureFrame=0,physicsFrame=0,last=0,elapsed=0;let ready=$state(false),lastOpen=open;let shell=new Spring(260,17),trackSpring=new Spring(260*(1-.45*.62),17*(1-.45*.3)),pillSprings:Spring[]=[];let geometry={full:0,closed:0,hidden:0,tucks:[] as number[]};
	const normalized=$derived(items.map((item,index):InlineOverflowItem=>typeof item==='string'?{label:item,value:item}:typeof item==='function'?{label:`Action ${index+1}`,content:item}:{...item}));
	const shown=$derived(Math.max(0,Math.min(normalized.length,Math.round(visible))));const hidden=$derived(Math.max(0,normalized.length-shown));
	function reduced(){return typeof matchMedia!=='undefined'&&matchMedia('(prefers-reduced-motion: reduce)').matches}function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
	function configure(){shell.k=stiffness;shell.d=damping;trackSpring.k=stiffness*(1-lag*.62);trackSpring.d=damping*(1-lag*.3);pillSprings=Array.from({length:hidden},(_,i)=>{const spring=pillSprings[i]??new Spring(stiffness,damping);spring.k=stiffness*(1+i*.04);spring.d=damping*(1-Math.min(.2,i*.03));return spring})}
	function motionBlur(velocity:number,scale=1){return reduced()?0:Math.min(blur,Math.abs(velocity)*scale)}
	function draw(){if(!root)return;const wrappers=[...root.querySelectorAll<HTMLElement>('.rx-io__item:not(.rx-io__trigger)')],trigger=root.querySelector<HTMLElement>('.rx-io__trigger'),dots=root.querySelector<HTMLElement>('.rx-io__glyph--dots'),cross=root.querySelector<HTMLElement>('.rx-io__glyph--cross'),s=shell.x,t=trackSpring.x;root.style.width=`${geometry.closed+geometry.hidden*t}px`;root.querySelector<HTMLElement>('.rx-io__track')!.style.transform=`translate3d(${(geometry.hidden*(t-s)/2).toFixed(2)}px,0,0)`;const visibleBlur=motionBlur(shell.v*.55,1.1),visibleFilter=visibleBlur>.05?`blur(${visibleBlur.toFixed(2)}px)`:'';for(let i=0;i<shown;i++){const el=wrappers[i];if(el){el.style.transform='';el.style.opacity='1';el.style.filter=visibleFilter}}for(let i=0;i<hidden;i++){const el=wrappers[shown+i],spring=pillSprings[i];if(!el||!spring)continue;const p=spring.x,tuck=(geometry.tucks[i]??0)*(1-p),base=.34+.66*p,velocity=reduced()?0:spring.v*squash,sx=clamp(base*(1+velocity),.2,1.5),sy=clamp(base*(1-velocity*.62),.2,1.5),b=motionBlur(spring.v,1.1);el.style.transform=`translate3d(${tuck.toFixed(2)}px,0,0) scale(${sx.toFixed(3)},${sy.toFixed(3)})`;el.style.opacity=clamp(p*1.7,0,1).toFixed(3);el.style.filter=b>.05?`blur(${b.toFixed(2)}px)`:''}if(trigger){trigger.style.transform=`translate3d(${(-geometry.hidden*(1-s)).toFixed(2)}px,0,0)`;trigger.style.filter=visibleFilter}if(dots){dots.style.opacity=clamp(1-s*1.6,0,1).toFixed(3);dots.style.transform=`rotate(${(s*90).toFixed(1)}deg) scale(${(1-s*.45).toFixed(3)})`}if(cross){cross.style.opacity=clamp((s-.25)*1.8,0,1).toFixed(3);cross.style.transform=`rotate(${((1-s)*-90).toFixed(1)}deg) scale(${(.5+s*.5).toFixed(3)})`}}
	function delay(index:number){return stagger<=0?0:open?index*stagger:(hidden-1-index)*stagger*.7}function maxDelay(){return hidden?delay(open?hidden-1:0):0}
	function loop(now:number){const dt=Math.min(.032,last?(now-last)/1000:1/60);last=now;elapsed+=dt*1000;const target=open?1:0;shell.target=target;trackSpring.target=target;pillSprings.forEach((spring,index)=>{if(elapsed>=delay(index))spring.target=target});shell.step(dt);trackSpring.step(dt);pillSprings.forEach(spring=>spring.step(dt));draw();if(elapsed>=maxDelay()&&shell.settled&&trackSpring.settled&&pillSprings.every(spring=>spring.settled)){physicsFrame=0;last=0;shell.snap();trackSpring.snap();pillSprings.forEach(spring=>spring.snap());draw();return}physicsFrame=requestAnimationFrame(loop)}
	function snap(){const value=open?1:0;shell.target=value;trackSpring.target=value;pillSprings.forEach(spring=>spring.target=value);shell.snap();trackSpring.snap();pillSprings.forEach(spring=>spring.snap());draw()}function animate(){cancelAnimationFrame(physicsFrame);last=0;elapsed=0;if(reduced()){snap();return}physicsFrame=requestAnimationFrame(loop)}
	function measure(){cancelAnimationFrame(measureFrame);measureFrame=requestAnimationFrame(()=>{if(!root)return;const wrappers=[...root.querySelectorAll<HTMLElement>('.rx-io__item:not(.rx-io__trigger)')],trigger=root.querySelector<HTMLElement>('.rx-io__trigger');if(!trigger)return;const track=root.querySelector<HTMLElement>('.rx-io__track')!,gap=parseFloat(getComputedStyle(track).columnGap)||0,pad=parseFloat(getComputedStyle(root).paddingLeft)||0;const widths=wrappers.map(el=>el.offsetWidth),triggerW=trigger.offsetWidth,full=widths.reduce((a,b)=>a+b,0)+gap*Math.max(0,widths.length)+(hidden?triggerW:0)+pad*2,closed=widths.slice(0,shown).reduce((a,b)=>a+b,0)+gap*Math.max(0,shown)+(hidden?triggerW:0)+pad*2,hiddenWidth=Math.max(0,full-closed),triggerCenter=widths.slice(0,shown).reduce((a,b)=>a+b,0)+gap*Math.max(0,shown)+triggerW/2;let cursor=0;const allTucks=wrappers.map((_,index)=>{const center=cursor+widths[index]/2;cursor+=widths[index]+gap;return triggerCenter-center});geometry={full,closed,hidden:hiddenWidth,tucks:allTucks.slice(shown)};configure();ready=true;snap()})}
	function watch(node:HTMLElement){root=node;const observer=new ResizeObserver(measure);observer.observe(node.querySelector('.rx-io__track')!);document.fonts?.ready.then(measure);queueMicrotask(measure);return()=>{observer.disconnect();cancelAnimationFrame(measureFrame);cancelAnimationFrame(physicsFrame)}}
	function toggle(){if(disabled||!hidden)return;open=!open;onOpenChange?.(open);animate()}function choose(item:InlineOverflowItem,index:number){if(disabled||item.disabled)return;item.onclick?.(item,index);onSelect?.(item,index)}function keydown(e:KeyboardEvent){if(e.key==='Escape'&&open){e.preventDefault();open=false;onOpenChange?.(false);animate();root.querySelector<HTMLButtonElement>('.rx-io__trigger button')?.focus()}}$effect(()=>{normalized.length;shown;stiffness;damping;lag;queueMicrotask(measure)});$effect(()=>{if(open!==lastOpen){lastOpen=open;queueMicrotask(animate)}});
</script>
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<div bind:this={root} class="rx-io" class:is-ready={ready} class:is-open={open} class:is-disabled={disabled} data-size={size} data-radius={radius} role="toolbar" aria-label="Actions" tabindex="-1" style={`${styleColor(color)??'--rx-color:var(--rx-primary)'};--rx-io-stiffness:${stiffness};--rx-io-damping:${damping};--rx-io-lag:${lag};--rx-io-squash:${squash};--rx-io-stagger:${stagger}ms;--rx-io-blur:${blur}px`} onkeydown={keydown} {@attach watch}><div class="rx-io__track">{#each normalized as item,index (index)}<div class="rx-io__item" class:is-tucked={index>=shown} style={`--rx-io-i:${index-shown}`} inert={index>=shown&&!open||undefined}><button class="rx-io__pill" class:is-danger={item.danger} type="button" disabled={disabled||item.disabled} tabindex={index>=shown&&!open?-1:0} onclick={()=>choose(item,index)}>{#if item.content}{@render item.content()}{:else}{item.label}{/if}</button></div>{/each}{#if hidden}<div class="rx-io__item rx-io__trigger"><button class="rx-io__pill rx-io__pill--trigger" type="button" {disabled} aria-label={open?'Collapse actions':'More actions'} aria-expanded={open} onclick={toggle}><svg class="rx-io__glyph rx-io__glyph--dots" viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="19" cy="12" r="2"/></svg><svg class="rx-io__glyph rx-io__glyph--cross" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg></button></div>{/if}</div></div>
<style>
	.rx-io{--rx-io-h:40px;--rx-io-fs:14px;--rx-io-px:17px;--rx-io-gap:6px;--rx-io-pad:5px;--rx-io-r:999px;position:relative;display:inline-flex;align-items:center;box-sizing:border-box;max-width:100%;padding:var(--rx-io-pad);border-radius:calc(var(--rx-io-r) + var(--rx-io-pad));background:rgb(var(--rx-text)/.06);overflow:clip;overflow-clip-margin:24px;opacity:0;transition:opacity 140ms linear}.rx-io.is-ready{opacity:1}.rx-io.is-disabled{opacity:.5;pointer-events:none}.rx-io[data-size=sm]{--rx-io-h:30px;--rx-io-fs:12px;--rx-io-px:12px;--rx-io-gap:4px;--rx-io-pad:4px}.rx-io[data-size=lg]{--rx-io-h:48px;--rx-io-fs:15px;--rx-io-px:21px;--rx-io-gap:8px;--rx-io-pad:6px}.rx-io[data-radius=rounded]{--rx-io-r:12px}.rx-io[data-radius=squircle]{--rx-io-r:calc(var(--rx-io-h)*.5)}.rx-io__track{display:flex;align-items:center;gap:var(--rx-io-gap);flex:0 0 auto;width:max-content;will-change:transform}.rx-io__item{display:flex;flex:0 0 auto;will-change:transform,filter,opacity}.rx-io__pill{position:relative;isolation:isolate;display:inline-flex;align-items:center;justify-content:center;height:var(--rx-io-h);padding:0 var(--rx-io-px);border:0;border-radius:var(--rx-io-r);background:rgb(var(--rx-surface-2));box-shadow:0 1px 2px rgb(var(--rx-shadow)/.28);color:rgb(var(--rx-text));font:inherit;font-size:var(--rx-io-fs);font-weight:500;line-height:1;white-space:nowrap;cursor:pointer;transition:background 160ms ease,transform 220ms cubic-bezier(.34,1.56,.64,1),box-shadow 160ms ease}.rx-io__pill:hover{background:rgb(var(--rx-border-hover));box-shadow:0 2px 6px rgb(var(--rx-shadow)/.2)}.rx-io__pill:active{transform:scale(.94)}.rx-io__pill:focus-visible{outline:2px solid rgb(var(--rx-color));outline-offset:2px}.rx-io__pill.is-danger{color:rgb(var(--rx-danger))}.rx-io__pill--trigger{width:var(--rx-io-h);padding:0;color:rgb(var(--rx-text-secondary))}.rx-io__glyph{position:absolute;width:20px;height:20px;fill:currentColor;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;opacity:1;will-change:transform,opacity}.rx-io__glyph--cross{width:16px;height:16px;fill:none;opacity:0;transform:rotate(-90deg) scale(.5)}@media(prefers-reduced-motion:reduce){.rx-io{transition:none}.rx-io__pill{transition:background 160ms ease}.rx-io__pill:active{transform:none}}
	.rx-io{visibility:hidden;opacity:1;transition:none}
	.rx-io.is-ready{visibility:visible}
</style>
