import { fireEvent, render, screen } from '@testing-library/svelte';
import { afterEach, describe, expect, it, vi } from 'vitest';
import Harness from './checkbox-test-harness.svelte';
describe('Checkbox', () => {
	afterEach(()=>vi.unstubAllGlobals());
	it('round-trips binding and fires its callback', async () => { render(Harness); const box = screen.getByRole('checkbox'); await fireEvent.click(box); expect(screen.getByLabelText('checkbox value').textContent).toBe('true'); expect(screen.getByLabelText('checkbox calls').textContent).toBe('1'); await fireEvent.click(screen.getByText('Set checked')); expect(box.getAttribute('data-state')).toBe('checked'); });
	it('toggles with space and its label', async () => { render(Harness); const box = screen.getByRole('checkbox'); box.focus(); await fireEvent.keyDown(box, { key: ' ', code: 'Space' }); await fireEvent.keyUp(box, { key: ' ', code: 'Space' }); expect(box.getAttribute('data-state')).toBe('checked'); await fireEvent.click(screen.getByText('Accept')); expect(box.getAttribute('data-state')).toBe('unchecked'); });
	it('blocks disabled interaction', async () => { render(Harness, { disabled: true }); const box = screen.getByRole('checkbox'); await fireEvent.click(box); expect(box.getAttribute('data-state')).toBe('unchecked'); });
	it.each(['base', 'bounce', 'card', 'fill', 'flip', 'neon'] as const)('maps the %s source variant', (variant) => { render(Harness, { variant }); expect(screen.getByRole('checkbox').className).toContain(`rx-checkbox--variant-${variant}`); });
	it('creates the source two-wave pointer-coordinate ripple', async () => { render(Harness, { variant: 'base', glow: true }); const box=screen.getByRole('checkbox'); Object.defineProperty(box,'getBoundingClientRect',{value:()=>({left:0,top:0,width:20,height:20,right:20,bottom:20,x:0,y:0,toJSON(){}})}); await fireEvent.pointerDown(box,{clientX:4,clientY:7}); const waves=document.querySelectorAll('.rx-checkbox__ripple'); expect(waves).toHaveLength(2); expect(waves[0].getAttribute('style')).toContain('left: 4px'); expect(waves[0].className).toContain('rx-checkbox__ripple--inner'); });
	it('rAF-batches its proximity field, remeasures after resize, and cleans up', async () => { const view=render(Harness,{variant:'base',glow:true});const box=screen.getByRole('checkbox');let left=10;Object.defineProperty(box,'getBoundingClientRect',{value:()=>({left,top:0,width:20,height:20,right:left+20,bottom:20,x:left,y:0,toJSON(){}})});await fireEvent.pointerMove(document,{clientX:15,clientY:10});await vi.waitFor(()=>expect(box.style.getPropertyValue('--rx-gx')).toBe('5px'));expect(Number(box.style.getPropertyValue('--rx-glow'))).toBeGreaterThan(0);left=20;window.dispatchEvent(new Event('resize'));await vi.waitFor(()=>expect(box.style.getPropertyValue('--rx-gx')).toBe('-5px'));view.unmount();expect(box.style.getPropertyValue('--rx-glow')).toBe('');});
	it('suppresses decorative waves when reduced motion is requested',async()=>{vi.stubGlobal('matchMedia',()=>({matches:true}));render(Harness);await fireEvent.pointerDown(screen.getByRole('checkbox'),{clientX:4,clientY:7});expect(document.querySelectorAll('.rx-checkbox__ripple')).toHaveLength(0)});
});
