<script lang="ts" module>
	import type { Snippet } from 'svelte'; import type { RxColor } from '$lib/registry/lib/color';
	export interface BreadcrumbItem { label:string; href?:string; icon?:Snippet; disabled?:boolean }
	export interface BreadcrumbProps { items:BreadcrumbItem[]; color?:RxColor; variant?:'default'|'arrow'|'collapse'|'pill'|'slash'|'glow'; maxItems?:number; separator?:string|Snippet; onNavigate?:(item:BreadcrumbItem,index:number)=>void }
</script>
<script lang="ts">
	import * as Menu from '$lib/components/ui/dropdown-menu'; import { styleColor } from '$lib/registry/lib/color';
	let{items,color,variant='default',maxItems,separator,onNavigate}:BreadcrumbProps=$props();
	const effectiveLimit=$derived(variant==='collapse' ? (maxItems ?? 4) : maxItems); const limit=$derived(effectiveLimit===undefined?undefined:Math.max(3,effectiveLimit)); const collapsed=$derived(limit!==undefined&&items.length>limit); const head=$derived(collapsed?items.slice(0,1):items); const hidden=$derived(collapsed?items.slice(1,items.length-(limit!-2)):[]); const tail=$derived(collapsed?items.slice(items.length-(limit!-2)):items.slice(1));
	function drop(e:MouseEvent){const target=e.currentTarget as HTMLElement;const rect=target.getBoundingClientRect();const x=e.clientX-rect.left,y=e.clientY-rect.top,r=Math.max(Math.hypot(x,y),Math.hypot(rect.width-x,y),Math.hypot(x,rect.height-y));const el=document.createElement('span');el.className='rx-breadcrumb__drop';el.style.cssText=`left:${x}px;top:${y}px;width:${r*2}px;height:${r*2}px`;target.append(el);el.addEventListener('animationend',()=>el.remove(),{once:true})}
	function choose(item:BreadcrumbItem,index:number,e?:MouseEvent){if(item.disabled){e?.preventDefault();return}if(e)drop(e);onNavigate?.(item,index)}
	function actualIndex(index:number){return collapsed?items.length-tail.length+index:index+1}
	const sep=$derived(variant==='slash'?'/':'›');
</script>
<nav aria-label="Breadcrumb" class="rx-breadcrumb" data-variant={variant} style={styleColor(color)??'--rx-color:var(--rx-primary)'}><ol>
	{#each head as item,index}<li class="rx-item">{#if item.href}<a href={item.href} aria-disabled={item.disabled?'true':undefined} onclick={(e)=>choose(item,index,e)}>{#if item.icon}{@render item.icon()}{/if}{item.label}</a>{:else}<button disabled={item.disabled} onclick={(e)=>choose(item,index,e)}>{#if item.icon}{@render item.icon()}{/if}{item.label}</button>{/if}</li>{/each}
	{#if collapsed}<li class="rx-sep" aria-hidden="true">{#if typeof separator==='function'}{@render separator()}{:else}{separator??sep}{/if}</li><li>
		<Menu.Root><Menu.Trigger aria-label="Show collapsed breadcrumb items"><span class="rx-more"><i></i><i></i><i></i></span></Menu.Trigger><Menu.Content align="start">{#each hidden as item,i}<Menu.Item disabled={item.disabled} onSelect={()=>choose(item,i+1)}>{item.label}</Menu.Item>{/each}</Menu.Content></Menu.Root>
	</li>{/if}
	{#each tail as item,index}<li class="rx-sep" aria-hidden="true">{#if typeof separator==='function'}{@render separator()}{:else}{separator??sep}{/if}</li><li class="rx-item">{#if actualIndex(index)===items.length-1}<span aria-current="page">{#if item.icon}{@render item.icon()}{/if}{item.label}</span>{:else if item.href}<a href={item.href} aria-disabled={item.disabled?'true':undefined} onclick={(e)=>choose(item,actualIndex(index),e)}>{#if item.icon}{@render item.icon()}{/if}{item.label}</a>{:else}<button disabled={item.disabled} onclick={(e)=>choose(item,actualIndex(index),e)}>{item.label}</button>{/if}</li>{/each}
</ol></nav>
<style>.rx-breadcrumb ol{display:flex;align-items:center;flex-wrap:wrap;gap:5px;margin:0;padding:0;list-style:none}.rx-item a,.rx-item span,.rx-item button,.rx-more{position:relative;overflow:hidden;display:inline-flex;align-items:center;gap:6px;border:0;border-radius:8px;padding:7px 10px;color:rgb(var(--rx-text-secondary));background:transparent;font:inherit;text-decoration:none;transition:color 220ms ease,background 220ms ease,transform 360ms cubic-bezier(.34,1.56,.64,1),box-shadow 220ms ease}.rx-item a:hover,.rx-item button:hover{color:rgb(var(--rx-color));background:rgb(var(--rx-color)/.1)}.rx-item [aria-current=page]{color:rgb(var(--rx-text));font-weight:650}.rx-sep{display:inline-flex;color:rgb(var(--rx-text-muted));transition:transform 620ms cubic-bezier(.34,1.8,.42,1),color 220ms ease}.rx-item:hover+.rx-sep{transform:translateX(2px);color:rgb(var(--rx-color))}:global(.rx-breadcrumb__drop){position:absolute;border-radius:50%;translate:-50% -50%;background:radial-gradient(circle,rgb(var(--rx-color)/.2),rgb(var(--rx-color)/.1) 32%,rgb(var(--rx-color)/.035) 58%,transparent 76%);pointer-events:none;animation:rx-bc-drop 1820ms cubic-bezier(.22,1,.36,1) forwards}
[data-variant=pill] .rx-item>*{border-radius:999px;background:rgb(var(--rx-color)/.08);box-shadow:inset 0 0 0 1px transparent}[data-variant=pill] .rx-item>*:hover{transform:scale(1.06);box-shadow:inset 0 0 0 1px rgb(var(--rx-color)/.35)}
[data-variant=arrow] ol{gap:0}.rx-breadcrumb[data-variant=arrow] .rx-sep{display:none}.rx-breadcrumb[data-variant=arrow] .rx-item>*{margin-right:-8px;padding:8px 18px 8px 14px;border-radius:0;background:rgb(var(--rx-surface-2));clip-path:polygon(0 0,calc(100% - 10px) 0,100% 50%,calc(100% - 10px) 100%,0 100%,10px 50%)}.rx-breadcrumb[data-variant=arrow] .rx-item:first-child>*{padding-left:12px;clip-path:polygon(0 0,calc(100% - 10px) 0,100% 50%,calc(100% - 10px) 100%,0 100%)}.rx-breadcrumb[data-variant=arrow] .rx-item>*:hover{transform:translateX(3px);background:rgb(var(--rx-color)/.14)}
[data-variant=slash] .rx-item>*:after{content:"";position:absolute;left:10px;right:10px;bottom:4px;height:1px;background:rgb(var(--rx-color));transform:scaleX(0);transform-origin:left;transition:transform 360ms cubic-bezier(.22,1,.36,1)}[data-variant=slash] .rx-item>*:hover:after{transform:scaleX(1)}[data-variant=slash] .rx-sep{transform:skewX(-8deg)}[data-variant=slash] .rx-item:hover+.rx-sep{transform:skewX(-16deg)}
[data-variant=glow] .rx-item>*:hover,[data-variant=glow] .rx-item>*:focus-visible{color:rgb(var(--rx-color));text-shadow:0 0 8px rgb(var(--rx-color)/.75),0 0 18px rgb(var(--rx-color)/.35);animation:rx-bc-flicker 1600ms ease}[data-variant=glow] .rx-item:hover+.rx-sep{filter:drop-shadow(0 0 5px rgb(var(--rx-color)))}
.rx-more{gap:3px;cursor:pointer}.rx-more i{display:block;width:4px;height:4px;border-radius:50%;background:currentColor;animation:rx-bc-bob 1200ms ease-in-out infinite}.rx-more i:nth-child(2){animation-delay:120ms}.rx-more i:nth-child(3){animation-delay:240ms}.rx-breadcrumb[data-variant=collapse] .rx-item{animation:rx-bc-reveal 420ms cubic-bezier(.34,1.56,.64,1) both}[aria-disabled=true]{pointer-events:none;opacity:.45}
@keyframes rx-bc-drop{from{transform:scale(0);opacity:.8}to{transform:scale(1);opacity:0}}@keyframes rx-bc-bob{50%{transform:translateY(-3px);opacity:1}}@keyframes rx-bc-reveal{from{opacity:0;transform:translateX(-6px) scale(.9)}}@keyframes rx-bc-flicker{0%,12%,22%,100%{opacity:1}8%,18%{opacity:.55}}
@media(prefers-reduced-motion:reduce){.rx-breadcrumb *{transition:color 160ms ease!important;animation:none!important}:global(.rx-breadcrumb__drop){display:none}}
</style>
