<script lang="ts" module>
	import type{NotificationItem,NotifyPosition,NotifyVariant}from'./notify.svelte';import type{TransitionConfig}from'svelte/transition';
	export interface NotificationProps{item:NotificationItem}
	type Motion={variant:NotifyVariant;position:NotifyPosition};
	function bezier(x1:number,y1:number,x2:number,y2:number){return(x:number)=>{let t=x;for(let i=0;i<5;i++){const mt=1-t;const bx=3*mt*mt*t*x1+3*mt*t*t*x2+t*t*t;const dx=3*mt*mt*x1+6*mt*t*(x2-x1)+3*t*t*(1-x2);if(Math.abs(dx)<1e-5)break;t-= (bx-x)/dx}const mt=1-t;return 3*mt*mt*t*y1+3*mt*t*t*y2+t*t*t}}
	const enterEase=bezier(.22,1.12,.36,1),outEase=bezier(.4,0,.7,.2),slideEase=bezier(.22,1,.36,1),springEase=bezier(.34,1.4,.5,1);
	function reduced(){return typeof matchMedia!=='undefined'&&matchMedia('(prefers-reduced-motion: reduce)').matches}
	export function notificationIn(_node:Element,{variant,position}:Motion):TransitionConfig{const family=variant==='default'?'base':variant;const duration=reduced()?0:family==='base'?720:family==='banner'?460:family==='snackbar'?460:family==='inline'?220:440;const easing=family==='base'?enterEase:family==='snackbar'?springEase:slideEase;return{duration,easing,css:(t)=>{const u=1-t;if(family==='base'){const y=(position.startsWith('top')?-14:14)*u;return`opacity:${t};transform:translateY(${y}px) scale(${.9+.1*t});filter:blur(${9*u}px)`}if(family==='banner')return`opacity:${t};transform:translateY(${-100*u}%)`;if(family==='card'||family==='glow')return`opacity:${t};transform:translateX(${120*u}%)`;if(family==='snackbar')return`opacity:${t};transform:translateY(${140*u}%)`;return`opacity:${t};transform:translateY(${-4*u}px)`}}}
	export function notificationOut(_node:Element,{variant,position}:Motion):TransitionConfig{const family=variant==='default'?'base':variant;const duration=reduced()?0:family==='base'?320:family==='banner'||family==='card'||family==='glow'?260:family==='snackbar'?240:220;return{duration,easing:outEase,css:(t)=>{const u=1-t;if(family==='base'){const y=(position.startsWith('top')?-7:7)*u;return`opacity:${t};transform:translateY(${y}px) scale(${.86+.14*t});filter:blur(${9*u}px)`}if(family==='banner')return`opacity:${t};transform:translateY(${-100*u}%)`;if(family==='card'||family==='glow')return`opacity:${t};transform:translateX(${120*u}%)`;if(family==='snackbar')return`opacity:${t};transform:translateY(${140*u}%)`;return`opacity:${t};transform:translateY(${-4*u}px)`}}}
</script>
<script lang="ts">
	import{styleColor}from'$lib/registry/lib/color';import{dismissNotification,pauseNotification,resumeNotification,type NotifyState}from'./notify.svelte';
	let{item}:NotificationProps=$props();let article=$state<HTMLElement|null>(null);let headerInner=$state<HTMLElement|null>(null);let contentElement=$state<HTMLElement|null>(null);let expanded=$state(false);let contentHeight=$state(0);let pillWidth=$state(160);let swapping=$state(false);let swapReady=false;const family=$derived(item.variant==='default'?'base':item.variant);const notifyState=$derived<NotifyState>(item.state??(item.color==='danger'?'error':item.color==='warn'?'warn':item.color==='success'?'success':'info'));const description=$derived(item.description??item.text);const hasDetails=$derived(Boolean(description||item.action||item.content));const bottomEdge=$derived(item.position.startsWith('bottom'));const alignment=$derived(item.position.endsWith('left')?'left':item.position.endsWith('right')?'right':'center');const pillX=$derived(alignment==='left'?0:alignment==='right'?360-pillWidth:(360-pillWidth)/2);const bodyHeight=$derived(expanded?contentHeight+16:0);const panelHeight=$derived(44+bodyHeight);const stateColor=$derived(notifyState==='success'?'--rx-color:var(--rx-success)':notifyState==='error'?'--rx-color:var(--rx-danger)':notifyState==='warn'?'--rx-color:var(--rx-warn)':'--rx-color:var(--rx-primary)');const inlineStyle=$derived(`${styleColor(item.color)??stateColor};--rx-notify-duration:${item.duration}ms;--rx-notify-roundness:${item.roundness}px;--rx-notification-h:${panelHeight}px`);function activate(event:MouseEvent){if((event.target as HTMLElement).closest('button'))return;if(item.onClick){item.onClick();return}if(family==='base'){item.action?.onClick();dismissNotification(item.id)}}function runAction(event:MouseEvent){event.stopPropagation();item.action?.onClick();dismissNotification(item.id)}function enter(){if(hasDetails&&notifyState!=='loading')expanded=true;pauseNotification(item.id)}function leave(){expanded=false;resumeNotification(item.id)}
	$effect(()=>{const content=contentElement,head=headerInner;if(!content||!head||family!=='base')return;const measure=()=>{contentHeight=Math.ceil(content.scrollHeight);pillWidth=Math.max(120,Math.min(352,Math.ceil(head.scrollWidth)+52))};measure();const observer=new ResizeObserver(measure);observer.observe(content);observer.observe(head);return()=>observer.disconnect()});
	$effect(()=>{if(family!=='base'||!hasDetails||notifyState==='loading'){expanded=false;return}const timer=setTimeout(()=>expanded=true,280);return()=>clearTimeout(timer)});
	$effect(()=>{item.title;notifyState;if(!swapReady){swapReady=true;return}swapping=true;const timer=setTimeout(()=>swapping=false,380);return()=>clearTimeout(timer)});
</script>
<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<article bind:this={article} class="rx-notification rx-notification--{family} rx-notification--state-{notifyState} rx-notification--surface-{item.surface}" class:rx-notification--edge-bottom={bottomEdge} class:rx-notification--align-left={alignment==='left'} class:rx-notification--align-right={alignment==='right'} class:rx-notification--align-center={alignment==='center'} class:rx-notification--expanded={expanded} data-source-variant={item.variant} data-state={notifyState} class:rx-notification--clickable={Boolean(item.onClick)||family==='base'} style={inlineStyle} role={notifyState==='error'?'alert':'status'} tabindex={item.onClick?0:undefined} onclick={activate} onkeydown={(event)=>{if(item.onClick&&(event.key==='Enter'||event.key===' ')){event.preventDefault();item.onClick()}}} onpointerenter={enter} onpointerleave={leave} in:notificationIn={{variant:item.variant,position:item.position}} out:notificationOut={{variant:item.variant,position:item.position}}>
	{#if family==='base'}
		<svg class="rx-notification__goo" viewBox="0 0 360 324" aria-hidden="true"><defs><filter id="rx-notification-goo-{item.id}" x="-20%" y="-20%" width="140%" height="140%" color-interpolation-filters="sRGB"><feGaussianBlur in="SourceGraphic" stdDeviation={Math.max(2,item.roundness*.5)} result="blur"/><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10" result="goo"/><feComposite in="SourceGraphic" in2="goo" operator="atop"/></filter></defs><g filter="url(#rx-notification-goo-{item.id})"><rect class="rx-notification__pill" x={pillX} y={bottomEdge?280:0} width={pillWidth} height="44" rx={item.roundness}/><rect class="rx-notification__goo-body" x="0" y={bottomEdge?296-bodyHeight:28} width="360" height={bodyHeight} rx={item.roundness}/></g></svg>
		<div class="rx-notification__head"><div class="rx-notification__head-inner" class:rx-notification__head-inner--swapping={swapping} bind:this={headerInner}><span class="rx-notification__icon" aria-hidden="true">{#if item.icon}{@render item.icon()}{:else if notifyState==='loading'}<svg class="rx-notification__spinner" viewBox="0 0 24 24"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>{:else if notifyState==='success'}<svg viewBox="0 0 24 24"><path d="M20.46 6.18 8.82 17.82 3.53 12.53"/></svg>{:else if notifyState==='error'}<svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg>{:else if notifyState==='warn'}<svg viewBox="0 0 24 24"><path d="M12 7.75V13M12 17h.01"/><path d="M12 2 2 21h20L12 2Z"/></svg>{:else}<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 8v5m0 3h.01"/></svg>{/if}</span><strong>{item.title??item.text??notifyState}</strong>{#if item.closable}<button class="rx-notification__close" type="button" aria-label="Close notification" onclick={(event)=>{event.stopPropagation();dismissNotification(item.id)}}>×</button>{/if}</div></div>
		<div class="rx-notification__morph-content" class:rx-notification__morph-content--visible={expanded} bind:this={contentElement}>{#if item.content}{@render item.content()}{:else}{#if item.title&&description}<p>{description}</p>{/if}{#if item.action}<button class="rx-notification__action" type="button" onclick={runAction}>{item.action.label}</button>{/if}{/if}</div>
	{:else}
		{#if item.variant==='inline'}<span class="rx-notification__accent" aria-hidden="true"></span>{/if}{#if item.variant==='snackbar'}<span class="rx-notification__dot" aria-hidden="true"></span>{:else if item.icon}<span class="rx-notification__icon" aria-hidden="true">{@render item.icon()}</span>{/if}
		<div class="rx-notification__body">{#if item.content}{@render item.content()}{:else}{#if item.title}<strong>{item.title}</strong>{/if}{#if description}<p>{description}</p>{/if}{/if}</div>{#if item.action}<button class="rx-notification__action" type="button" onclick={runAction}>{item.action.label}</button>{/if}{#if item.closable}<button class="rx-notification__close" type="button" aria-label="Close notification" onclick={(event)=>{event.stopPropagation();dismissNotification(item.id)}}>×</button>{/if}
	{/if}
	{#if item.progress&&item.duration>0}<span class="rx-notification__progress" class:rx-notification__progress--paused={item.paused} aria-hidden="true"></span>{/if}
</article>
<style>
	.rx-notification{--rx-notification-content-h:44px;position:relative;box-sizing:border-box;pointer-events:auto;color:rgb(var(--rx-text));font-family:inherit}.rx-notification--clickable{cursor:pointer}.rx-notification--clickable:focus-visible{outline:2px solid rgb(var(--rx-color));outline-offset:2px}.rx-notification__body{min-width:0;flex:1}.rx-notification__body strong{display:block;font-size:14px;font-weight:600}.rx-notification__body p{margin:3px 0 0;color:rgb(var(--rx-text-muted));font-size:13px;line-height:1.5}.rx-notification__icon{position:relative;display:inline-flex;flex:none;color:rgb(var(--rx-color))}.rx-notification__icon svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}.rx-notification__spinner{animation:rx-notification-spin .8s linear infinite}.rx-notification__action{position:relative;z-index:4;flex:none;padding:6px 9px;border:0;border-radius:8px;background:transparent;color:rgb(var(--rx-color));font:inherit;font-size:13px;font-weight:600;cursor:pointer}.rx-notification__action:hover{text-decoration:underline;background:rgb(var(--rx-color)/.12)}.rx-notification__close{position:relative;z-index:4;flex:none;display:grid;place-items:center;width:26px;height:26px;margin:-2px -2px 0 0;padding:0;border:0;border-radius:8px;color:rgb(var(--rx-text-muted));background:transparent;cursor:pointer;font-size:20px;line-height:1;transition:background-color 160ms ease,color 160ms ease}.rx-notification__close:hover{color:rgb(var(--rx-text));background:rgb(var(--rx-text)/.08)}
	.rx-notification--base{width:min(360px,calc(100vw - 40px));height:var(--rx-notification-h);min-height:44px;transition:height 600ms cubic-bezier(.34,1.46,.44,1);filter:drop-shadow(0 10px 30px rgb(var(--rx-dark)/.45))}.rx-notification__goo{position:absolute;inset:0;width:360px;height:324px;overflow:visible;pointer-events:none}.rx-notification--edge-bottom .rx-notification__goo{inset:auto 0 0}.rx-notification__pill,.rx-notification__goo-body{fill:rgb(var(--rx-surface-2));transition:x 600ms cubic-bezier(.34,1.46,.44,1),width 600ms cubic-bezier(.34,1.46,.44,1),height 600ms cubic-bezier(.34,1.46,.44,1),y 600ms cubic-bezier(.34,1.46,.44,1)}.rx-notification__head{position:absolute;inset:0 0 auto;z-index:2;display:flex;height:44px;align-items:center;justify-content:center;pointer-events:none}.rx-notification--edge-bottom .rx-notification__head{inset:auto 0 0}.rx-notification--align-left .rx-notification__head{justify-content:flex-start}.rx-notification--align-right .rx-notification__head{justify-content:flex-end}.rx-notification__head-inner{display:inline-flex;max-width:352px;align-items:center;gap:9px;padding:0 16px;pointer-events:auto;transition:filter 300ms ease,opacity 300ms ease}.rx-notification__head-inner--swapping{animation:rx-notification-swap 360ms ease}.rx-notification__head strong{min-width:0;overflow:hidden;color:rgb(var(--rx-color));font-size:14px;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.rx-notification__head .rx-notification__close{margin-left:auto}.rx-notification__morph-content{position:absolute;inset:44px 0 auto;z-index:2;padding:0 22px;opacity:0;transform:translateY(-6px);pointer-events:none;transition:opacity 240ms ease,transform 600ms cubic-bezier(.34,1.46,.44,1)}.rx-notification--edge-bottom .rx-notification__morph-content{inset:auto 0 44px;transform:translateY(6px)}.rx-notification__morph-content--visible{opacity:1;transform:translateY(0)!important;pointer-events:auto;transition-delay:90ms}.rx-notification__morph-content>p:first-child{margin-top:0}.rx-notification__morph-content p{margin:0;color:rgb(var(--rx-text-muted));font-size:13px;line-height:1.5}.rx-notification__morph-content .rx-notification__action{margin-top:10px}.rx-notification--surface-fluent .rx-notification__pill,.rx-notification--surface-fluent .rx-notification__goo-body{fill:rgb(var(--rx-surface-2)/.88)}.rx-notification--surface-outline{filter:drop-shadow(1px 0 0 rgb(var(--rx-border))) drop-shadow(-1px 0 0 rgb(var(--rx-border))) drop-shadow(0 1px 0 rgb(var(--rx-border))) drop-shadow(0 -1px 0 rgb(var(--rx-border))) drop-shadow(0 8px 22px rgb(var(--rx-dark)/.5))}.rx-notification--surface-glass{filter:drop-shadow(.5px 0 0 rgb(var(--rx-light)/.35)) drop-shadow(-.5px 0 0 rgb(var(--rx-light)/.18)) drop-shadow(0 -.5px 0 rgb(var(--rx-light)/.4)) drop-shadow(0 14px 36px rgb(var(--rx-dark)/.45))}.rx-notification--surface-glass .rx-notification__pill,.rx-notification--surface-glass .rx-notification__goo-body{fill:rgb(var(--rx-surface-2)/.52)}
	.rx-notification--banner{position:fixed;top:0;left:0;right:0;display:flex;align-items:center;gap:12px;width:100vw;padding:12px 20px;border-bottom:1px solid rgb(var(--rx-color)/.4);background:color-mix(in srgb,rgb(var(--rx-color)) 14%,rgb(var(--rx-surface)));box-shadow:0 8px 24px -12px rgb(var(--rx-dark)/.5)}.rx-notification--banner .rx-notification__body{display:flex;flex-wrap:wrap;align-items:baseline;gap:4px 10px}
	.rx-notification--card,.rx-notification--glow{display:flex;align-items:flex-start;gap:12px;width:min(340px,calc(100vw - 40px));padding:14px 14px 16px;border:1px solid rgb(var(--rx-border));border-radius:14px;background:rgb(var(--rx-surface));box-shadow:0 16px 44px -12px rgb(var(--rx-dark)/.6);overflow:hidden}.rx-notification--card .rx-notification__icon,.rx-notification--glow .rx-notification__icon{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:rgb(var(--rx-color)/.16)}.rx-notification--glow{align-items:center;width:min(330px,calc(100vw - 40px));padding:13px 14px;border-color:rgb(var(--rx-color)/.55);background:rgb(var(--rx-dark));color:rgb(var(--rx-light));box-shadow:0 0 0 1px rgb(var(--rx-color)/.35),0 0 22px -6px rgb(var(--rx-color)/.55),0 16px 40px -14px rgb(var(--rx-dark)/.7)}.rx-notification--glow .rx-notification__icon{filter:drop-shadow(0 0 5px rgb(var(--rx-color)/.8))}.rx-notification--glow .rx-notification__icon::after{content:'';position:absolute;inset:0;border-radius:inherit;box-shadow:0 0 0 3px rgb(var(--rx-color)/.25);opacity:0;animation:rx-notification-pulse 1.8s ease-in-out infinite}.rx-notification--glow .rx-notification__body p{color:rgb(var(--rx-light)/.6)}
	.rx-notification--inline{display:flex;align-items:flex-start;gap:12px;width:min(480px,calc(100vw - 32px));padding:14px 14px 14px 18px;border:1px solid color-mix(in srgb,rgb(var(--rx-color)) 30%,rgb(var(--rx-border)));border-radius:12px;background:color-mix(in srgb,rgb(var(--rx-color)) 9%,rgb(var(--rx-surface)));overflow:hidden}.rx-notification__accent{position:absolute;inset:0 auto 0 0;width:3px;background:rgb(var(--rx-color))}
	.rx-notification--snackbar{display:flex;align-items:center;gap:12px;max-width:calc(100vw - 32px);height:48px;padding:0 8px 0 16px;border:1px solid rgb(var(--rx-light)/.08);border-radius:12px;background:rgb(var(--rx-dark));color:rgb(var(--rx-light));box-shadow:0 14px 40px -10px rgb(var(--rx-dark)/.6)}.rx-notification--snackbar .rx-notification__body p{margin:0;color:rgb(var(--rx-light));font-size:14px;font-weight:500;white-space:nowrap}.rx-notification--snackbar .rx-notification__action{height:32px;color:rgb(var(--rx-color))}.rx-notification__dot{flex:none;width:9px;height:9px;border-radius:50%;background:rgb(var(--rx-color));box-shadow:0 0 10px rgb(var(--rx-color))}
	.rx-notification__progress{position:absolute;z-index:5;inset:auto 0 0;height:3px;background:rgb(var(--rx-color));transform-origin:left;animation:rx-notification-countdown var(--rx-notify-duration) linear forwards}.rx-notification__progress--paused{animation-play-state:paused}@keyframes rx-notification-countdown{to{transform:scaleX(0)}}@keyframes rx-notification-pulse{0%,50%,100%{opacity:0}25%,75%{opacity:1}}@keyframes rx-notification-spin{to{transform:rotate(360deg)}}@keyframes rx-notification-swap{0%{filter:blur(0);opacity:1}40%{filter:blur(6px);opacity:.4}100%{filter:blur(0);opacity:1}}
	@media(prefers-reduced-motion:reduce){.rx-notification,.rx-notification__pill,.rx-notification__goo-body,.rx-notification__morph-content{transition-duration:1ms!important}.rx-notification--glow .rx-notification__icon::after,.rx-notification__spinner{animation:none}.rx-notification__progress{display:none}}@media(forced-colors:active){.rx-notification{border:1px solid CanvasText;box-shadow:none;filter:none}.rx-notification__progress{background:Highlight}}
</style>
