<script lang="ts" module>
 import type { Snippet } from 'svelte'; import type { RxColor } from '$lib/registry/lib/color';
 export interface ListItem {id:string;title:string;description?:string;href?:string;icon?:Snippet;leading?:Snippet;trailing?:Snippet;disabled?:boolean}
 export interface ListProps {items:ListItem[];selected?:string|string[];selectionMode?:'none'|'single'|'multiple';color?:RxColor;variant?:'default'|'cards'|'glow'|'hover'|'reveal'|'stripe';onSelectedChange?:(value:string|string[]|undefined)=>void;onActivate?:(item:ListItem)=>void}
</script>
<script lang="ts">
 import { styleColor } from '$lib/registry/lib/color';
 let {items,selected=$bindable(),selectionMode='none',color,variant='default',onSelectedChange,onActivate}:ListProps=$props();
 function isSelected(id:string){return Array.isArray(selected)?selected.includes(id):selected===id}
 function choose(item:ListItem){if(item.disabled)return;if(selectionMode==='single')selected=item.id;else if(selectionMode==='multiple'){const value=Array.isArray(selected)?selected:[];selected=value.includes(item.id)?value.filter(x=>x!==item.id):[...value,item.id]}onSelectedChange?.(selected);onActivate?.(item)}
 function keydown(e:KeyboardEvent,index:number){if(selectionMode==='none')return;const enabled=items.map((x,i)=>({x,i})).filter(v=>!v.x.disabled);const current=enabled.findIndex(v=>v.i===index);let next:number|undefined;if(e.key==='ArrowDown')next=Math.min(enabled.length-1,current+1);else if(e.key==='ArrowUp')next=Math.max(0,current-1);else if(e.key==='Home')next=0;else if(e.key==='End')next=enabled.length-1;else if(e.key===' '||e.key==='Enter'){e.preventDefault();choose(items[index]);return}else return;e.preventDefault();document.querySelector<HTMLElement>(`[data-rx-list-id="${CSS.escape(enabled[next].x.id)}"]`)?.focus()}
</script>
<ul class="rx-list rx-list--{variant}" role={selectionMode==='none'?undefined:'listbox'} aria-multiselectable={selectionMode==='multiple'||undefined} style={styleColor(color)??'--rx-color:var(--rx-primary)'}>
 {#each items as item,i (item.id)}<li role={selectionMode==='none'?undefined:'option'} aria-selected={selectionMode==='none'?undefined:isSelected(item.id)} aria-disabled={item.disabled||undefined}>
  {#if item.href}<a href={item.disabled?undefined:item.href} aria-disabled={item.disabled||undefined} tabindex={item.disabled?-1:0} data-rx-list-id={item.id} onclick={(e)=>{if(item.disabled)e.preventDefault();else choose(item)}} onkeydown={(e)=>keydown(e,i)}>{#if item.leading}<span>{@render item.leading()}</span>{:else if item.icon}<span class="rx-list__icon">{@render item.icon()}</span>{/if}<span class="rx-list__copy"><strong>{item.title}</strong>{#if item.description}<small>{item.description}</small>{/if}</span>{#if item.trailing}<span class="rx-list__trailing">{@render item.trailing()}</span>{/if}</a>
  {:else}<button type="button" disabled={item.disabled} data-rx-list-id={item.id} onclick={()=>choose(item)} onkeydown={(e)=>keydown(e,i)}>{#if item.leading}<span>{@render item.leading()}</span>{:else if item.icon}<span class="rx-list__icon">{@render item.icon()}</span>{/if}<span class="rx-list__copy"><strong>{item.title}</strong>{#if item.description}<small>{item.description}</small>{/if}</span>{#if item.trailing}<span class="rx-list__trailing">{@render item.trailing()}</span>{/if}</button>{/if}
 </li>{/each}
</ul>
<style>.rx-list{display:grid;list-style:none;margin:0;padding:0;gap:.35rem}.rx-list li{min-width:0}.rx-list a,.rx-list button{display:flex;width:100%;box-sizing:border-box;align-items:center;gap:.8rem;padding:.75rem 1rem;border:0;border-radius:var(--rx-radius);background:transparent;color:rgb(var(--rx-text));text-align:left;text-decoration:none;font:inherit;cursor:pointer;transition:background .2s,transform .2s,box-shadow .2s}.rx-list a:focus-visible,.rx-list button:focus-visible{outline:3px solid rgb(var(--rx-color)/.28)}.rx-list [aria-selected=true]>a,.rx-list [aria-selected=true]>button{background:rgb(var(--rx-color)/.13);color:rgb(var(--rx-color))}.rx-list__copy{display:grid;gap:.15rem;flex:1}.rx-list__copy small{opacity:.6}.rx-list__icon{color:rgb(var(--rx-color))}.rx-list--cards{gap:.7rem}.rx-list--cards a,.rx-list--cards button{background:rgb(var(--rx-surface));box-shadow:var(--rx-shadow)}.rx-list--glow [aria-selected=true]>a,.rx-list--glow [aria-selected=true]>button{box-shadow:0 0 1.1rem rgb(var(--rx-color)/.35)}.rx-list--hover a:hover,.rx-list--hover button:hover{background:rgb(var(--rx-color)/.08);transform:translateX(.25rem)}.rx-list--stripe li:nth-child(odd)>a,.rx-list--stripe li:nth-child(odd)>button{background:rgb(var(--rx-color)/.06)}.rx-list--reveal .rx-list__trailing{opacity:0;transform:translateX(.4rem);transition:.2s}.rx-list--reveal a:hover .rx-list__trailing,.rx-list--reveal button:hover .rx-list__trailing,.rx-list--reveal a:focus-visible .rx-list__trailing,.rx-list--reveal button:focus-visible .rx-list__trailing{opacity:1;transform:none}@media(prefers-reduced-motion:reduce){.rx-list :global(*){transition-duration:0ms!important;transform:none!important}}</style>
