<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { Switch as SwitchTypes } from 'bits-ui';
	import type { RxColor } from '$lib/registry/lib/color';
	export type SwitchVariant = 'base' | 'day-night' | 'dot' | 'glow' | 'label' | 'liquid' | 'material';
	export interface SwitchProps extends Omit<SwitchTypes.RootProps, 'checked' | 'disabled' | 'children' | 'child' | 'color' | 'onCheckedChange'> {
		checked?: boolean; color?: RxColor; size?: 'lg' | 'default' | 'sm'; shape?: 'pill' | 'rounded' | 'square'; variant?: SwitchVariant;
		loading?: boolean; disabled?: boolean; glow?: boolean; labelPosition?: 'left' | 'right'; on?: Snippet; off?: Snippet;
		onCheckedChange?: (checked: boolean) => void;
	}
	type Ripple = { id: number; x: number; y: number; size: number };
</script>
<script lang="ts">
	import { Switch as SwitchPrimitive, useId } from 'bits-ui';
	import { proximityGlow } from '$lib/registry/attachments/proximity-glow';
	import { styleColor } from '$lib/registry/lib/color';
	import { switchVariants } from './index';
	let { checked = $bindable(false), color, size = 'default', shape = 'pill', variant = 'base', loading = false, disabled = false, glow = false,
		labelPosition = 'right', on, off, onCheckedChange, class: className, style, ...restProps }: SwitchProps = $props();
	const inactive=$derived(disabled||loading),classes=$derived(switchVariants({size,shape,variant,class:typeof className==='string'?className:undefined})),inlineStyle=$derived(`${styleColor(color)??'--rx-color:var(--rx-primary)'};${style??''}`);
	const attachProximity=proximityGlow({radius:120,disabled:()=>inactive||!glow||variant!=='base'});
	let pressed=$state(false),dragging=$state(false),startX=0,startChecked=false,sequence=0,ripples=$state<Ripple[]>([]),timers:ReturnType<typeof setTimeout>[]=[];
	const filterId=`rx-switch-goo-${useId().replaceAll(':','')}`,reduced=()=>typeof matchMedia!=='undefined'&&matchMedia('(prefers-reduced-motion:reduce)').matches;
	function change(next:boolean){onCheckedChange?.(next)}
	function pointerDown(event:PointerEvent){if(inactive)return;pressed=true;dragging=false;startX=event.clientX;startChecked=checked;if(variant==='base'&&!reduced()){const n=event.currentTarget as HTMLElement,r=n.getBoundingClientRect(),x=event.clientX-r.left,y=event.clientY-r.top,d=Math.hypot(Math.max(x,r.width-x),Math.max(y,r.height-y))*2,id=++sequence;ripples.push({id,x,y,size:d});timers.push(setTimeout(()=>ripples=ripples.filter(v=>v.id!==id),700));const c=(v:number)=>Math.max(-1,Math.min(1,v)),nx=c((x/r.width-.5)*2),ny=c((y/r.height-.5)*2),s=1-.2*Math.min(Math.abs(nx),Math.abs(ny));n.style.transform=`perspective(300px) rotateX(${(-ny*18*s).toFixed(2)}deg) rotateY(${(nx*12*s).toFixed(2)}deg) scale(.93)`}try{(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)}catch{}}
	function pointerMove(event:PointerEvent){if(!pressed||variant!=='base')return;const delta=event.clientX-startX;if(Math.abs(delta)>4){dragging=true;const next=delta>0?true:delta<0?false:startChecked;if(next!==checked){checked=next;change(next)}}}
	function pointerUp(event:PointerEvent){if(dragging)event.preventDefault();pressed=false;dragging=false;(event.currentTarget as HTMLElement).style.transform='';try{(event.currentTarget as HTMLElement).releasePointerCapture(event.pointerId)}catch{}}
	function cancel(event:PointerEvent){pressed=false;dragging=false;(event.currentTarget as HTMLElement).style.transform=''}
	$effect(()=>()=>{for(const timer of timers)clearTimeout(timer)});
</script>
<span class="rx-switch-field rx-switch-field--{variant} rx-switch-field--label-{labelPosition}" class:rx-switch-field--pressed={pressed} class:rx-switch-field--dragging={dragging} class:rx-switch-field--disabled={inactive} style={inlineStyle}>
	<SwitchPrimitive.Root {...restProps} bind:checked disabled={inactive} onCheckedChange={change} class={classes} style={inlineStyle} aria-busy={loading?'true':undefined} onpointerdown={pointerDown} onpointermove={pointerMove} onpointerup={pointerUp} onpointercancel={cancel} onpointerleave={cancel} {@attach attachProximity}>
		{#snippet children({ checked: isChecked })}
			<span class="rx-switch__glow" aria-hidden="true"></span><span class="rx-switch__ripples" aria-hidden="true">{#each ripples as ripple(ripple.id)}<span class="rx-switch__ripple" style={`left:${ripple.x}px;top:${ripple.y}px;width:${ripple.size}px;height:${ripple.size}px`}></span>{/each}</span>
			<span class="rx-switch__stars" aria-hidden="true"><i style="--x:60%;--y:32%;--d:1"></i><i style="--x:74%;--y:60%;--d:.7"></i><i style="--x:86%;--y:40%;--d:1"></i><i style="--x:68%;--y:76%;--d:.6"></i></span>
			<span class="rx-switch__clouds" aria-hidden="true"><i style="--x:20%;--y:62%;--s:1"></i><i style="--x:36%;--y:40%;--s:.7"></i></span>
			<span class="rx-switch__state rx-switch__state--on" aria-hidden="true">{#if on}{@render on()}{:else}ON{/if}</span><span class="rx-switch__state rx-switch__state--off" aria-hidden="true">{#if off}{@render off()}{:else}OFF{/if}</span>
			{#if variant==='liquid'}<svg class="rx-switch__goo-def" width="0" height="0" aria-hidden="true"><defs><filter id={filterId}><feGaussianBlur in="SourceGraphic" stdDeviation="3" result="blur"/><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo"/><feComposite in="SourceGraphic" in2="goo" operator="atop"/></filter></defs></svg><span class="rx-switch__liquid" style={`filter:url(#${filterId})`} aria-hidden="true"><span class="rx-switch__trail rx-switch__trail--one"></span><span class="rx-switch__trail rx-switch__trail--two"></span></span>{/if}
			<SwitchPrimitive.Thumb class="rx-switch__thumb"><span class="rx-switch__craters" aria-hidden="true"></span>{#if loading}<span class="rx-switch__spinner" aria-hidden="true"></span>{:else}<span class="rx-switch__icon rx-switch__icon--on" aria-hidden="true">{#if on}{@render on()}{:else}<svg viewBox="0 0 24 24"><path d="m7.75 12 2.83 2.83 5.67-5.66"/></svg>{/if}</span><span class="rx-switch__icon rx-switch__icon--off" aria-hidden="true">{#if off}{@render off()}{:else}<svg viewBox="0 0 24 24"><path d="M6 12h12"/></svg>{/if}</span>{/if}</SwitchPrimitive.Thumb>
		{/snippet}
	</SwitchPrimitive.Root>
</span>
<style>
	:global {
	.rx-switch-field{--rx-sw-w:52px;--rx-sw-h:32px;--rx-sw-pad:3px;display:inline-flex;align-items:center;gap:10px;color:rgb(var(--rx-text));font-size:14px;cursor:pointer;user-select:none;-webkit-tap-highlight-color:transparent}.rx-switch-field--label-left{flex-direction:row-reverse}.rx-switch-field--disabled{opacity:.45;cursor:not-allowed}.rx-switch{position:relative;isolation:isolate;flex:none;box-sizing:border-box;width:var(--rx-sw-w);height:var(--rx-sw-h);padding:0;border:0;border-radius:999px;background:rgb(var(--rx-text)/.2);cursor:inherit;outline:none;overflow:visible;transform-style:preserve-3d;transition:transform 260ms cubic-bezier(.34,1.56,.64,1),background-color 480ms cubic-bezier(.22,1,.36,1),box-shadow 480ms ease}.rx-switch--sm{--rx-sw-w:40px;--rx-sw-h:24px;--rx-sw-pad:2.5px}.rx-switch--lg{--rx-sw-w:64px;--rx-sw-h:38px;--rx-sw-pad:4px}.rx-switch--rounded{border-radius:calc(var(--rx-sw-h)*.34)}.rx-switch--square{border-radius:7px}.rx-switch[data-state=checked]{background:rgb(var(--rx-color))}.rx-switch:focus-visible{outline:2px solid rgb(var(--rx-color)/.8);outline-offset:3px}.rx-switch:disabled{cursor:not-allowed}.rx-switch__thumb{position:absolute;z-index:3;top:var(--rx-sw-pad);left:var(--rx-sw-pad);display:flex;align-items:center;justify-content:center;width:calc(var(--rx-sw-h) - var(--rx-sw-pad)*2);height:calc(var(--rx-sw-h) - var(--rx-sw-pad)*2);border-radius:calc((var(--rx-sw-h) - var(--rx-sw-pad)*2)/2);background:rgb(var(--rx-background));color:rgb(var(--rx-text)/.5);transition:transform 480ms cubic-bezier(.34,1.56,.64,1),width 480ms cubic-bezier(.34,1.56,.64,1),border-radius 480ms cubic-bezier(.22,1,.36,1),background-color 480ms ease,box-shadow 480ms ease;will-change:transform,width}.rx-switch--rounded .rx-switch__thumb{border-radius:calc((var(--rx-sw-h) - var(--rx-sw-pad)*2)*.32)}.rx-switch--square .rx-switch__thumb{border-radius:5px}.rx-switch[data-state=checked] .rx-switch__thumb{transform:translateX(calc(var(--rx-sw-w) - var(--rx-sw-h)));color:rgb(var(--rx-color))}.rx-switch-field--pressed .rx-switch--variant-base .rx-switch__thumb{width:calc((var(--rx-sw-h) - var(--rx-sw-pad)*2)*1.32)}.rx-switch-field--pressed .rx-switch--variant-base[data-state=checked] .rx-switch__thumb{transform:translateX(calc(var(--rx-sw-w) - var(--rx-sw-h) - (var(--rx-sw-h) - var(--rx-sw-pad)*2)*.32))}
	.rx-switch__icon{position:absolute;display:grid;place-items:center;width:56%;height:56%;transition:opacity 200ms ease,transform 320ms cubic-bezier(.34,1.56,.64,1)}.rx-switch__icon svg{width:100%;height:100%;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.rx-switch__icon--on{opacity:0;transform:scale(.4) rotate(-45deg)}.rx-switch__icon--off{opacity:.55;transform:scale(1)}.rx-switch[data-state=checked] .rx-switch__icon--on{opacity:1;transform:scale(1) rotate(0)}.rx-switch[data-state=checked] .rx-switch__icon--off{opacity:0;transform:scale(.4)}.rx-switch__spinner{width:60%;height:60%;box-sizing:border-box;border:2px solid currentColor;border-right-color:transparent;border-radius:999px;animation:rx-switch-spin .7s linear infinite}@keyframes rx-switch-spin{to{transform:rotate(1turn)}}
	.rx-switch__glow{position:absolute;inset:-2px;z-index:1;border-radius:inherit;padding:1.5px;pointer-events:none;background:radial-gradient(42px circle at var(--rx-gx,50%) var(--rx-gy,50%),rgb(var(--rx-color)/.75),rgb(var(--rx-color)/.4) 42%,rgb(var(--rx-color)/.12) 66%,rgb(var(--rx-color)/0) 82%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask-composite:exclude;opacity:calc(var(--rx-glow,0)*.9);transition:opacity 140ms}.rx-switch__ripples{position:absolute;inset:0;z-index:2;border-radius:inherit;overflow:hidden;pointer-events:none}.rx-switch__ripple{position:absolute;border-radius:50%;transform:translate(-50%,-50%) scale(0);background:radial-gradient(circle,rgb(var(--rx-background)/.45) 0%,rgb(var(--rx-background)/.22) 30%,rgb(var(--rx-background)/.08) 52%,transparent 72%);opacity:0;animation:rx-switch-ripple-scale 640ms cubic-bezier(.22,1,.36,1) forwards,rx-switch-ripple-fade 640ms cubic-bezier(.25,.1,.25,1) forwards}@keyframes rx-switch-ripple-scale{to{transform:translate(-50%,-50%) scale(1)}}@keyframes rx-switch-ripple-fade{from{opacity:.85}to{opacity:0}}
	.rx-switch__stars,.rx-switch__clouds,.rx-switch__state,.rx-switch__liquid,.rx-switch__goo-def{display:none}.rx-switch--variant-day-night{--rx-sw-w:58px;--rx-sw-h:30px;--rx-sw-pad:3px;background:linear-gradient(160deg,rgb(var(--rx-text)/.9) 0%,rgb(var(--rx-bg)) 100%);box-shadow:inset 0 0 0 1px rgb(var(--rx-background)/.06);overflow:hidden;transition:background 520ms ease}.rx-switch--variant-day-night.rx-switch--sm{--rx-sw-w:46px;--rx-sw-h:24px;--rx-sw-pad:2.5px}.rx-switch--variant-day-night.rx-switch--lg{--rx-sw-w:70px;--rx-sw-h:36px;--rx-sw-pad:4px}.rx-switch--variant-day-night[data-state=checked]{background:linear-gradient(160deg,rgb(var(--rx-color)) 0%,hsl(from rgb(var(--rx-color)) h s calc(l*.72)) 100%)}.rx-switch--variant-day-night .rx-switch__stars,.rx-switch--variant-day-night .rx-switch__clouds{display:block;position:absolute;inset:0;pointer-events:none}.rx-switch__stars i{position:absolute;left:var(--x);top:var(--y);width:2px;height:2px;border-radius:999px;background:rgb(var(--rx-background));opacity:calc(var(--d)*.9);transition:opacity 520ms ease}.rx-switch--variant-day-night[data-state=checked] .rx-switch__stars i{opacity:0}.rx-switch__clouds i{position:absolute;left:var(--x);top:var(--y);width:calc(10px*var(--s));height:calc(4px*var(--s));border-radius:999px;background:rgb(var(--rx-background)/.9);box-shadow:calc(4px*var(--s)) calc(-1px*var(--s)) 0 calc(-.5px*var(--s)) rgb(var(--rx-background)/.9);opacity:0;transform:translateX(-4px);transition:opacity 520ms ease,transform 520ms ease}.rx-switch--variant-day-night[data-state=checked] .rx-switch__clouds i{opacity:1;transform:translateX(0)}.rx-switch--variant-day-night .rx-switch__thumb{background:rgb(var(--rx-gray));box-shadow:0 1px 3px rgb(var(--rx-bg)/.35),inset -2px -2px 4px rgb(var(--rx-bg)/.12);transition:transform 520ms cubic-bezier(.34,1.45,.64,1),background-color 520ms ease,box-shadow 520ms ease}.rx-switch--variant-day-night[data-state=checked] .rx-switch__thumb{background:rgb(var(--rx-background));box-shadow:0 0 6px rgb(var(--rx-color)),0 0 14px rgb(var(--rx-color)/.7),inset -1px -1px 3px rgb(var(--rx-color)/.35)}.rx-switch__craters{position:absolute;inset:0;border-radius:inherit;opacity:1;transition:opacity 520ms ease}.rx-switch__craters:before,.rx-switch__craters:after{content:'';position:absolute;border-radius:999px;background:rgb(var(--rx-bg)/.1);box-shadow:inset 1px 1px 1px rgb(var(--rx-bg)/.14)}.rx-switch__craters:before{width:26%;height:26%;left:24%;top:22%}.rx-switch__craters:after{width:18%;height:18%;left:54%;top:54%}.rx-switch--variant-day-night[data-state=checked] .rx-switch__craters{opacity:0}.rx-switch--variant-day-night .rx-switch__icon{display:none}
	.rx-switch--variant-dot{--rx-sw-w:42px;--rx-sw-h:24px;--rx-sw-pad:5px;background:rgb(var(--rx-surface));border:1px solid rgb(var(--rx-border-strong));box-shadow:inset 0 1px 3px rgb(var(--rx-bg)/.14)}.rx-switch--variant-dot[data-state=checked]{background:rgb(var(--rx-background))}.rx-switch--variant-dot .rx-switch__thumb{width:14px;height:14px;background:rgb(var(--rx-text-muted));box-shadow:none;transition:transform 300ms cubic-bezier(.34,1.5,.6,1),scale 180ms ease,background-color 240ms ease}.rx-switch--variant-dot:hover .rx-switch__thumb{scale:1.12}.rx-switch-field--pressed .rx-switch--variant-dot .rx-switch__thumb{scale:.84}.rx-switch--variant-dot[data-state=checked] .rx-switch__thumb{transform:translateX(18px);background:rgb(var(--rx-color))}.rx-switch--variant-dot .rx-switch__icon{display:none}
	.rx-switch--variant-glow{--rx-sw-pad:4px;background:rgb(var(--rx-text)/.2);box-shadow:inset 0 0 0 1px rgb(var(--rx-background)/.08);transition:background 420ms ease,box-shadow 420ms ease}.rx-switch--variant-glow[data-state=checked]{background:linear-gradient(90deg,hsl(from rgb(var(--rx-color)) h s calc(l*.48)),hsl(from rgb(var(--rx-color)) h s calc(l*.26)));box-shadow:inset 0 0 0 1px rgb(var(--rx-color)/.65),inset 0 0 12px rgb(var(--rx-color)/.28),0 0 8px rgb(var(--rx-color)/.5),0 0 18px rgb(var(--rx-color)/.3)}.rx-switch--variant-glow:after{content:'';position:absolute;inset:0;z-index:-1;border-radius:inherit;box-shadow:inset 0 0 0 1px rgb(var(--rx-color)/.75),inset 0 0 14px rgb(var(--rx-color)/.38),0 0 12px rgb(var(--rx-color)/.65),0 0 26px rgb(var(--rx-color)/.45);opacity:0}.rx-switch--variant-glow[data-state=checked]:after{animation:rx-switch-breathe 2.2s ease-in-out infinite}@keyframes rx-switch-breathe{0%,100%{opacity:0}50%{opacity:1}}.rx-switch--variant-glow .rx-switch__thumb{background:radial-gradient(circle at 50% 38%,rgb(var(--rx-muted)),rgb(var(--rx-text-muted)) 78%);box-shadow:inset 0 -1px 2px rgb(var(--rx-bg)/.35);transition:transform 420ms cubic-bezier(.34,1.5,.6,1),background 420ms ease,box-shadow 420ms ease}.rx-switch--variant-glow[data-state=checked] .rx-switch__thumb{background:radial-gradient(circle at 50% 36%,rgb(var(--rx-background)),rgb(var(--rx-color)) 72%);box-shadow:0 0 5px rgb(var(--rx-color)),0 0 13px rgb(var(--rx-color)/.65),inset 0 0 3px rgb(var(--rx-background)/.6)}.rx-switch-field--pressed .rx-switch--variant-glow .rx-switch__thumb{transform:scaleX(1.12) scaleY(.92)}.rx-switch-field--pressed .rx-switch--variant-glow[data-state=checked] .rx-switch__thumb{transform:translateX(calc(var(--rx-sw-w) - var(--rx-sw-h))) scaleX(1.12) scaleY(.92)}.rx-switch--variant-glow .rx-switch__icon{display:none}
	.rx-switch--variant-label{--rx-sw-w:64px;--rx-sw-h:30px;--rx-sw-pad:3px;overflow:hidden;transition:background-color 440ms ease}.rx-switch--variant-label.rx-switch--sm{--rx-sw-w:52px;--rx-sw-h:24px;--rx-sw-pad:2.5px}.rx-switch--variant-label.rx-switch--lg{--rx-sw-w:76px;--rx-sw-h:36px;--rx-sw-pad:4px}.rx-switch--variant-label .rx-switch__state{display:block;position:absolute;top:50%;transform:translateY(-50%);font-size:calc(var(--rx-sw-h)*.34);font-weight:700;letter-spacing:.04em;line-height:1;transition:opacity 240ms ease;pointer-events:none}.rx-switch__state--on{left:calc(var(--rx-sw-h)*.34);color:rgb(var(--rx-background));opacity:0}.rx-switch__state--off{right:calc(var(--rx-sw-h)*.34);color:rgb(var(--rx-background)/.55);opacity:1}.rx-switch--variant-label[data-state=checked] .rx-switch__state--on{opacity:1}.rx-switch--variant-label[data-state=checked] .rx-switch__state--off{opacity:0}.rx-switch--variant-label .rx-switch__thumb{box-shadow:0 1px 2px rgb(var(--rx-bg)/.3),0 3px 8px rgb(var(--rx-bg)/.25);transition:transform 440ms cubic-bezier(.34,1.45,.64,1)}.rx-switch--variant-label .rx-switch__icon{display:none}
	.rx-switch--variant-liquid{--rx-sw-pad:4px;overflow:hidden;background:rgb(var(--rx-text)/.2);transition:background-color 300ms ease}.rx-switch--variant-liquid[data-state=checked]{background:rgb(var(--rx-color)/.32)}.rx-switch--variant-liquid .rx-switch__liquid,.rx-switch--variant-liquid .rx-switch__goo-def{display:block}.rx-switch--variant-liquid .rx-switch__liquid{position:absolute;inset:0;pointer-events:none}.rx-switch--variant-liquid .rx-switch__thumb,.rx-switch__trail{background:rgb(var(--rx-background))}.rx-switch--variant-liquid[data-state=checked] .rx-switch__thumb,.rx-switch--variant-liquid[data-state=checked] .rx-switch__trail{background:rgb(var(--rx-color))}.rx-switch--variant-liquid .rx-switch__thumb{transition:transform 300ms cubic-bezier(.34,1.4,.6,1)}.rx-switch__trail{position:absolute;top:var(--rx-sw-pad);left:calc(var(--rx-sw-pad) + var(--rx-liquid-inset));width:calc((var(--rx-sw-h) - var(--rx-sw-pad)*2)*var(--rx-liquid-scale));height:calc((var(--rx-sw-h) - var(--rx-sw-pad)*2)*var(--rx-liquid-scale));border-radius:999px;transition:transform var(--rx-liquid-dur) cubic-bezier(.4,0,.2,1)}.rx-switch__trail--one{--rx-liquid-inset:1.3px;--rx-liquid-scale:.9;--rx-liquid-dur:396ms}.rx-switch__trail--two{--rx-liquid-inset:3.1px;--rx-liquid-scale:.76;--rx-liquid-dur:486ms}.rx-switch--variant-liquid[data-state=checked] .rx-switch__trail{transform:translateX(calc(var(--rx-sw-w) - var(--rx-sw-h)))}.rx-switch-field--pressed .rx-switch--variant-liquid .rx-switch__thumb{transform:translateX(calc(var(--rx-sw-h)*.12)) scaleX(1.1) scaleY(.93)}.rx-switch-field--pressed .rx-switch--variant-liquid[data-state=checked] .rx-switch__thumb{transform:translateX(calc(var(--rx-sw-w) - var(--rx-sw-h) - var(--rx-sw-h)*.12)) scaleX(1.1) scaleY(.93)}.rx-switch--variant-liquid .rx-switch__icon{display:none}
	.rx-switch--variant-material{--rx-sw-pad:3px;background:transparent;box-shadow:inset 0 0 0 2px rgb(var(--rx-text)/.3);transition:background-color 380ms ease,box-shadow 380ms ease}.rx-switch--variant-material[data-state=checked]{background:rgb(var(--rx-color));box-shadow:inset 0 0 0 2px rgb(var(--rx-color))}.rx-switch--variant-material .rx-switch__thumb{top:50%;background:rgb(var(--rx-text)/.3);color:rgb(var(--rx-color));transform:translateY(-50%) scale(.5);transition:transform 380ms cubic-bezier(.34,1.4,.64,1),background-color 380ms ease}.rx-switch--variant-material[data-state=checked] .rx-switch__thumb{background:rgb(var(--rx-background));transform:translateY(-50%) translateX(calc(var(--rx-sw-w) - var(--rx-sw-h))) scale(1)}.rx-switch-field--pressed .rx-switch--variant-material .rx-switch__thumb{transform:translateY(-50%) scale(.72)}.rx-switch-field--pressed .rx-switch--variant-material[data-state=checked] .rx-switch__thumb{transform:translateY(-50%) translateX(calc(var(--rx-sw-w) - var(--rx-sw-h))) scale(1.1)}.rx-switch--variant-material .rx-switch__icon--off{display:none}.rx-switch--variant-material .rx-switch__icon--on{opacity:0;transform:scale(.4);transition:opacity 200ms ease,transform 380ms cubic-bezier(.34,1.4,.64,1)}.rx-switch--variant-material[data-state=checked] .rx-switch__icon--on{opacity:1;transform:scale(1)}
	@media(prefers-reduced-motion:reduce){.rx-switch,.rx-switch__thumb,.rx-switch__icon,.rx-switch__craters,.rx-switch__stars i,.rx-switch__clouds i,.rx-switch__state,.rx-switch__trail{transition-duration:0ms}.rx-switch__ripple{display:none}.rx-switch--variant-glow[data-state=checked]:after{animation:none;opacity:0}.rx-switch--variant-liquid .rx-switch__liquid{filter:none!important}.rx-switch__spinner{animation-duration:1.4s}}
	}
</style>
