import { fireEvent, render, screen } from '@testing-library/svelte';
import { afterEach, describe, expect, it, vi } from 'vitest';
import Harness from './switch-test-harness.svelte';
describe('Switch', () => {
	afterEach(()=>vi.unstubAllGlobals());
	it('round-trips binding and fires its callback', async () => { render(Harness); const control = screen.getByRole('switch'); await fireEvent.click(control); expect(screen.getByLabelText('switch value').textContent).toBe('true'); expect(screen.getByLabelText('switch calls').textContent).toBe('1'); await fireEvent.click(screen.getByText('Set switch')); expect(control.getAttribute('data-state')).toBe('checked'); });
	it('toggles with space', async () => { render(Harness); const control = screen.getByRole('switch'); control.focus(); await fireEvent.keyDown(control, { key: ' ', code: 'Space' }); await fireEvent.keyUp(control, { key: ' ', code: 'Space' }); expect(control.getAttribute('data-state')).toBe('checked'); });
	it('blocks disabled and loading interaction', async () => { for (const props of [{ disabled: true }, { loading: true }]) { const view = render(Harness, props); await fireEvent.click(screen.getByRole('switch')); expect(screen.getByRole('switch').getAttribute('data-state')).toBe('unchecked'); view.unmount(); } });
	it.each(['base','day-night','dot','glow','label','liquid','material'] as const)('maps the %s source variant',(variant)=>{render(Harness,{variant});expect(screen.getByRole('switch').className).toContain(`rx-switch--variant-${variant}`)});
	it('creates a pointer-coordinate base ripple and supports directional dragging',async()=>{render(Harness,{variant:'base',glow:true});const control=screen.getByRole('switch');Object.defineProperty(control,'getBoundingClientRect',{value:()=>({left:0,top:0,width:52,height:32,right:52,bottom:32,x:0,y:0,toJSON(){}})});await fireEvent.pointerDown(control,{pointerId:1,clientX:8,clientY:10});expect(control.querySelectorAll('.rx-switch__ripple')).toHaveLength(1);await fireEvent.pointerMove(control,{pointerId:1,clientX:28,clientY:10});expect(screen.getByLabelText('switch value').textContent).toBe('true');await fireEvent.pointerUp(control,{pointerId:1,clientX:28,clientY:10})});
	it('rAF-batches its 120px proximity field and invalidates geometry on resize',async()=>{render(Harness,{variant:'base',glow:true});const control=screen.getByRole('switch');let left=0;Object.defineProperty(control,'getBoundingClientRect',{value:()=>({left,top:0,width:52,height:32,right:left+52,bottom:32,x:left,y:0,toJSON(){}})});await fireEvent.pointerMove(document,{clientX:10,clientY:10});await vi.waitFor(()=>expect(control.style.getPropertyValue('--rx-gx')).toBe('10px'));expect(Number(control.style.getPropertyValue('--rx-glow'))).toBeGreaterThan(0);left=8;window.dispatchEvent(new Event('resize'));await vi.waitFor(()=>expect(control.style.getPropertyValue('--rx-gx')).toBe('2px'));});
	it('suppresses the base ripple when reduced motion is requested',async()=>{vi.stubGlobal('matchMedia',()=>({matches:true}));render(Harness);await fireEvent.pointerDown(screen.getByRole('switch'),{clientX:4,clientY:7});expect(document.querySelectorAll('.rx-switch__ripple')).toHaveLength(0)});
});
