<script lang="ts" module>import type { Snippet } from 'svelte'; export interface TabsListProps { children: Snippet }</script>
<script lang="ts">
	import { Tabs as Primitive } from 'bits-ui'; import { getTabsContext } from './context';
	let { children }: TabsListProps = $props(); const config = getTabsContext();
	function track(node: HTMLElement) {
		let frame=0; let previous:{x:number;y:number;w:number;h:number}|undefined; let animation:Animation|undefined;
		const indicator=node.querySelector<HTMLElement>('.rx-indicator'); const mask=node.querySelector<HTMLElement>('.rx-indicator-mask');
		const rebuildMask=()=>{if(!mask)return;mask.replaceChildren(...[...node.querySelectorAll<HTMLElement>(':scope > [role=tab]')].map(tab=>{const clone=tab.cloneNode(true) as HTMLElement;clone.removeAttribute('id');clone.removeAttribute('role');clone.removeAttribute('data-state');clone.removeAttribute('aria-selected');clone.removeAttribute('aria-controls');clone.className='rx-mask-label';clone.setAttribute('aria-hidden','true');clone.setAttribute('tabindex','-1');clone.setAttribute('inert','');for(const descendant of clone.querySelectorAll<HTMLElement>('a,button,input,select,textarea,[tabindex]')){descendant.setAttribute('tabindex','-1');descendant.setAttribute('inert','')}return clone}))};
		const animateChrome=(from:{x:number;y:number;w:number;h:number},to:{x:number;y:number;w:number;h:number})=>{if(!indicator)return;animation?.cancel();const frames:Keyframe[]=[];for(let i=0;i<=30;i++){const t=i/30;const spring=1-Math.exp(-7*t)*Math.cos(11*t);const lead=1-Math.exp(-8*t)*Math.cos(12*t);const left=from.x+(to.x-from.x)*spring;const right=from.x+from.w+(to.x+to.w-from.x-from.w)*lead;frames.push({transform:`translate3d(${left}px,${to.y}px,0)`,width:`${Math.max(1,right-left)}px`})}animation=indicator.animate(frames,{duration:620,easing:'linear',fill:'forwards'});animation.onfinish=()=>{indicator.style.transform=`translate3d(${to.x}px,${to.y}px,0)`;indicator.style.width=`${to.w}px`;animation=undefined}};
		const measure=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const active=node.querySelector<HTMLElement>(':scope > [role=tab][data-state=active]');if(!active||!indicator)return;const next={x:active.offsetLeft,y:active.offsetTop,w:active.offsetWidth,h:active.offsetHeight};const variant=node.dataset.variant;node.style.setProperty('--rx-i-x',`${next.x}px`);node.style.setProperty('--rx-i-y',`${next.y}px`);node.style.setProperty('--rx-i-w',`${next.w}px`);node.style.setProperty('--rx-i-h',`${next.h}px`);indicator.classList.add('is-ready');if(previous){indicator.classList.remove('is-pop','is-hop','is-goo');void indicator.offsetWidth;if(variant==='chrome')animateChrome(previous,next);else if(variant==='gooey'){const left=Math.min(previous.x,next.x),right=Math.max(previous.x+previous.w,next.x+next.w);indicator.style.setProperty('--rx-union-x',`${left}px`);indicator.style.setProperty('--rx-union-w',`${right-left}px`);indicator.classList.add('is-goo')}else if(variant==='bubble')indicator.classList.add('is-hop');else indicator.classList.add('is-pop')}previous=next;rebuildMask()})};
		const down=(event:PointerEvent)=>{const target=(event.target as Element).closest<HTMLElement>('[role=tab]');if(!target||target.hasAttribute('disabled'))return;const rect=node.getBoundingClientRect();const x=event.clientX-rect.left,y=event.clientY-rect.top;const radius=Math.max(Math.hypot(x,y),Math.hypot(rect.width-x,y),Math.hypot(x,rect.height-y));const ripple=document.createElement('span');ripple.className='rx-tab-ripple';ripple.style.cssText=`left:${x}px;top:${y}px;width:${radius*2}px;height:${radius*2}px`;node.querySelector('.rx-ripples')?.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove(),{once:true})};
		const move=(event:PointerEvent)=>{const rect=node.getBoundingClientRect();for(const tab of node.querySelectorAll<HTMLElement>(':scope > [role=tab]')){tab.style.setProperty('--rx-mx',`${event.clientX-rect.left-tab.offsetLeft}px`);tab.style.setProperty('--rx-my',`${event.clientY-rect.top-tab.offsetTop}px`)}};
		const ro=new ResizeObserver(measure);ro.observe(node);const mo=new MutationObserver(measure);mo.observe(node,{attributes:true,subtree:true,attributeFilter:['data-state']});node.addEventListener('pointerdown',down);node.addEventListener('pointermove',move);document.fonts?.ready.then(measure);measure();return()=>{ro.disconnect();mo.disconnect();node.removeEventListener('pointerdown',down);node.removeEventListener('pointermove',move);animation?.cancel();cancelAnimationFrame(frame)}}
</script>
<Primitive.List class="rx-list" data-variant={config.variant} data-orientation={config.orientation} {@attach track}><span class="rx-ripples" aria-hidden="true" inert></span><span class="rx-indicator" aria-hidden="true" inert><span class="rx-indicator-mask"></span><span class="rx-indicator-dot"></span></span>{@render children()}</Primitive.List>
<style>
	:global {
		.rx-tabs{--rx-tab-h:40px;--rx-tab-px:14px;--rx-tab-r:20px}.rx-tabs[data-size=sm]{--rx-tab-h:32px;--rx-tab-px:11px}.rx-tabs[data-size=lg]{--rx-tab-h:48px;--rx-tab-px:18px}.rx-tabs[data-radius=none]{--rx-tab-r:0}.rx-tabs[data-radius=subtle]{--rx-tab-r:8px}.rx-tabs[data-radius=rounded]{--rx-tab-r:12px}.rx-tabs[data-radius=squircle]{--rx-tab-r:20px}.rx-tabs[data-block] .rx-list{display:flex;width:100%}.rx-tabs[data-block] .rx-trigger{flex:1 1 0;min-width:0}
		.rx-list{position:relative;display:inline-flex;align-self:flex-start;gap:2px;padding:5px;border:1px solid rgb(var(--rx-border));border-radius:calc(var(--rx-tab-r) + 5px);background:rgb(var(--rx-surface-2));max-width:100%;isolation:isolate}.rx-list[data-orientation=vertical]{flex-direction:column;padding-left:10px}.rx-ripples{position:absolute;inset:0;z-index:0;border-radius:inherit;overflow:hidden;pointer-events:none}.rx-tab-ripple{position:absolute;border-radius:50%;opacity:0;transform:translate(-50%,-50%) scale(0);background:radial-gradient(circle,rgb(var(--rx-text)/.22) 0%,rgb(var(--rx-text)/.12) 30%,rgb(var(--rx-text)/.04) 55%,transparent 72%);animation:rx-tab-ripple-scale 720ms cubic-bezier(.22,1,.36,1) forwards,rx-tab-ripple-fade 720ms cubic-bezier(.25,.1,.25,1) forwards}
		.rx-indicator{position:absolute;z-index:1;left:0;top:0;width:var(--rx-i-w,0);height:var(--rx-i-h,var(--rx-tab-h));transform:translate3d(var(--rx-i-x,0),var(--rx-i-y,0),0);border-radius:var(--rx-tab-r);background:rgb(var(--rx-color));box-shadow:0 1px 2px rgb(var(--rx-shadow)/.28);visibility:hidden;pointer-events:none;overflow:hidden;transition:width 420ms cubic-bezier(.34,1.4,.64,1),height 420ms cubic-bezier(.34,1.4,.64,1),transform 420ms cubic-bezier(.34,1.4,.64,1)}.rx-indicator.is-ready{visibility:visible}.rx-indicator.is-pop{animation:rx-tab-pop 460ms cubic-bezier(.34,1.4,.64,1)}
		.rx-indicator-mask{position:absolute;left:calc(-1 * var(--rx-i-x,0));top:calc(-1 * var(--rx-i-y,0));display:flex;gap:2px;padding:5px;width:max-content;transition:left 420ms cubic-bezier(.34,1.4,.64,1),top 420ms cubic-bezier(.34,1.4,.64,1)}.rx-mask-label{display:inline-flex;align-items:center;justify-content:center;height:var(--rx-tab-h);padding:0 var(--rx-tab-px);border:0!important;background:none!important;color:var(--rx-color-foreground, rgb(var(--rx-dark)))!important;-webkit-text-fill-color:currentColor!important;font:inherit;font-weight:500;white-space:nowrap;pointer-events:none}.rx-mask-label[disabled]{opacity:.4}
		.rx-list[data-variant=bubble]{overflow-x:auto;padding:6px 0 12px;border:0;background:transparent}.rx-list[data-variant=bubble] .rx-indicator{top:auto;bottom:2px;width:8px!important;height:8px!important;margin-left:calc(var(--rx-i-w)/2 - 4px);border-radius:50%;box-shadow:0 0 10px rgb(var(--rx-color)/.6);overflow:visible;background:transparent}.rx-list[data-variant=bubble] .rx-indicator-mask{display:none}.rx-indicator-dot{display:block;width:100%;height:100%;border-radius:inherit;background:rgb(var(--rx-color))}.rx-list[data-variant=bubble] .rx-indicator.is-hop .rx-indicator-dot{animation:rx-tab-hop 440ms cubic-bezier(.4,0,.2,1)}
		.rx-list[data-variant=card]{overflow-x:auto;padding:6px 0 0;border:0;border-bottom:1px solid rgb(var(--rx-border));border-radius:0;background:transparent}.rx-list[data-variant=card] .rx-indicator{display:none}
		.rx-list[data-variant=gooey]{overflow-x:auto}.rx-list[data-variant=gooey] .rx-indicator{transition:transform 460ms cubic-bezier(.5,1.5,.5,1),width 460ms cubic-bezier(.5,1.5,.5,1)}.rx-list[data-variant=gooey] .rx-indicator.is-goo{animation:rx-tab-goo 460ms cubic-bezier(.5,1.5,.5,1)}
		.rx-list[data-variant=neon]{overflow-x:auto;padding:6px 0 3px;border:0;border-bottom:1px solid rgb(var(--rx-border));border-radius:0;background:transparent}.rx-list[data-variant=neon] .rx-indicator{top:auto;bottom:0;height:2px!important;border-radius:2px;background:linear-gradient(90deg,rgb(var(--rx-color)),hsl(from rgb(var(--rx-color)) calc(h + 65) s l),rgb(var(--rx-color)));background-size:200% 100%;box-shadow:0 0 8px rgb(var(--rx-color)/.8),0 0 16px rgb(var(--rx-color)/.55);animation:rx-tab-neon 3s linear infinite}.rx-list[data-variant=neon] .rx-indicator-mask{display:none}
		.rx-list[data-variant=chrome]{padding:6px 8px 0;overflow:visible;border:0;border-radius:14px 14px 0 0;background:rgb(var(--rx-surface));border-bottom:1px solid rgb(var(--rx-border))}.rx-list[data-variant=chrome] .rx-indicator{top:auto;bottom:0;border-radius:var(--rx-tab-r) var(--rx-tab-r) 0 0;background:rgb(var(--rx-surface-2));overflow:visible}.rx-list[data-variant=chrome] .rx-indicator:before,.rx-list[data-variant=chrome] .rx-indicator:after{content:"";position:absolute;bottom:0;width:var(--rx-tab-r);height:var(--rx-tab-r);background:rgb(var(--rx-surface-2))}.rx-list[data-variant=chrome] .rx-indicator:before{left:calc(-1 * var(--rx-tab-r));mask:radial-gradient(circle at 0 0,transparent calc(var(--rx-tab-r) - .5px),#000 var(--rx-tab-r))}.rx-list[data-variant=chrome] .rx-indicator:after{right:calc(-1 * var(--rx-tab-r));mask:radial-gradient(circle at 100% 0,transparent calc(var(--rx-tab-r) - .5px),#000 var(--rx-tab-r))}
		.rx-list[data-orientation=vertical] .rx-indicator{left:0;width:3px!important;border-radius:3px;background:rgb(var(--rx-color));box-shadow:none}.rx-list[data-orientation=vertical] .rx-indicator-mask{display:none}
		@keyframes rx-tab-ripple-scale{to{transform:translate(-50%,-50%) scale(1)}}@keyframes rx-tab-ripple-fade{from{opacity:.8}to{opacity:0}}@keyframes rx-tab-pop{0%{scale:1}38%{scale:1.099}100%{scale:1}}@keyframes rx-tab-hop{45%{transform:translateY(-14px) scale(.8)}}@keyframes rx-tab-goo{0%{transform:translate3d(var(--rx-i-x),var(--rx-i-y),0);width:var(--rx-i-w)}42%{transform:translate3d(var(--rx-union-x),var(--rx-i-y),0);width:var(--rx-union-w)}100%{transform:translate3d(var(--rx-i-x),var(--rx-i-y),0);width:var(--rx-i-w)}}@keyframes rx-tab-neon{to{background-position:-200% 0}}
		.rx-indicator{z-index:3}
		@media(prefers-reduced-motion:reduce){.rx-indicator{transition:none!important;animation:none!important}.rx-trigger{transition:color 200ms ease!important}.rx-tab-ripple{display:none}}
	}
</style>
