<script lang="ts" module>
	import type { Snippet } from 'svelte';
	export interface TabsTriggerProps { value: string; disabled?: boolean; icon?: Snippet; children: Snippet; }
</script>
<script lang="ts">
	import { Tabs as Primitive } from 'bits-ui';
	let { value, disabled = false, icon, children }: TabsTriggerProps = $props();
</script>
<Primitive.Trigger {value} {disabled} class="rx-trigger">{#if icon}<span class="rx-tab-icon">{@render icon()}</span>{/if}<span class="rx-tab-label">{@render children()}</span></Primitive.Trigger>
<style>
	:global {
		.rx-trigger{position:relative;z-index:2;overflow:visible;display:inline-flex;align-items:center;justify-content:center;gap:.45rem;height:var(--rx-tab-h);padding:0 var(--rx-tab-px);border:0;border-radius:var(--rx-tab-r);color:rgb(var(--rx-text-secondary));background:radial-gradient(140px circle at var(--rx-mx,50%) var(--rx-my,50%),rgb(var(--rx-text)),rgb(var(--rx-text)) 25%,rgb(var(--rx-text-secondary)) 100%);background-clip:text;-webkit-background-clip:text;-webkit-text-fill-color:transparent;font:inherit;font-weight:500;line-height:1;white-space:nowrap;cursor:pointer;user-select:none;transition:opacity 120ms linear,transform 320ms cubic-bezier(.34,1.56,.64,1),color 240ms ease}
		.rx-trigger:active:not(:disabled){transform:scale(.92)}.rx-trigger:focus-visible{outline:2px solid rgb(var(--rx-color)/.75);outline-offset:2px}.rx-trigger:disabled{opacity:.4;cursor:not-allowed}.rx-tab-label{min-width:0;overflow:hidden;text-overflow:ellipsis}.rx-tab-icon{display:inline-flex}.rx-tab-icon :global(svg){width:18px;height:18px}
		.rx-list[data-variant=bubble] .rx-trigger[data-state=active],.rx-list[data-variant=neon] .rx-trigger[data-state=active]{background:none;color:rgb(var(--rx-color));-webkit-text-fill-color:currentColor}.rx-list[data-variant=bubble] .rx-trigger:hover:not(:disabled),.rx-list[data-variant=neon] .rx-trigger:hover:not(:disabled){color:rgb(var(--rx-text));-webkit-text-fill-color:currentColor}.rx-list[data-variant=neon] .rx-trigger[data-state=active]{color:rgb(var(--rx-light));text-shadow:0 0 8px rgb(var(--rx-color)/.7),0 0 16px rgb(var(--rx-color)/.45)}
		.rx-list[data-variant=card] .rx-trigger{border:1px solid transparent;border-bottom:0;border-radius:10px 10px 0 0}.rx-list[data-variant=card] .rx-trigger[data-state=active]{background:rgb(var(--rx-surface-2));border-color:rgb(var(--rx-border));color:rgb(var(--rx-color));-webkit-text-fill-color:currentColor}.rx-list[data-variant=card] .rx-trigger[data-state=active]:before{content:"";position:absolute;left:-1px;right:-1px;top:-1px;height:2px;border-radius:2px;background:rgb(var(--rx-color));box-shadow:0 0 8px rgb(var(--rx-color)/.45)}.rx-list[data-variant=card] .rx-trigger[data-state=active]:after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:2px;background:rgb(var(--rx-surface-2))}
		:root[data-theme='dark'] .rx-list[data-variant=bubble] .rx-trigger[data-state=active],:root[data-theme='dark'] .rx-list[data-variant=card] .rx-trigger[data-state=active]{color:color-mix(in srgb,rgb(var(--rx-color)) 78%,rgb(var(--rx-light)));-webkit-text-fill-color:currentColor}
		.rx-list[data-variant=gooey] .rx-trigger[data-state=active]{background:none;color:var(--rx-color-foreground, rgb(var(--rx-dark)));-webkit-text-fill-color:currentColor}.rx-list[data-variant=chrome] .rx-trigger{background:none;color:rgb(var(--rx-text-secondary));-webkit-text-fill-color:currentColor}.rx-list[data-variant=chrome] .rx-trigger[data-state=active]{color:rgb(var(--rx-text));font-weight:600}.rx-list[data-variant=chrome] .rx-trigger:after{content:"";position:absolute;right:-1px;top:50%;width:1px;height:42%;background:rgb(var(--rx-border));transform:translateY(-50%);transition:opacity 180ms ease}.rx-list[data-variant=chrome] .rx-trigger[data-state=active]:after,.rx-list[data-variant=chrome] .rx-trigger:has(+[data-state=active]):after,.rx-list[data-variant=chrome] .rx-trigger:last-child:after{opacity:0}
		.rx-list:not([data-variant=bubble]):not([data-variant=card]):not([data-variant=neon]):not([data-variant=chrome]) .rx-trigger[data-state=active]{background:none;color:rgb(var(--rx-text-secondary));-webkit-text-fill-color:currentColor}
		.rx-list[data-variant=neon] .rx-trigger[data-state=active]{color:color-mix(in srgb,rgb(var(--rx-color)) 78%,rgb(var(--rx-dark)));-webkit-text-fill-color:currentColor}
		:root[data-theme='dark'] .rx-list[data-variant=neon] .rx-trigger[data-state=active]{color:color-mix(in srgb,rgb(var(--rx-color)) 78%,rgb(var(--rx-light)));-webkit-text-fill-color:currentColor}
		@media(prefers-reduced-motion:reduce){.rx-trigger{transition:none}}
	}
</style>
