<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { RxColor } from '$lib/registry/lib/color';
	export interface ScrollbarProps {
		orientation?: 'vertical' | 'horizontal' | 'both'; ariaLabel?: string; color?: RxColor;
		variant?: 'default' | 'dots' | 'glow' | 'gradient' | 'minimal' | 'rounded';
		size?: 'sm' | 'default' | 'lg'; mode?: 'embedded' | 'bare' | 'page'; hideDelay?: number;
		autoHide?: boolean; smoothness?: number; smooth?: boolean; ghost?: boolean; ghostGradient?: boolean; overscroll?: boolean;
		intensity?: number; color2?: RxColor; showTrack?: boolean; maxHeight?: number; children?: Snippet;
	}
</script>

<script lang="ts">
	import { getColor, styleColor } from '$lib/registry/lib/color';
	let {orientation='vertical',ariaLabel='Scrollable content',color,variant='default',size='default',mode='embedded',hideDelay=900,autoHide=true,smoothness=.18,smooth=true,ghost=true,ghostGradient=true,overscroll=true,intensity=1.6,color2,showTrack=true,maxHeight,children}:ScrollbarProps=$props();
	type Axis='vertical'|'horizontal';
	type AxisState={axis:Axis;track:HTMLElement;thumb:HTMLElement;ghost:HTMLElement|null;target:number;position:number;ghostPosition:number;thumbLength:number;trackLength:number;overscroll:number;velocity:number;dragging:boolean;dragStart:number;scrollStart:number};

	function scrollbarPhysics(root:HTMLElement){
		const viewport=root.querySelector<HTMLElement>('[data-slot="scroll-area-viewport"]');if(!viewport)return;const vp=viewport;
		const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
		const pageStyle=mode==='page'?document.createElement('style'):null;if(pageStyle){pageStyle.dataset.rxScrollbarPage='true';pageStyle.textContent='html{scrollbar-width:none}html::-webkit-scrollbar{display:none;width:0;height:0}';document.head.appendChild(pageStyle)}
		const scrollElement=()=>mode==='page'?((document.scrollingElement as HTMLElement|null)??document.documentElement):vp;
		const states:AxisState[]=[];const previousScroll=new Map<Axis,number>();let frame=0,hideTimer=0,hovering=false;
		for(const track of root.querySelectorAll<HTMLElement>('[data-rx-scroll-track]')){const axis=track.dataset.rxScrollTrack as Axis,thumb=track.querySelector<HTMLElement>('[data-rx-scroll-thumb]');if(!thumb)continue;states.push({axis,track,thumb,ghost:track.querySelector('[data-rx-scroll-ghost]'),target:0,position:0,ghostPosition:0,thumbLength:0,trackLength:0,overscroll:0,velocity:0,dragging:false,dragStart:0,scrollStart:0})}
		function show(){if(hideTimer)clearTimeout(hideTimer);root.dataset.scrollVisible='true';for(const s of states)s.track.dataset.hidden='false';if(autoHide&&!hovering&&!states.some(s=>s.dragging))hideTimer=window.setTimeout(()=>{root.dataset.scrollVisible='false';for(const s of states)s.track.dataset.hidden='true'},Math.max(0,hideDelay))}
		function measure(){const scroller=scrollElement();for(const s of states){const v=s.axis==='vertical',view=mode==='page'?(v?innerHeight:innerWidth):(v?vp.clientHeight:vp.clientWidth),scroll=v?scroller.scrollHeight:scroller.scrollWidth,pos=v?scroller.scrollTop:scroller.scrollLeft;s.trackLength=v?s.track.clientHeight:s.track.clientWidth;const ratio=scroll?view/scroll:1;s.thumbLength=Math.min(Math.max(28,s.trackLength*ratio),s.trackLength*.52);const scrollRange=Math.max(0,scroll-view),thumbRange=Math.max(0,s.trackLength-s.thumbLength-6);s.target=scrollRange?(pos/scrollRange)*thumbRange:0;s.track.dataset.scrollable=scrollRange>1?'true':'false';s.thumb.style.setProperty('--rx-thumb-length',`${s.thumbLength}px`);s.ghost?.style.setProperty('--rx-thumb-length',`${s.thumbLength}px`);if(variant==='dots'){const dotSize=size==='sm'?4:size==='lg'?8:6,count=Math.max(3,Math.floor(s.thumbLength/(dotSize*1.6)));while(s.thumb.childElementCount<count){const dot=document.createElement('i');dot.style.setProperty('--rx-dot-delay',`${s.thumb.childElementCount*120}ms`);s.thumb.appendChild(dot)}while(s.thumb.childElementCount>count)s.thumb.lastElementChild?.remove()}}}
		function paint(){frame=0;let moving=false;for(const s of states){const rate=reduced?1:Math.max(.02,Math.min(1,smoothness));s.position+=(s.target-s.position)*rate;s.ghostPosition+=(s.position-s.ghostPosition)*(reduced?1:rate*.42);s.velocity=(s.velocity-s.overscroll*.13)*.84;s.overscroll=Math.max(-22,Math.min(22,s.overscroll+s.velocity));if(Math.abs(s.overscroll)<.04&&Math.abs(s.velocity)<.04){s.overscroll=0;s.velocity=0}const squash=1-Math.min(Math.abs(s.overscroll)/60,.35),origin=s.overscroll<-.2?'start':s.overscroll>.2?'end':'center';s.thumb.style.setProperty('--rx-scroll-position',`${s.position+s.overscroll}px`);s.thumb.style.setProperty('--rx-scroll-squash',String(squash));s.thumb.style.setProperty('--rx-scroll-origin',origin);s.ghost?.style.setProperty('--rx-scroll-position',`${s.ghostPosition+s.overscroll*.6}px`);s.ghost?.style.setProperty('--rx-scroll-squash',String(squash));s.ghost?.style.setProperty('--rx-scroll-origin',origin);moving||=Math.abs(s.target-s.position)>.08||Math.abs(s.position-s.ghostPosition)>.08||s.velocity!==0}if(moving)frame=requestAnimationFrame(paint)}
		function schedule(){measure();if(!frame)frame=requestAnimationFrame(paint)}
		function onScroll(){const scroller=scrollElement();if(overscroll){for(const s of states){const vertical=s.axis==='vertical',position=vertical?scroller.scrollTop:scroller.scrollLeft,prior=previousScroll.get(s.axis)??position,delta=position-prior,view=mode==='page'?(vertical?innerHeight:innerWidth):(vertical?vp.clientHeight:vp.clientWidth),maximum=(vertical?scroller.scrollHeight:scroller.scrollWidth)-view;if((position<=0&&delta<0)||(position>=maximum-.5&&delta>0))s.velocity+=(delta<0?-1:1)*Math.min(Math.abs(delta)/50,1)*6;previousScroll.set(s.axis,position)}}measure();show();if(!frame)frame=requestAnimationFrame(paint)}
		function onWheel(e:WheelEvent){if(!overscroll)return;const scroller=scrollElement();for(const s of states){const v=s.axis==='vertical',delta=v?e.deltaY:e.deltaX,pos=v?scroller.scrollTop:scroller.scrollLeft,max=(v?scroller.scrollHeight:scroller.scrollWidth)-(mode==='page'?(v?innerHeight:innerWidth):(v?vp.clientHeight:vp.clientWidth));if((pos<=0&&delta<0)||(pos>=max-.5&&delta>0))s.velocity+=(delta<0?-1:1)*Math.min(Math.abs(delta)/120,1)*4.5}show();if(!frame)frame=requestAnimationFrame(paint)}
		const point=(e:PointerEvent,a:Axis)=>a==='vertical'?e.clientY:e.clientX;
		function startDrag(s:AxisState,e:PointerEvent){const scroller=scrollElement();s.dragging=true;s.track.dataset.active='true';s.dragStart=point(e,s.axis);s.scrollStart=s.axis==='vertical'?scroller.scrollTop:scroller.scrollLeft;s.thumb.setPointerCapture?.(e.pointerId);show();e.preventDefault()}
		function drag(s:AxisState,e:PointerEvent){if(!s.dragging)return;const scroller=scrollElement(),v=s.axis==='vertical',view=mode==='page'?(v?innerHeight:innerWidth):(v?vp.clientHeight:vp.clientWidth),range=(v?scroller.scrollHeight:scroller.scrollWidth)-view,thumbRange=s.trackLength-s.thumbLength-6,next=s.scrollStart+(point(e,s.axis)-s.dragStart)/Math.max(1,thumbRange)*range;if(v)scroller.scrollTop=next;else scroller.scrollLeft=next}
		function endDrag(s:AxisState,e:PointerEvent){if(!s.dragging)return;s.dragging=false;s.track.dataset.active='false';s.thumb.releasePointerCapture?.(e.pointerId);show()}
		function trackPress(s:AxisState,e:PointerEvent){if(e.target===s.thumb||s.thumb.contains(e.target as Node))return;const scroller=scrollElement(),r=s.track.getBoundingClientRect(),local=point(e,s.axis)-(s.axis==='vertical'?r.top:r.left)-s.thumbLength/2,ratio=Math.max(0,Math.min(1,local/Math.max(1,s.trackLength-s.thumbLength))),v=s.axis==='vertical',view=mode==='page'?(v?innerHeight:innerWidth):(v?vp.clientHeight:vp.clientWidth),destination=ratio*((v?scroller.scrollHeight:scroller.scrollWidth)-view),behavior=reduced||!smooth?'auto':'smooth';scroller.scrollTo(v?{top:destination,behavior}:{left:destination,behavior})}
		const cleanups:Array<()=>void>=[];function listen(target:EventTarget,type:string,listener:EventListener,options?:AddEventListenerOptions){target.addEventListener(type,listener,options);cleanups.push(()=>target.removeEventListener(type,listener,options))}
		listen(mode==='page'?window:vp,'scroll',onScroll as EventListener,{passive:true});listen(mode==='page'?window:vp,'wheel',onWheel as EventListener,{passive:true});listen(root,'pointerenter',(()=>{hovering=true;show()}) as EventListener);listen(root,'pointerleave',(()=>{hovering=false;show()}) as EventListener);listen(window,'resize',schedule as EventListener,{passive:true});
		for(const s of states){listen(s.thumb,'pointerdown',((e:PointerEvent)=>startDrag(s,e)) as EventListener);listen(s.thumb,'pointermove',((e:PointerEvent)=>drag(s,e)) as EventListener);listen(s.thumb,'pointerup',((e:PointerEvent)=>endDrag(s,e)) as EventListener);listen(s.thumb,'pointercancel',((e:PointerEvent)=>endDrag(s,e)) as EventListener);listen(s.track,'pointerdown',((e:PointerEvent)=>trackPress(s,e)) as EventListener)}
		const observer=typeof ResizeObserver==='undefined'?null:new ResizeObserver(schedule);observer?.observe(mode==='page'?document.body:vp);measure();for(const s of states){s.position=s.target;s.ghostPosition=s.target}paint();show();
		return()=>{for(const cleanup of cleanups)cleanup();observer?.disconnect();if(frame)cancelAnimationFrame(frame);if(hideTimer)clearTimeout(hideTimer);pageStyle?.remove()}
	}
</script>

<div data-slot="scroll-area" class="rx-scrollbar rx-scrollbar--{variant} rx-scrollbar--{size} rx-scrollbar--{mode}" class:no-ghost-gradient={!ghostGradient} class:no-track={!showTrack} data-scroll-visible="true" style={`${styleColor(color)??'--rx-color:var(--rx-primary)'};--rx-scroll-intensity:${intensity};--rx-scroll-glow-blur:${5+(.4*intensity)*9}px;--rx-scroll-glow-spread:${3+(.4*intensity)*7}px;--rx-scroll-color-2:${getColor(color2)??'var(--rx-color)'};${maxHeight?`--rx-scroll-max:${maxHeight}px`:''}`} {@attach scrollbarPhysics}>
	<!-- svelte-ignore a11y_no_noninteractive_tabindex (keyboard users need a focusable native scrolling region) -->
	<div data-slot="scroll-area-viewport" class="rx-scrollbar__viewport" style:overflow-x={orientation==='horizontal'||orientation==='both'?'scroll':'hidden'} style:overflow-y={orientation==='vertical'||orientation==='both'?'scroll':'hidden'} role="region" tabindex="0" aria-label={ariaLabel}>{@render children?.()}</div>
	{#if orientation==='vertical'||orientation==='both'}<div class="rx-scrollbar__track rx-scrollbar__track--vertical" data-rx-scroll-track="vertical" data-hidden="false" data-scrollable="false">{#if ghost}<span class="rx-scrollbar__ghost" data-rx-scroll-ghost aria-hidden="true"></span>{/if}<span class="rx-scrollbar__thumb" data-rx-scroll-thumb aria-hidden="true"></span></div>{/if}
	{#if orientation==='horizontal'||orientation==='both'}<div class="rx-scrollbar__track rx-scrollbar__track--horizontal" data-rx-scroll-track="horizontal" data-hidden="false" data-scrollable="false">{#if ghost}<span class="rx-scrollbar__ghost" data-rx-scroll-ghost aria-hidden="true"></span>{/if}<span class="rx-scrollbar__thumb" data-rx-scroll-thumb aria-hidden="true"></span></div>{/if}
</div>

<style>
	.rx-scrollbar{position:relative;overflow:hidden;border-radius:var(--rx-radius);background:rgb(var(--rx-bg));border:1px solid rgb(var(--rx-text)/.08)}
	.rx-scrollbar--bare{height:auto!important;max-height:var(--rx-scroll-max,none);border:0;border-radius:0;background:transparent}.rx-scrollbar--page{position:fixed;inset:0;z-index:2147483600;width:auto!important;height:auto!important;border:0;border-radius:0;background:transparent;overflow:visible;pointer-events:none}
	.rx-scrollbar__viewport{width:100%;height:100%;scrollbar-width:none;-ms-overflow-style:none;overscroll-behavior:contain;outline:none}.rx-scrollbar__viewport::-webkit-scrollbar{display:none;width:0;height:0}.rx-scrollbar--bare .rx-scrollbar__viewport{height:auto;max-height:var(--rx-scroll-max,none)}.rx-scrollbar--page .rx-scrollbar__viewport{display:none}.rx-scrollbar__viewport:focus-visible{box-shadow:inset 0 0 0 3px rgb(var(--rx-color)/.26)}
	.rx-scrollbar__track{position:absolute;z-index:4;cursor:pointer;transition:opacity 320ms ease}.rx-scrollbar__track[data-scrollable=false]{display:none}.rx-scrollbar__track:global([data-hidden=true]){opacity:0}.rx-scrollbar__track--vertical{top:3px;right:3px;bottom:3px;width:16px}.rx-scrollbar__track--horizontal{left:3px;right:3px;bottom:3px;height:16px}.rx-scrollbar--page .rx-scrollbar__track--vertical{position:fixed;right:2px;pointer-events:auto}.rx-scrollbar--page .rx-scrollbar__track--horizontal{position:fixed;bottom:2px;pointer-events:auto}.rx-scrollbar--sm .rx-scrollbar__track--vertical{width:12px}.rx-scrollbar--sm .rx-scrollbar__track--horizontal{height:12px}.rx-scrollbar--lg .rx-scrollbar__track--vertical{width:20px}.rx-scrollbar--lg .rx-scrollbar__track--horizontal{height:20px}
	.rx-scrollbar--glow .rx-scrollbar__track--vertical,.rx-scrollbar--gradient .rx-scrollbar__track--vertical{width:14px}.rx-scrollbar--glow .rx-scrollbar__track--horizontal,.rx-scrollbar--gradient .rx-scrollbar__track--horizontal{height:14px}.rx-scrollbar--minimal .rx-scrollbar__track--vertical{top:2px;right:2px;bottom:2px;width:12px}.rx-scrollbar--minimal .rx-scrollbar__track--horizontal{left:2px;right:2px;bottom:2px;height:12px}.rx-scrollbar--rounded .rx-scrollbar__track--vertical{top:6px;right:5px;bottom:6px;width:18px}.rx-scrollbar--rounded .rx-scrollbar__track--horizontal{left:6px;right:6px;bottom:5px;height:18px}
	.rx-scrollbar{--rx-thumb-width:4px;--rx-thumb-grow:6px}.rx-scrollbar--sm{--rx-thumb-width:3px;--rx-thumb-grow:5px}.rx-scrollbar--lg{--rx-thumb-width:6px;--rx-thumb-grow:8px}.rx-scrollbar__thumb,.rx-scrollbar__ghost{position:absolute;border-radius:999px;will-change:transform,width,height,scale,filter,opacity;transition:width 220ms cubic-bezier(.34,1.56,.64,1),height 220ms cubic-bezier(.34,1.56,.64,1),opacity 360ms ease,scale 420ms cubic-bezier(.34,1.56,.64,1),filter 360ms ease}.rx-scrollbar__track--vertical :is(.rx-scrollbar__thumb,.rx-scrollbar__ghost){top:3px;right:0;width:var(--rx-thumb-width);height:var(--rx-thumb-length);transform:translate3d(0,var(--rx-scroll-position,0),0) scaleY(var(--rx-scroll-squash,1));transform-origin:center var(--rx-scroll-origin,center)}.rx-scrollbar__track--horizontal :is(.rx-scrollbar__thumb,.rx-scrollbar__ghost){right:3px;bottom:0;width:var(--rx-thumb-length);height:var(--rx-thumb-width);transform:translate3d(var(--rx-scroll-position,0),0,0) scaleX(var(--rx-scroll-squash,1));transform-origin:var(--rx-scroll-origin,center) center}.rx-scrollbar__track:is(:hover,:global([data-active=true])) :is(.rx-scrollbar__thumb,.rx-scrollbar__ghost){--rx-thumb-width:var(--rx-thumb-grow)}
	.rx-scrollbar__thumb{cursor:grab;background:rgb(var(--rx-color)/.2);backdrop-filter:blur(10px)}.rx-scrollbar__thumb:active{cursor:grabbing}.rx-scrollbar__ghost{pointer-events:none;background:linear-gradient(to bottom,rgb(var(--rx-color)/0),rgb(var(--rx-color)/.1) 50%,rgb(var(--rx-color)/0))}.rx-scrollbar__track--horizontal .rx-scrollbar__ghost{background:linear-gradient(to right,rgb(var(--rx-color)/0),rgb(var(--rx-color)/.1) 50%,rgb(var(--rx-color)/0))}.rx-scrollbar.no-ghost-gradient .rx-scrollbar__ghost{background:rgb(var(--rx-color)/.1)}.rx-scrollbar__track:is(:hover,:global([data-active=true])) .rx-scrollbar__thumb{background:rgb(var(--rx-color))}.rx-scrollbar__track:global([data-hidden=true]) :is(.rx-scrollbar__thumb,.rx-scrollbar__ghost){opacity:0;scale:.35;filter:blur(5px)}
	.rx-scrollbar--minimal{--rx-thumb-width:3px;--rx-thumb-grow:4px}.rx-scrollbar--minimal.rx-scrollbar--sm{--rx-thumb-width:2px;--rx-thumb-grow:3px}.rx-scrollbar--minimal.rx-scrollbar--lg{--rx-thumb-width:4px;--rx-thumb-grow:5px}.rx-scrollbar--minimal .rx-scrollbar__thumb{background:rgb(var(--rx-text)/.35)}.rx-scrollbar--minimal .rx-scrollbar__track:is(:hover,:global([data-active=true])) .rx-scrollbar__thumb{background:rgb(var(--rx-text)/.9)}.rx-scrollbar--glow{--rx-thumb-width:6px;--rx-thumb-grow:8px}.rx-scrollbar--glow.rx-scrollbar--sm{--rx-thumb-width:4px;--rx-thumb-grow:6px}.rx-scrollbar--glow.rx-scrollbar--lg{--rx-thumb-width:8px;--rx-thumb-grow:10px}.rx-scrollbar--glow .rx-scrollbar__thumb{background:rgb(var(--rx-color));box-shadow:0 0 var(--rx-scroll-glow-blur) var(--rx-scroll-glow-spread) rgb(var(--rx-color))}.rx-scrollbar--glow .rx-scrollbar__thumb::after{content:'';position:absolute;inset:0;border-radius:inherit;background:inherit;box-shadow:inherit;filter:brightness(1.35);opacity:0;animation:rx-scroll-glow 2.4s ease-in-out infinite}.rx-scrollbar--gradient{--rx-thumb-width:7px;--rx-thumb-grow:9px}.rx-scrollbar--gradient.rx-scrollbar--sm{--rx-thumb-width:5px;--rx-thumb-grow:7px}.rx-scrollbar--gradient.rx-scrollbar--lg{--rx-thumb-width:9px;--rx-thumb-grow:11px}.rx-scrollbar--gradient .rx-scrollbar__thumb{background:linear-gradient(to bottom,rgb(var(--rx-color)),rgb(var(--rx-scroll-color-2)),rgb(var(--rx-color)));background-size:100% 300%;animation:rx-scroll-flow 3.5s linear infinite}.rx-scrollbar--gradient .rx-scrollbar__track--horizontal .rx-scrollbar__thumb{background:linear-gradient(to right,rgb(var(--rx-color)),rgb(var(--rx-scroll-color-2)),rgb(var(--rx-color)));background-size:300% 100%}
	.rx-scrollbar--rounded{--rx-thumb-width:9px;--rx-thumb-grow:12px}.rx-scrollbar--rounded.rx-scrollbar--sm{--rx-thumb-width:6px;--rx-thumb-grow:9px}.rx-scrollbar--rounded.rx-scrollbar--lg{--rx-thumb-width:12px;--rx-thumb-grow:15px}.rx-scrollbar--rounded .rx-scrollbar__track{border:1px solid rgb(var(--rx-text)/.08);border-radius:999px;background:rgb(var(--rx-color)/.06);padding:4px}.rx-scrollbar--rounded.no-track .rx-scrollbar__track{border-color:transparent;background:transparent}.rx-scrollbar--rounded .rx-scrollbar__thumb{right:4px;background:rgb(var(--rx-color)/.55)}.rx-scrollbar--dots .rx-scrollbar__thumb{right:0;width:100%;display:flex;align-items:center;justify-content:space-around;background:transparent}.rx-scrollbar--dots .rx-scrollbar__track--vertical .rx-scrollbar__thumb{flex-direction:column}.rx-scrollbar--dots .rx-scrollbar__thumb :global(i){display:block;width:var(--rx-dot-size,6px);height:var(--rx-dot-size,6px);border-radius:999px;background:rgb(var(--rx-color)/.5);animation:rx-scroll-wave 1.6s ease-in-out var(--rx-dot-delay) infinite;transition:width 220ms cubic-bezier(.34,1.56,.64,1),height 220ms cubic-bezier(.34,1.56,.64,1),background-color 220ms}.rx-scrollbar--dots.rx-scrollbar--sm{--rx-dot-size:4px}.rx-scrollbar--dots.rx-scrollbar--lg{--rx-dot-size:8px}.rx-scrollbar--dots .rx-scrollbar__track:is(:hover,:global([data-active=true])) .rx-scrollbar__thumb :global(i){width:calc(var(--rx-dot-size) + 2px);height:calc(var(--rx-dot-size) + 2px);background:rgb(var(--rx-color)/.95);animation-play-state:paused}
	@keyframes rx-scroll-glow{0%,100%{opacity:0}50%{opacity:1}}@keyframes rx-scroll-flow{to{background-position:0 300%}}@keyframes rx-scroll-wave{0%,100%{opacity:.6;transform:scale(.85)}50%{opacity:1;transform:scale(1.1)}}
	@media(prefers-reduced-motion:reduce){.rx-scrollbar__track,.rx-scrollbar__thumb,.rx-scrollbar__ghost{transition:none!important}.rx-scrollbar__thumb,.rx-scrollbar__thumb::after,.rx-scrollbar__thumb :global(i){animation:none!important}}@media(forced-colors:active){.rx-scrollbar__thumb{background:CanvasText;forced-color-adjust:auto}.rx-scrollbar__ghost{display:none}}
</style>
