<script lang="ts" module>import type { RxColor } from '$lib/registry/lib/color'; export interface PaginationProps { page?:number;count:number;perPage?:number;siblingCount?:number;color?:RxColor;variant?:'default'|'compact'|'dots'|'gooey'|'ink'|'segments';showEdges?:boolean;showControls?:boolean;showGoto?:boolean;disabled?:boolean;onPageChange?:(page:number)=>void }</script>
<script lang="ts">import { styleColor } from '$lib/registry/lib/color';import{pageCount,clampPage,paginationRange}from'./range';let{page=$bindable(1),count,perPage=10,siblingCount=1,color,variant='default',showEdges=true,showControls=true,showGoto=false,disabled=false,onPageChange}:PaginationProps=$props();const pages=$derived(pageCount(count,perPage));const range=$derived(paginationRange(page,pages,siblingCount));let gotoValue=$state('');let emitted=$state(page);let direction=$state(1);function setPage(next:number){const safe=clampPage(next,pages);direction=safe>=page?1:-1;page=safe;if(safe!==emitted){emitted=safe;onPageChange?.(safe)}}$effect(()=>{const safe=clampPage(page,pages);if(page!==safe)setPage(safe)});function commit(){if(gotoValue.trim()!=='')setPage(Number.parseInt(gotoValue,10));gotoValue=String(page)}function fidelity(node:HTMLElement){let frame=0;const measure=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const active=node.querySelector<HTMLElement>('button[aria-current=page]'),ind=node.querySelector<HTMLElement>('.rx-page-indicator');if(!active||!ind)return;node.style.setProperty('--rx-px',`${active.offsetLeft}px`);node.style.setProperty('--rx-py',`${active.offsetTop}px`);node.style.setProperty('--rx-pw',`${active.offsetWidth}px`);node.style.setProperty('--rx-ph',`${active.offsetHeight}px`);ind.classList.remove('is-pop','is-wobble');void ind.offsetWidth;ind.classList.add(variant==='gooey'?'is-wobble':'is-pop','is-ready')})};const down=(e:PointerEvent)=>{const button=(e.target as Element).closest<HTMLButtonElement>('button');if(!button||button.disabled)return;const rect=button.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,r=Math.max(Math.hypot(x,y),Math.hypot(rect.width-x,y),Math.hypot(x,rect.height-y));const ripple=document.createElement('span');ripple.className='rx-page-ripple';ripple.style.cssText=`left:${x}px;top:${y}px;width:${2*r}px;height:${2*r}px`;button.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove(),{once:true})};const ro=new ResizeObserver(measure),mo=new MutationObserver(measure);ro.observe(node);mo.observe(node,{subtree:true,attributes:true,attributeFilter:['aria-current']});node.addEventListener('pointerdown',down);measure();return()=>{ro.disconnect();mo.disconnect();node.removeEventListener('pointerdown',down);cancelAnimationFrame(frame)}};</script>
<nav class="rx-pagination" data-variant={variant} data-direction={direction} aria-label="Pagination" style={styleColor(color)??'--rx-color:var(--rx-primary)'} {@attach fidelity}><span class="rx-page-indicator" aria-hidden="true"></span>
	{#if showControls}<button aria-label="Previous page" disabled={disabled||page<=1} onclick={()=>setPage(page-1)}>‹</button>{/if}
	{#if showEdges&&range[0]!==1}<button disabled={disabled} onclick={()=>setPage(1)}>1</button><span>…</span>{/if}
	{#each range as token}{#if token==='ellipsis'}<span class="rx-ellipsis">…</span>{:else}<button class:active={token===page} data-state={token<page?'complete':token===page?'current':'pending'} aria-current={token===page?'page':undefined} aria-label={`Page ${token}`} disabled={disabled} onclick={()=>setPage(token)}><span class="rx-page-glyph" aria-hidden={variant==='dots'}>{variant==='dots'?'•':token}</span></button>{/if}{/each}
	{#if showEdges&&range[range.length-1]!==pages}<span>…</span><button disabled={disabled} onclick={()=>setPage(pages)}>{pages}</button>{/if}
	{#if showControls}<button aria-label="Next page" disabled={disabled||page>=pages} onclick={()=>setPage(page+1)}>›</button>{/if}
	{#if showGoto}<label class="rx-goto">Go to page<input aria-label="Go to page" inputmode="numeric" bind:value={gotoValue} onblur={commit} onkeydown={(e)=>e.key==='Enter'&&commit()} /></label>{/if}
</nav>
<style>.rx-pagination{position:relative;display:flex;align-items:center;gap:5px;flex-wrap:wrap}.rx-pagination button{position:relative;z-index:1;overflow:hidden;display:grid;place-items:center;min-width:36px;height:36px;border:0;border-radius:9px;color:rgb(var(--rx-text-secondary));background:rgb(var(--rx-text)/.055);font:inherit;font-weight:600;cursor:pointer;transition:transform 320ms cubic-bezier(.34,1.56,.64,1),color 200ms ease,background 200ms ease}.rx-pagination button:active:not(:disabled){transform:scale(.92)}.rx-pagination button:hover:not(:disabled){color:rgb(var(--rx-color));background:rgb(var(--rx-color)/.12)}.rx-pagination button.active{color:var(--rx-color-foreground, rgb(var(--rx-dark)));background:transparent}.rx-page-indicator{position:absolute;z-index:0;left:0;top:0;width:var(--rx-pw,0);height:var(--rx-ph,36px);border-radius:9px;background:rgb(var(--rx-color));box-shadow:0 5px 14px rgb(var(--rx-color)/.23);opacity:0;transform:translate3d(var(--rx-px,0),var(--rx-py,0),0);transition:transform 420ms cubic-bezier(.34,1.4,.64,1),width 420ms cubic-bezier(.34,1.4,.64,1),height 420ms cubic-bezier(.34,1.4,.64,1),opacity 200ms ease}:global(.rx-page-indicator.is-ready){opacity:1}:global(.rx-page-indicator.is-pop){animation:rx-page-pop 460ms cubic-bezier(.34,1.4,.64,1)}:global(.rx-page-ripple){position:absolute;border-radius:50%;translate:-50% -50%;background:radial-gradient(circle,rgb(var(--rx-text)/.22),rgb(var(--rx-text)/.12) 30%,rgb(var(--rx-text)/.04) 55%,transparent 72%);pointer-events:none;animation:rx-page-ripple 720ms cubic-bezier(.22,1,.36,1) forwards}.rx-pagination button:focus-visible,.rx-goto input:focus-visible{outline:2px solid rgb(var(--rx-color)/.75);outline-offset:2px}.rx-pagination button:disabled{opacity:.4;cursor:not-allowed}
.rx-pagination[data-variant=compact]{gap:0;overflow:hidden;border:1px solid rgb(var(--rx-border));border-radius:10px}.rx-pagination[data-variant=compact] button{border-radius:0;background:transparent}.rx-pagination[data-variant=compact] .rx-page-indicator{border-radius:0}.rx-pagination[data-variant=compact] .active .rx-page-glyph{animation:rx-page-roll-next 420ms cubic-bezier(.34,1.4,.64,1)}.rx-pagination[data-variant=compact][data-direction="-1"] .active .rx-page-glyph{animation-name:rx-page-roll-prev}
.rx-pagination[data-variant=segments]{gap:3px}.rx-pagination[data-variant=segments] .rx-page-indicator{display:none}.rx-pagination[data-variant=segments] button{min-width:42px;height:30px;border-radius:4px;background:rgb(var(--rx-border));overflow:hidden}.rx-pagination[data-variant=segments] button:after{content:"";position:absolute;inset:0;background:rgb(var(--rx-color));transform:scaleX(0);transform-origin:left;transition:transform 520ms cubic-bezier(.22,1,.36,1)}.rx-pagination[data-variant=segments] button[data-state=complete]:after,.rx-pagination[data-variant=segments] button[data-state=current]:after{transform:scaleX(1)}.rx-pagination[data-variant=segments] .rx-page-glyph{position:relative;z-index:1}
.rx-pagination[data-variant=gooey] .rx-page-indicator{border-radius:999px;transition-timing-function:cubic-bezier(.5,1.5,.5,1)}:global(.rx-page-indicator.is-wobble){animation:rx-page-wobble 460ms cubic-bezier(.5,1.5,.5,1)}.rx-pagination[data-variant=ink]{padding:0 14px;mask-image:linear-gradient(90deg,transparent,#000 14px,#000 calc(100% - 14px),transparent)}.rx-pagination[data-variant=ink] button{background:transparent}.rx-pagination[data-variant=ink] button.active{color:rgb(var(--rx-color));-webkit-text-fill-color:currentColor}.rx-pagination[data-variant=ink] .rx-page-indicator{top:auto;bottom:0;height:2px!important;border-radius:2px;box-shadow:0 0 8px rgb(var(--rx-color)/.45)}
.rx-pagination[data-variant=dots] button{min-width:22px;width:22px;background:transparent;font-size:22px}.rx-pagination[data-variant=dots] .rx-page-indicator{display:none}.rx-pagination[data-variant=dots] button.active{color:rgb(var(--rx-color));transform:scale(1.35);text-shadow:0 0 10px rgb(var(--rx-color)/.65)}.rx-goto{display:inline-flex;align-items:center;gap:6px;margin-left:7px;font-size:12px;color:rgb(var(--rx-text-secondary))}.rx-goto input{width:56px;border:1px solid rgb(var(--rx-border));border-radius:7px;padding:7px;background:rgb(var(--rx-surface));color:rgb(var(--rx-text))}
@keyframes rx-page-pop{38%{scale:1.099}}@keyframes rx-page-ripple{from{transform:scale(0);opacity:.8}to{transform:scale(1);opacity:0}}@keyframes rx-page-roll-next{from{opacity:0;transform:translateY(100%);filter:blur(7px)}to{opacity:1;transform:none;filter:blur(0)}}@keyframes rx-page-roll-prev{from{opacity:0;transform:translateY(-100%);filter:blur(7px)}to{opacity:1;transform:none;filter:blur(0)}}@keyframes rx-page-wobble{22%{scale:1.16 .88}55%{scale:.92 1.08}100%{scale:1}}
@media(prefers-reduced-motion:reduce){.rx-pagination button,.rx-page-indicator{transition:color 160ms ease!important;animation:none!important}:global(.rx-page-ripple){display:none}.rx-pagination[data-variant=dots] button.active{transform:none}.rx-page-glyph{animation:none!important}}
</style>
