<script lang="ts" module>import type { RxColor } from '$lib/registry/lib/color'; export interface PaginationProps { page?:number;count:number;perPage?:number;siblingCount?:number;color?:RxColor;variant?:'default'|'compact'|'dots'|'gooey'|'ink'|'segments';showEdges?:boolean;showControls?:boolean;showGoto?:boolean;disabled?:boolean;onPageChange?:(page:number)=>void }</script>
<script lang="ts">import { styleColor } from '$lib/registry/lib/color';import{pageCount,clampPage,paginationRange}from'./range';let{page=$bindable(1),count,perPage=10,siblingCount=1,color,variant='default',showEdges=true,showControls=true,showGoto=false,disabled=false,onPageChange}:PaginationProps=$props();const pages=$derived(pageCount(count,perPage));const range=$derived(paginationRange(page,pages,siblingCount));let gotoValue=$state('');let emitted=$state(page);function setPage(next:number){const safe=clampPage(next,pages);page=safe;if(safe!==emitted){emitted=safe;onPageChange?.(safe)}}$effect(()=>{const safe=clampPage(page,pages);if(page!==safe)setPage(safe)});function commit(){if(gotoValue.trim()!=='')setPage(Number.parseInt(gotoValue,10));gotoValue=String(page)}</script>
<nav class="rx-pagination" data-variant={variant} aria-label="Pagination" style={styleColor(color)??'--rx-color:var(--rx-primary)'}>
	{#if showControls}<button aria-label="Previous page" disabled={disabled||page<=1} onclick={()=>setPage(page-1)}>‹</button>{/if}
	{#if showEdges&&range[0]!==1}<button disabled={disabled} onclick={()=>setPage(1)}>1</button><span>…</span>{/if}
	{#each range as token}{#if token==='ellipsis'}<span class="rx-ellipsis">…</span>{:else}<button class:active={token===page} aria-current={token===page?'page':undefined} aria-label={`Page ${token}`} disabled={disabled} onclick={()=>setPage(token)}>{variant==='dots'?'•':token}</button>{/if}{/each}
	{#if showEdges&&range[range.length-1]!==pages}<span>…</span><button disabled={disabled} onclick={()=>setPage(pages)}>{pages}</button>{/if}
	{#if showControls}<button aria-label="Next page" disabled={disabled||page>=pages} onclick={()=>setPage(page+1)}>›</button>{/if}
	{#if showGoto}<label class="rx-goto">Go to page<input aria-label="Go to page" inputmode="numeric" bind:value={gotoValue} onblur={commit} onkeydown={(e)=>e.key==='Enter'&&commit()} /></label>{/if}
</nav>
<style>.rx-pagination{display:flex;align-items:center;gap:.35rem;flex-wrap:wrap}.rx-pagination button{min-width:2.25rem;height:2.25rem;border:0;border-radius:calc(var(--rx-radius)*.75);color:rgb(var(--rx-text));background:rgb(var(--rx-text)/.06);font:inherit;font-weight:650;cursor:pointer;transition:transform 180ms var(--rx-ease),background 180ms var(--rx-ease),box-shadow 180ms var(--rx-ease)}.rx-pagination button:hover:not(:disabled){background:rgb(var(--rx-color)/.14);color:rgb(var(--rx-color))}.rx-pagination button.active{color:rgb(var(--rx-light));background:rgb(var(--rx-color));box-shadow:0 6px 16px rgb(var(--rx-color)/.26)}.rx-pagination button:focus-visible,.rx-goto input:focus-visible{outline:3px solid rgb(var(--rx-color)/.28);outline-offset:2px}.rx-pagination button:disabled{opacity:.4;cursor:not-allowed}.rx-pagination[data-variant=compact]{gap:0}.rx-pagination[data-variant=compact] button{border-radius:0}.rx-pagination[data-variant=segments] button{border-radius:.2rem}.rx-pagination[data-variant=gooey] button.active{border-radius:45% 55% 48% 52%}.rx-pagination[data-variant=ink] button.active{box-shadow:0 8px 0 -5px rgb(var(--rx-color)/.35)}.rx-pagination[data-variant=dots] button{min-width:1.35rem;background:transparent;font-size:1.5rem}.rx-pagination[data-variant=dots] button.active{color:rgb(var(--rx-color));box-shadow:none;transform:scale(1.35)}.rx-goto{display:inline-flex;align-items:center;gap:.4rem;margin-left:.45rem;font-size:.8rem;color:rgb(var(--rx-text)/.65)}.rx-goto input{width:3.5rem;border:1px solid rgb(var(--rx-text)/.16);border-radius:.4rem;padding:.42rem;background:rgb(var(--rx-surface));color:rgb(var(--rx-text))}@media(prefers-reduced-motion:reduce){.rx-pagination button{transition:none}.rx-pagination[data-variant=dots] button.active{transform:none}}</style>
