<script lang="ts" module>
	import type {Snippet}from'svelte';import type{HTMLAttributes}from'svelte/elements';import type{RxColor}from'$lib/registry/lib/color';
	export type SeparatorOrientation='horizontal'|'vertical';export type SeparatorVariant='base'|'solid'|'dashed'|'dotted'|'flow'|'glow'|'gradient'|'icon'|'zigzag';
	export interface SeparatorProps extends HTMLAttributes<HTMLDivElement>{orientation?:SeparatorOrientation;variant?:SeparatorVariant;color?:RxColor;tone?:'default'|'danger'|'warn'|'success';labelPosition?:'start'|'center'|'end';speed?:number;dash?:number;zigzagSize?:number;children?:Snippet;icon?:Snippet}
</script>
<script lang="ts">
	import{styleColor}from'$lib/registry/lib/color';import{cn}from'$lib/utils.js';
	let{orientation='horizontal',variant='base',color,tone='default',labelPosition='center',speed,dash=8,zigzagSize=8,children,icon,class:className,style,...rest}:SeparatorProps=$props();
	const colorStyle=$derived([color?styleColor(color):'--rx-color:var(--rx-gray)',`--rx-sep-speed:${speed??(variant==='glow'?2.8:variant==='gradient'?3:variant==='zigzag'?3.5:variant==='icon'?6:1.2)}s`,`--rx-sep-dash:${dash}px`,`--rx-sep-zig:${zigzagSize}px`,typeof style==='string'?style:undefined].filter(Boolean).join(';'));
</script>
<div {...rest} class={cn('rx-separator',`rx-separator--${orientation}`,`rx-separator--${variant}`,children&&'has-label',`rx-separator--label-${labelPosition}`,className)} data-tone={tone} style={colorStyle} role={children?'none':'separator'} aria-orientation={children?undefined:orientation}>
	<span class="rx-separator__line rx-separator__line--left" aria-hidden="true"></span>
	{#if variant==='icon'}<span class="rx-separator__node"><span class="rx-separator__mark" aria-hidden="true">{#if icon}{@render icon()}{:else}✦{/if}</span>{#if children}<span class="rx-separator__label">{@render children()}</span>{/if}</span>{:else if children}<span class="rx-separator__label">{@render children()}</span>{/if}
	<span class="rx-separator__line rx-separator__line--right" aria-hidden="true"></span>
</div>
<style>
	.rx-separator{--rx-sep-gap:14px;display:flex;align-items:center;width:100%;color:rgb(var(--rx-color));flex-shrink:0}.rx-separator[data-tone=danger]{--rx-color:var(--rx-danger)}.rx-separator[data-tone=warn]{--rx-color:var(--rx-warning)}.rx-separator[data-tone=success]{--rx-color:var(--rx-success)}.rx-separator__line{flex:1;height:1px;border:0;background:currentColor}.rx-separator:not(.has-label):not(.rx-separator--icon) .rx-separator__line--right{display:none}.rx-separator__label{flex:none;padding:0 var(--rx-sep-gap);color:rgb(var(--rx-text-muted));font:inherit;font-size:13px;line-height:1;white-space:nowrap;user-select:none}.has-label .rx-separator__line--left{mask-image:linear-gradient(to right,transparent,#000 92%)}.has-label .rx-separator__line--right{mask-image:linear-gradient(to left,transparent,#000 92%)}.rx-separator--label-start.has-label .rx-separator__line--left{flex:0 0 var(--rx-sep-gap)}.rx-separator--label-end.has-label .rx-separator__line--right{flex:0 0 var(--rx-sep-gap)}.rx-separator--base:not(.has-label) .rx-separator__line,.rx-separator--solid:not(.has-label) .rx-separator__line{background:linear-gradient(90deg,transparent,currentColor,transparent)}.rx-separator--dashed .rx-separator__line{background:repeating-linear-gradient(90deg,currentColor 0 6px,transparent 6px 12px)}.rx-separator--dotted .rx-separator__line{background:repeating-linear-gradient(90deg,currentColor 0 1px,transparent 1px 4px)}
	.rx-separator--flow .rx-separator__line{background:repeating-linear-gradient(90deg,currentColor 0 var(--rx-sep-dash),transparent var(--rx-sep-dash) calc(var(--rx-sep-dash)*2));background-size:calc(var(--rx-sep-dash)*2) 100%;animation:rx-sep-flow var(--rx-sep-speed) linear infinite}.rx-separator--gradient .rx-separator__line{background:linear-gradient(90deg,rgb(var(--rx-border)),currentColor,rgb(var(--rx-border)));background-size:220% 100%;animation:rx-sep-gradient var(--rx-sep-speed) linear infinite}.rx-separator--glow .rx-separator__line{background:linear-gradient(90deg,transparent,currentColor,transparent);box-shadow:0 0 10px 1px currentColor;animation:rx-sep-glow var(--rx-sep-speed) ease-in-out infinite}.rx-separator__node{display:inline-flex;align-items:center;gap:10px;padding:0 10px;color:currentColor}.rx-separator__node .rx-separator__label{padding:0}.rx-separator__mark{display:block;animation:rx-sep-spin var(--rx-sep-speed,6s) linear infinite}.rx-separator--icon{--rx-sep-speed:6s}.rx-separator--icon .rx-separator__line{mask-image:linear-gradient(to right,transparent,#000 92%)}.rx-separator--icon .rx-separator__line--right{mask-image:linear-gradient(to left,transparent,#000 92%)}.rx-separator--zigzag .rx-separator__line{height:calc(var(--rx-sep-zig)*2);background:linear-gradient(135deg,currentColor 1px,transparent 1px 50%),linear-gradient(45deg,currentColor 1px,transparent 1px 50%);background-size:var(--rx-sep-zig) var(--rx-sep-zig);background-repeat:repeat-x;background-position:0 50%;animation:rx-sep-zig var(--rx-sep-speed) linear infinite}
	.rx-separator--vertical{display:inline-flex;flex-direction:column;align-items:center;align-self:stretch;width:auto;height:100%;min-height:28px}.rx-separator--vertical.has-label{min-height:96px}.rx-separator--vertical .rx-separator__line{width:1px;height:auto;align-self:center}.rx-separator--vertical .rx-separator__label{padding:var(--rx-sep-gap) 0}.rx-separator--vertical.has-label .rx-separator__line--left{mask-image:linear-gradient(to bottom,transparent,#000 92%)}.rx-separator--vertical.has-label .rx-separator__line--right{mask-image:linear-gradient(to top,transparent,#000 92%)}.rx-separator--vertical.rx-separator--label-start.has-label .rx-separator__line--left{flex:0 0 var(--rx-sep-gap)}.rx-separator--vertical.rx-separator--label-end.has-label .rx-separator__line--right{flex:0 0 var(--rx-sep-gap)}.rx-separator--vertical:is(.rx-separator--base,.rx-separator--solid):not(.has-label) .rx-separator__line{background:linear-gradient(180deg,transparent,currentColor,transparent)}.rx-separator--vertical.rx-separator--dashed .rx-separator__line{background:repeating-linear-gradient(180deg,currentColor 0 6px,transparent 6px 12px)}.rx-separator--vertical.rx-separator--dotted .rx-separator__line{background:repeating-linear-gradient(180deg,currentColor 0 1px,transparent 1px 4px)}.rx-separator--vertical.rx-separator--flow .rx-separator__line{background:repeating-linear-gradient(180deg,currentColor 0 var(--rx-sep-dash),transparent var(--rx-sep-dash) calc(var(--rx-sep-dash)*2));background-size:100% calc(var(--rx-sep-dash)*2);animation-name:rx-sep-flow-v}.rx-separator--vertical.rx-separator--gradient .rx-separator__line{background:linear-gradient(180deg,rgb(var(--rx-border)),currentColor,rgb(var(--rx-border)));background-size:100% 220%;animation-name:rx-sep-gradient-v}.rx-separator--vertical.rx-separator--glow .rx-separator__line{background:linear-gradient(180deg,transparent,currentColor,transparent)}.rx-separator--vertical .rx-separator__node{flex-direction:column;padding:10px 0}.rx-separator--vertical.rx-separator--zigzag .rx-separator__line{width:calc(var(--rx-sep-zig)*2);height:auto;background:linear-gradient(225deg,currentColor 1px,transparent 1px 50%),linear-gradient(315deg,currentColor 1px,transparent 1px 50%);background-size:var(--rx-sep-zig) var(--rx-sep-zig);background-repeat:repeat-y;background-position:50% 0;animation-name:rx-sep-zig-v}
	@keyframes rx-sep-flow{to{background-position:calc(var(--rx-sep-dash)*2) 0}}@keyframes rx-sep-flow-v{to{background-position:0 calc(var(--rx-sep-dash)*2)}}@keyframes rx-sep-gradient{from{background-position:220% 0}to{background-position:-220% 0}}@keyframes rx-sep-gradient-v{from{background-position:0 220%}to{background-position:0 -220%}}@keyframes rx-sep-glow{0%,100%{opacity:.35}50%{opacity:1}}@keyframes rx-sep-spin{to{rotate:1turn}}@keyframes rx-sep-zig{to{background-position:var(--rx-sep-zig) 50%}}@keyframes rx-sep-zig-v{to{background-position:50% var(--rx-sep-zig)}}@media(prefers-reduced-motion:reduce){.rx-separator__line,.rx-separator__mark{animation:none!important}.rx-separator--glow .rx-separator__line{opacity:1;box-shadow:0 0 6px currentColor}}
	.rx-separator__label{color:rgb(var(--rx-text-secondary))}
</style>
