<script lang="ts">
	import DemoSection from '../DemoSection.svelte';
	import { Card } from '$lib/registry/ui/card';
	const variants = ['default', 'asset', 'glow', 'gradient-border', 'lift', 'slider', 'spotlight', 'tilt-3d', 'shadow', 'border', 'flat', 'reveal', 'zoom'] as const;
	const mediaUri = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 300"%3E%3Cdefs%3E%3ClinearGradient id="g" x2="1" y2="1"%3E%3Cstop stop-color="%23195bff"/%3E%3Cstop offset="1" stop-color="%2346c93a"/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="640" height="300" fill="url(%23g)"/%3E%3Ccircle cx="510" cy="72" r="110" fill="%23fff" fill-opacity=".18"/%3E%3Cpath d="M0 250 170 100l105 95 90-80 175 135" fill="none" stroke="%23fff" stroke-width="18" stroke-opacity=".72"/%3E%3C/svg%3E';
</script>
<div class="page-heading"><p class="eyebrow">Component</p><h1>Card</h1><p>Flexible media cards with depth, accent, reveal, zoom, spotlight, and 3D tilt treatments.</p></div>
<DemoSection title="Source variants" source={'<Card variant="spotlight">…</Card>'}><div class="card-grid" data-demo-section="card-variants">{#each variants as variant}<Card {variant} color={variant === 'glow' ? 'primary' : 'success'} href={['default','glow','gradient-border','lift','spotlight','tilt-3d'].includes(variant) ? '#card-target' : undefined} slides={variant === 'slider' ? [{src:mediaUri,alt:'Blue and green landscape'},{src:mediaUri,alt:'Second abstract landscape'},{src:mediaUri,alt:'Third abstract landscape'}] : []}>{#snippet media()}<img src={mediaUri} alt="Abstract landscape" />{/snippet}{#if variant === 'asset'}{#snippet actions()}<button type="button" aria-label="Save asset">♡</button><button type="button" aria-label="Download asset">↓</button>{/snippet}{/if}{#snippet header()}<strong>{variant} card</strong>{/snippet}<p>{variant === 'spotlight' || variant === 'tilt-3d' ? 'Move the pointer across the surface to drive the live effect.' : 'A source-matched Vuesax card treatment.'}</p>{#snippet footer()}<span>{variant === 'reveal' ? 'Hover to reveal' : variant}</span>{#if variant === 'reveal'}<button type="button">View details</button>{/if}{/snippet}</Card>{/each}</div><span id="card-target" class="sr-only">Card link target</span></DemoSection>
<style>.card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); gap: 2rem; width: 100%; }.card-grid :global(.rx-card) { min-width: 0; }.card-grid :global(.rx-card__footer) { display: flex; justify-content: space-between; gap: .75rem; align-items: center; }</style>
