<script lang="ts">
	import DemoSection from '../DemoSection.svelte';import {Dock} from '$lib/registry/ui/dock';import House from '@lucide/svelte/icons/house';import Search from '@lucide/svelte/icons/search';import Bell from '@lucide/svelte/icons/bell';import Settings from '@lucide/svelte/icons/settings';
	let active=$state('home');const items=[{id:'home',label:'Home',icon:home},{id:'search',label:'Search',icon:search},{id:'alerts',label:'Alerts',icon:bell},{id:'settings',label:'Settings',icon:settings}];const variants=['default','aurora','bounce','glass','gooey','magnet','neon'] as const;
</script>
{#snippet home()}<House size={20}/>{/snippet}{#snippet search()}<Search size={20}/>{/snippet}{#snippet bell()}<Bell size={20}/>{/snippet}{#snippet settings()}<Settings size={20}/>{/snippet}
<div class="page-heading"><p class="eyebrow">Component</p><h1>Dock</h1><p>Seven source-faithful physics systems: proximity magnification, aurora fields, squash bounce, glass tilt, goo trails, magnetic displacement, and a springing neon rail.</p></div>
<DemoSection title="Physics variants" source={'<Dock bind:active {items} variant="aurora" magnification={1.7} />'}><div class="gallery">{#each variants as variant}<article><header><code>{variant}</code><span>{active}</span></header><div class="dock-demo"><Dock bind:active {items} {variant} magnification={1.7}/></div></article>{/each}</div></DemoSection>
<DemoSection title="API mapping" source={'<Dock radius="pill" tone="success" magnify bounce tilt goo magnetic tooltips pulse />'}><dl><div><dt><code>variant</code></dt><dd>default · aurora · bounce · glass · gooey · magnet · neon</dd></div><div><dt><code>magnification / distance / size</code></dt><dd>Tunes the live Gaussian pointer field and item geometry.</dd></div><div><dt><code>radius / tone</code></dt><dd>none · subtle · rounded · pill · squircle, plus semantic accent routing.</dd></div><div><dt><code>magnify / bounce / tilt</code></dt><dd>Source switches for default/Aurora scale, bounce squash, and glass perspective.</dd></div><div><dt><code>goo / magnetic</code></dt><dd>Enable the goo trail or magnetic displacement engine.</dd></div><div><dt><code>placement</code></dt><dd>top · bottom · left · right, with matching arrow-key navigation.</dd></div><div><dt><code>active / onActiveChange / onSelect</code></dt><dd>Bindable stable-id selection and callbacks.</dd></div><div><dt><code>tooltips / pulse / disabled</code></dt><dd>Label visibility, neon breathing, and the whole-dock disabled state.</dd></div></dl></DemoSection>
<style>.gallery{display:grid;gap:1rem}.gallery article{min-width:0;border:1px solid rgb(var(--rx-text)/.08);border-radius:16px;background:rgb(var(--rx-bg)/.5);overflow:hidden}.gallery header{display:flex;justify-content:space-between;padding:.75rem 1rem;color:rgb(var(--rx-text)/.66);font-size:.8rem}.dock-demo{display:grid;min-height:9rem;place-items:center;overflow:auto}dl{display:grid;gap:.65rem}dl div{display:grid;grid-template-columns:minmax(10rem,.35fr) 1fr;gap:1rem;padding:.65rem;border-bottom:1px solid rgb(var(--rx-text)/.08)}dt,dd{margin:0}@media(max-width:640px){dl div{grid-template-columns:1fr}}</style>
