<script lang="ts">
	import DemoSection from'../DemoSection.svelte';import{Drawer,type DrawerPlacement,type DrawerVariant}from'$lib/registry/ui/drawer';import{Button}from'$lib/registry/ui/button';
	const variants:DrawerVariant[]=['base','blur','bounce','glass','push','slide'];let open=$state(false),protectedOpen=$state(false),placement=$state<DrawerPlacement>('right'),status=$state('Closed');function show(side:DrawerPlacement){placement=side;open=true}
</script>
<div class="page-heading"><p class="eyebrow">Component</p><h1>Drawer</h1><p>Six source drawer treatments: measured spring/wall bounce, de-blur, five-stop bounce, glass frost, coordinated page push, and depth slide.</p></div>
<DemoSection title="Source variants" source={'<Drawer variant="glass" frost="heavy">...</Drawer>'}><div class="gallery" data-demo-section="variants">{#each variants as variant}<Drawer {variant} placement="right" color={variant==='glass'?'primary':'success'} frost="heavy" bounce="springy" blurAmount={16}>{#snippet trigger()}<span class="trigger">{variant}</span>{/snippet}<p><strong>{variant}</strong> preserves its source surface and open/close choreography.</p><p>Close it to compare the asymmetric leave behavior.</p>{#snippet footer()}<span class="footnote">Focus stays trapped by the official sheet primitive.</span>{/snippet}</Drawer>{/each}</div></DemoSection>
<DemoSection title="Placements"><div class="row">{#each ['left','right','top','bottom'] as side}<Button onclick={()=>show(side as DrawerPlacement)}>{side}</Button>{/each}</div><Drawer bind:open {placement} variant="base" size={placement==='top'||placement==='bottom'?'300px':'380px'} title="Project settings" onOpenChange={(value)=>status=value?'Opened':'Closed'}><p>The base drawer springs from a 300px measured floor and wall-bounces on close.</p>{#snippet footer()}<Button onclick={()=>open=false}>Done</Button>{/snippet}</Drawer><output aria-live="polite" aria-atomic="true">{status}</output></DemoSection>
<DemoSection title="Gradient feather and guarded close"><div class="row"><Drawer variant="base" gradient placement="left" title="Gradient feather">{#snippet trigger()}<span class="trigger">140px feather</span>{/snippet}<p>No hard border, shadow, dim, or blur: the surface feathers into the page.</p></Drawer><Button variant="border" onclick={()=>protectedOpen=true}>Protected</Button></div><Drawer bind:open={protectedOpen} preventClose placement="bottom" variant="blur" title="Unsaved changes"><p>Escape and outside interaction are blocked.</p>{#snippet footer()}<Button onclick={()=>protectedOpen=false}>Save and close</Button>{/snippet}</Drawer></DemoSection>
<style>.gallery,.row{display:flex;flex-wrap:wrap;gap:.75rem}.trigger{display:inline-flex;border:1px solid rgb(var(--rx-border));border-radius:10px;padding:.7rem 1rem;background:rgb(var(--rx-surface));font-weight:650;text-transform:capitalize}.footnote{color:rgb(var(--rx-text-secondary));font-size:.8rem}output{display:block;margin-top:.75rem;color:rgb(var(--rx-text-secondary))}</style>
