<script lang="ts">
	import DemoSection from '../DemoSection.svelte';
	import { Popup, ConfirmPopup, type PopupTransition } from '$lib/registry/ui/popup';
	import { Button } from '$lib/registry/ui/button';
	let open=$state(false), confirming=$state(false), fullscreen=$state(false), protectedOpen=$state(false), result=$state('No action yet');
	const transitions:PopupTransition[]=['base','zoom','bounce','flip','slide-up'];
	let transition=$state<PopupTransition>('base');
	function show(value:typeof transition){transition=value;open=true}
</script>

<div class="page-heading"><p class="eyebrow">Component</p><h1>Popup</h1><p>Source dialogs with pointer-proximity rings, asymmetric enter/leave curves, confirmation, fullscreen, sizing, and guarded-close states.</p></div>
<DemoSection title="Source transitions" source={'<Popup bind:open transition="flip" title="Welcome">...</Popup>'}><div class="row" data-demo-section="transitions">{#each transitions as value}<Button onclick={()=>show(value)}>{value}</Button>{/each}</div><Popup bind:open {transition} color="primary" title="Welcome" onOpenChange={(value)=>result=`Popup ${value?'opened':'closed'}`}><p>Move the pointer around the morph surface to see the two-radius masked ring.</p>{#snippet footer()}<Button onclick={()=>open=false}>Done</Button>{/snippet}</Popup></DemoSection>
<DemoSection title="Confirm preset" source={'<ConfirmPopup bind:open message="This action cannot be undone." destructive />'}><Button color="danger" style="color:hsl(from rgb(var(--rx-color)) h 35% 8%)" onclick={()=>confirming=true}>Delete project</Button><ConfirmPopup bind:open={confirming} title="Delete project?" message="This action cannot be undone." confirmLabel="Delete" cancelLabel="Keep project" destructive onConfirm={()=>result='Confirmed deletion'} onCancel={()=>result='Cancelled deletion'}/><output aria-live="polite" aria-atomic="true">{result}</output></DemoSection>
<DemoSection title="Fullscreen and prevent close" source={'<Popup fullscreen preventClose title="Protected">...</Popup>'}><div class="row"><Button onclick={()=>fullscreen=true}>Fullscreen</Button><Button variant="border" onclick={()=>protectedOpen=true}>Protected popup</Button></div><Popup bind:open={fullscreen} fullscreen title="Fullscreen workspace"><p>This surface fills the viewport while retaining dialog semantics.</p></Popup><Popup bind:open={protectedOpen} preventClose title="Protected changes"><p>Escape and outside interaction are blocked. Use the explicit action.</p>{#snippet footer()}<Button onclick={()=>protectedOpen=false}>Close safely</Button>{/snippet}</Popup></DemoSection>
<DemoSection title="Trigger snippet" source={'<Popup>{#snippet trigger()}Open inline{/snippet}...</Popup>'}><Popup title="Built-in trigger">{#snippet trigger()}<span class="trigger">Open from trigger snippet</span>{/snippet}<p>The optional trigger snippet is wired to the official dialog trigger.</p></Popup></DemoSection>
<DemoSection title="Size, radius, and scrolling"><div class="row"><Popup size="sm" radius="pill" title="Small pill">{#snippet trigger()}<span class="trigger">Small pill</span>{/snippet}<p>360px source width and pill radius.</p></Popup><Popup size="lg" radius="squircle" title="Large squircle">{#snippet trigger()}<span class="trigger">Large squircle</span>{/snippet}<p>640px source width with scrollable body.</p></Popup></div></DemoSection>
<style>.row{display:flex;flex-wrap:wrap;gap:.75rem}.trigger{display:inline-flex;border-radius:var(--rx-radius);padding:.7rem 1rem;background:rgb(var(--rx-primary));color:var(--rx-primary-foreground);font-weight:650}output{display:block;margin-top:.75rem;color:rgb(var(--rx-text-secondary))}</style>
