import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render}from'@testing-library/svelte';import{tick}from'svelte';import Harness from'./phase-5c-test-harness.svelte';
let resize:()=>void;class RO{constructor(cb:()=>void){resize=cb}observe(){}disconnect(){}}
describe('phase 5c',()=>{beforeEach(()=>{vi.stubGlobal('ResizeObserver',RO);vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>{cb(0);return 1});vi.stubGlobal('cancelAnimationFrame',vi.fn())});afterEach(()=>{cleanup();vi.unstubAllGlobals()});
	it('normalizes tick bounds and emits exact stepped input',async()=>{const view=render(Harness);const slider=view.getByRole('slider')as HTMLInputElement;expect(slider.min).toBe('0');expect(slider.max).toBe('10');await fireEvent.input(slider,{target:{value:'8'}});expect(view.container.querySelector('output')?.textContent).toBe('8')});
	it('keeps mounted transform content inert while hidden',()=>{const view=render(Harness,{props:{mode:'transform'}});const shell=view.getByText('Inside').parentElement;expect(shell?.hasAttribute('hidden')).toBe(true);expect(shell?.getAttribute('aria-hidden')).toBe('true')});
	it('cleans Ask AI pointer decoration and reflects loading',()=>{const remove=vi.spyOn(HTMLElement.prototype,'removeEventListener');const view=render(Harness,{props:{mode:'ai',disabled:true}});expect((view.getByRole('button')as HTMLButtonElement).disabled).toBe(true);view.unmount();expect(remove.mock.calls.some(([type])=>type==='pointermove')).toBe(true)});
	it('uses group semantics and vertical orientation',()=>{const view=render(Harness,{props:{mode:'group'}});const group=view.getByRole('group');expect(group.getAttribute('data-orientation')).toBe('vertical');expect(view.getAllByRole('button').map(x=>x.textContent?.trim())).toEqual(['A','B'])});
	it('separates split action and menu trigger and coherently disables both',async()=>{const view=render(Harness,{props:{mode:'split'}});await fireEvent.click(view.getByRole('button',{name:'Save'}));expect(view.getByText('1').tagName).toBe('OUTPUT');expect(view.getByRole('button',{name:'More Save options'})).toBeTruthy();view.unmount();const off=render(Harness,{props:{mode:'split',disabled:true}});expect((off.getByRole('button',{name:'Save'})as HTMLButtonElement).disabled).toBe(true);expect((off.getByRole('button',{name:'More Save options'})as HTMLButtonElement).disabled).toBe(true)});
	it('moves overflow items after resize without exposing measurement clones',async()=>{const view=render(Harness,{props:{mode:'overflow'}});const root=view.container.querySelector('.rx-overflow')as HTMLElement;Object.defineProperty(root,'clientWidth',{value:120});for(const el of root.querySelectorAll<HTMLElement>('[data-measure]'))Object.defineProperty(el,'offsetWidth',{value:70});resize();await tick();expect(view.getByRole('button',{name:/More/})).toBeTruthy();expect(root.querySelector('.rx-overflow__measure')?.getAttribute('aria-hidden')).toBe('true')});
});
