import {cleanup,fireEvent,render} from '@testing-library/svelte';import {afterEach,describe,expect,it,vi} from 'vitest';import Harness from './phase-5a-test-harness.svelte';
describe('phase 5a data display',()=>{
	afterEach(cleanup);
 it('sorts generic columns and exposes aria-sort',async()=>{const v=render(Harness);const sort=v.getAllByRole('button',{name:/Name/})[0];expect(sort.closest('th')?.getAttribute('aria-sort')).toBe('none');await fireEvent.click(sort);expect(sort.closest('th')?.getAttribute('aria-sort')).toBe('ascending');expect(v.container.querySelector('tbody tr')?.textContent).toContain('Alpha')});
 it('selects all rows and expands content',async()=>{const v=render(Harness);const all=v.getByRole('checkbox',{name:'Select all rows'});await fireEvent.click(all);expect(v.getAllByRole('checkbox',{name:/Select row/})).toHaveLength(2);await fireEvent.click(v.getByRole('button',{name:'Expand row b'}));expect(v.getByText('Details Beta')).toBeTruthy()});
 it('renders empty state and pagination',()=>{const v=render(Harness);expect(v.getByText('No results.')).toBeTruthy();expect(v.getByRole('navigation',{name:'Pagination'})).toBeTruthy()});
 it('uses named listbox semantics, keyboard conventions, and skips disabled options',async()=>{const v=render(Harness);expect(v.getByRole('listbox',{name:'Items'})).toBeTruthy();const one=v.getByRole('option',{name:'One'});expect(one.tagName).toBe('BUTTON');one.focus();await fireEvent.keyDown(one,{key:'ArrowDown'});expect(document.activeElement?.getAttribute('data-rx-list-id')).toBe('two');await fireEvent.keyDown(document.activeElement!,{key:' '});expect(v.getByTestId('list-state').textContent).toContain('two')});
 it('escapes unknown code and reports copy success and failure',async()=>{const writeText=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText}});const v=render(Harness);expect(v.container.querySelector('script')).toBeNull();await fireEvent.click(v.getByRole('button',{name:'Copy'}));expect(writeText).toHaveBeenCalled();expect(v.container.textContent).toContain('Copied');writeText.mockRejectedValueOnce(new Error('no'));await fireEvent.click(v.getByRole('button',{name:'Copy'}));expect(v.container.textContent).toContain('Could not copy')});
});
