import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render}from'@testing-library/svelte';import{tick}from'svelte';import Harness from'./phase-5c-test-harness.svelte';
class RO{constructor(_cb:()=>void){}observe(){}disconnect(){}}
describe('phase 5c',()=>{beforeEach(()=>{vi.stubGlobal('ResizeObserver',RO);vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>{cb(0);return 1});vi.stubGlobal('cancelAnimationFrame',vi.fn());vi.stubGlobal('matchMedia',()=>({matches:true}))});afterEach(()=>{cleanup();vi.unstubAllGlobals()});
	it('navigates the source tick rail with roving keyboard focus',async()=>{const view=render(Harness);const rail=view.getByRole('toolbar',{name:'Timeline'}),root=rail.closest<HTMLElement>('.rx-rail')!;const ticks=view.getAllByRole('button');expect(root.style.getPropertyValue('--rx-rail-height')).toBe('45px');expect(ticks[0].getAttribute('aria-current')).toBe('true');await fireEvent.keyDown(rail,{key:'ArrowDown'});expect(view.container.querySelector('output')?.textContent).toBe('1');expect(ticks[1].getAttribute('tabindex')).toBe('0')});
	it('keeps mounted transform content inert while hidden',()=>{const view=render(Harness,{props:{mode:'transform'}});const shell=view.getByText('Inside').parentElement;expect(shell?.hasAttribute('hidden')).toBe(true);expect(shell?.getAttribute('aria-hidden')).toBe('true')});
	it('cleans Ask AI pointer decoration and reflects loading',()=>{const remove=vi.spyOn(HTMLElement.prototype,'removeEventListener');const view=render(Harness,{props:{mode:'ai',disabled:true}});expect((view.getByRole('button')as HTMLButtonElement).disabled).toBe(true);view.unmount();expect(remove.mock.calls.some(([type])=>type==='pointermove')).toBe(true)});
	it('uses group semantics and vertical orientation',()=>{const view=render(Harness,{props:{mode:'group'}});const group=view.getByRole('group');expect(group.getAttribute('data-orientation')).toBe('vertical');expect(view.getByRole('button',{name:'A'})).toBeTruthy();expect(view.getByRole('button',{name:'B'})).toBeTruthy()});
	it('opens source split actions and coherently disables every control',async()=>{const view=render(Harness,{props:{mode:'split'}});await fireEvent.click(view.getByRole('button',{name:'Save'}));expect(view.getByText('1').tagName).toBe('OUTPUT');expect(view.getByRole('button',{name:'Back'})).toBeTruthy();expect(view.getByRole('button',{name:'Draft'})).toBeTruthy();view.unmount();const off=render(Harness,{props:{mode:'split',disabled:true}});expect((off.getByRole('button',{name:'Save'})as HTMLButtonElement).disabled).toBe(true);expect((off.getByRole('button',{name:'Back'})as HTMLButtonElement).disabled).toBe(true)});
	it('reveals overflow actions in place and restores trigger state',async()=>{const view=render(Harness,{props:{mode:'overflow'}});const toolbar=view.getByRole('toolbar',{name:'Actions'});const trigger=view.getByRole('button',{name:'More actions'});expect((toolbar.querySelector('.rx-io__item.is-tucked') as HTMLElement).inert).toBe(true);await fireEvent.click(trigger);await tick();expect(trigger.getAttribute('aria-expanded')).toBe('true');expect((toolbar.querySelector('.rx-io__item.is-tucked') as HTMLElement).inert).not.toBe(true);await fireEvent.keyDown(toolbar,{key:'Escape'});expect(view.getByRole('button',{name:'More actions'}).getAttribute('aria-expanded')).toBe('false')});
});
