import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import {cleanup,fireEvent,render} from '@testing-library/svelte';import Harness from './shell-physics-test-harness.svelte';import dockSource from './dock/dock.svelte?raw';
class ResizeObserverMock{observe=vi.fn();disconnect=vi.fn()}
describe('source shell physics',()=>{beforeEach(()=>{vi.stubGlobal('ResizeObserver',ResizeObserverMock);vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()}));vi.stubGlobal('requestAnimationFrame',(callback:FrameRequestCallback)=>window.setTimeout(()=>callback(performance.now()),0));vi.stubGlobal('cancelAnimationFrame',(id:number)=>clearTimeout(id))});afterEach(()=>{cleanup();vi.useRealTimers();vi.unstubAllGlobals()});
	it('measures sidebar hover and nav trigger indicators while tracking pointer light',async()=>{const view=render(Harness);const sidebar=view.getByTestId('sidebar-shell'),item=view.getByText('Sidebar home').closest<HTMLElement>('[data-rx-sidebar-item]');expect(item).toBeTruthy();await fireEvent.pointerOver(item!);expect(sidebar.querySelector('[data-rx-sidebar-hover]')?.getAttribute('data-ready')).toBe('true');const nav=view.getByTestId('nav-shell'),trigger=view.getByRole('button',{name:'Products'}),stage=nav.querySelector<HTMLElement>('.rx-nav__stage');await fireEvent.pointerOver(trigger);const indicator=nav.querySelector<HTMLElement>('[data-rx-nav-indicator]');expect(indicator?.dataset.ready).toBe('true');await fireEvent.pointerMove(stage!,{clientX:44,clientY:23});expect(stage?.style.getPropertyValue('--pointer-x')).toBe('44px')});
	it('syncs the public open state into the official mobile sheet',async()=>{vi.stubGlobal('matchMedia',(query:string)=>({matches:query.includes('max-width'),media:query,addEventListener:vi.fn(),removeEventListener:vi.fn(),addListener:vi.fn(),removeListener:vi.fn(),dispatchEvent:vi.fn()}));const view=render(Harness);await vi.waitFor(()=>expect(view.getByRole('dialog')).toBeTruthy());expect(view.getByText('Sidebar home')).toBeTruthy()});
	it('exposes dock pointer layers and live glass geometry',async()=>{const view=render(Harness),dock=view.getByRole('navigation',{name:'Application dock'}),bar=dock.querySelector<HTMLElement>('[data-rx-dock-bar]');expect(dock.querySelector('.rx-dock__sheen')).toBeTruthy();expect(dock.querySelector('.rx-dock__edge')).toBeTruthy();await fireEvent.pointerMove(bar!,{pointerType:'mouse',clientX:30,clientY:20});await new Promise(resolve=>setTimeout(resolve,1));expect(bar?.classList.contains('is-tracking')).toBe(true);expect(bar?.style.getPropertyValue('--sheen-o')).toBe('1');await fireEvent.pointerLeave(bar!);expect(bar?.classList.contains('is-tracking')).toBe(false)});
	it('maps each selected dock icon to its source accent or ink role',async()=>{const view=render(Harness),home=view.getByRole('link',{name:'Dock home'}),search=view.getByRole('link',{name:'Dock search'});expect(home.classList.contains('is-active')).toBe(true);expect(search.classList.contains('is-active')).toBe(false);await fireEvent.click(search);await vi.waitFor(()=>expect(search.classList.contains('is-active')).toBe(true));expect(home.classList.contains('is-active')).toBe(false);expect(dockSource).toContain('.rx-dock__item.is-active{color:rgb(var(--rx-color))}');expect(dockSource).toContain('.rx-dock--gooey .rx-dock__item.is-active{color:rgb(var(--rx-text))}');expect(dockSource).toContain('.rx-dock--neon.rx-dock--t-default .rx-dock__item.is-active{color:rgb(var(--rx-text))}')});
	it('separates reduced motion from coarse-pointer dock policy',()=>{expect(dockSource).toContain('@media(prefers-reduced-motion:reduce){');expect(dockSource).toContain('@media(pointer:coarse){');expect(dockSource).not.toContain('@media(prefers-reduced-motion:reduce),(pointer:coarse)');expect(dockSource).toContain('@media(pointer:coarse){.rx-dock__item,.rx-dock__ico{transform:none!important}.rx-dock--glass .rx-dock__bar{transform:none!important}.rx-dock__sheen,.rx-dock__halo{display:none!important}}');expect(dockSource).toContain('.rx-dock--aurora .rx-dock__aurora::before');expect(dockSource).toContain('.rx-dock--neon.is-pulse .rx-dock__item.is-active .rx-dock__ico{animation:rx-neon-pulse');expect(dockSource).toContain('.rx-dock--bounce .rx-dock__item:global(.is-press) .rx-dock__ico{animation:rx-dock-press')});
	it('renders ghost thumbs, adaptive dot renderers, two-axis tracks, and clears listeners',()=>{const added=vi.spyOn(HTMLElement.prototype,'addEventListener'),removed=vi.spyOn(HTMLElement.prototype,'removeEventListener'),view=render(Harness),scroll=view.getByTestId('scroll-shell');expect(scroll.querySelectorAll('[data-rx-scroll-track]')).toHaveLength(2);expect(scroll.querySelectorAll('[data-rx-scroll-ghost]')).toHaveLength(2);expect(scroll.querySelectorAll('[data-rx-scroll-thumb] i').length).toBeGreaterThanOrEqual(6);const pointerAdds=added.mock.calls.filter(([type])=>type==='pointercancel').length;view.unmount();expect(removed.mock.calls.filter(([type])=>type==='pointercancel').length).toBe(pointerAdds)});
});
