import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import {cleanup,fireEvent,render} from '@testing-library/svelte';import {tick} from 'svelte';import Harness from './slide-confirm-test-harness.svelte';
let resize:()=>void;class ResizeObserverMock{constructor(callback:()=>void){resize=callback}observe(){}disconnect(){}}
function geometry(view:{container:HTMLElement;getByRole:(role:string)=>HTMLElement}){const root=view.container.querySelector('.rx-slide') as HTMLElement;const thumb=view.getByRole('slider');root.getBoundingClientRect=()=>({left:0,right:360,top:0,bottom:56,width:360,height:56,x:0,y:0,toJSON(){}});thumb.getBoundingClientRect=()=>({left:4,right:52,top:4,bottom:52,width:48,height:48,x:4,y:4,toJSON(){}});Object.assign(thumb,{setPointerCapture:vi.fn(),releasePointerCapture:vi.fn(),hasPointerCapture:()=>true});resize();return {root,thumb}}
function pointer(node:Element,type:string,pointerId:number,clientX:number){const event=new MouseEvent(type,{bubbles:true,clientX});Object.defineProperty(event,'pointerId',{value:pointerId});Object.defineProperty(event,'pointerType',{value:'mouse'});return fireEvent(node,event)}
describe('SlideConfirm',()=>{beforeEach(()=>vi.stubGlobal('ResizeObserver',ResizeObserverMock));afterEach(()=>{cleanup();document.documentElement.removeAttribute('dir');vi.unstubAllGlobals()});
	it('confirms once above threshold and resets below threshold',async()=>{const confirmed=vi.fn(),changed=vi.fn();const view=render(Harness,{props:{threshold:.8,onConfirm:confirmed,onChange:changed}});const {thumb}=geometry(view);await pointer(thumb,'pointerdown',1,0);await pointer(thumb,'pointermove',1,300);await pointer(thumb,'pointerup',1,300);expect(view.getByText('yes').tagName).toBe('OUTPUT');expect(confirmed).toHaveBeenCalledTimes(1);expect(changed).toHaveBeenCalledWith(true);await pointer(thumb,'pointerup',1,300);expect(confirmed).toHaveBeenCalledTimes(1)});
	it('settles below threshold and cancels on pointercancel and resize',async()=>{const view=render(Harness,{props:{threshold:.9}});const {thumb}=geometry(view);await pointer(thumb,'pointerdown',1,0);await pointer(thumb,'pointermove',1,80);await pointer(thumb,'pointerup',1,80);await tick();expect(thumb.getAttribute('aria-valuenow')).toBe('0');for(const end of ['pointerCancel','resize'] as const){await pointer(thumb,'pointerdown',2,0);await pointer(thumb,'pointermove',2,80);if(end==='pointerCancel')await pointer(thumb,'pointercancel',2,80);else resize();await tick();expect(thumb.getAttribute('aria-valuenow')).toBe('0')}});
	it('supports equivalent keyboard confirmation, reset, RTL direction, and inactive states',async()=>{const changed=vi.fn();const view=render(Harness,{props:{resettable:true,onChange:changed}});const {root,thumb}=geometry(view);root.style.direction='rtl';resize();await fireEvent.keyDown(thumb,{key:'ArrowLeft'});expect(view.getByText('yes')).toBeTruthy();await fireEvent.keyDown(thumb,{key:'Home'});expect(view.getByText('no')).toBeTruthy();await fireEvent.keyDown(thumb,{key:'Enter'});expect(changed.mock.calls).toEqual([[true],[false],[true]]);view.unmount();for(const props of [{disabled:true},{loading:true}]){const inactive=render(Harness,{props});expect((inactive.getByRole('slider') as HTMLButtonElement).disabled).toBe(true);inactive.unmount()}});
});
