<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { RxColor } from '$lib/registry/lib/color';
	export interface DockItem { id:string; label:string; icon:Snippet; href?:string; disabled?:boolean; onSelect?:()=>void }
	export interface DockProps {
		items:DockItem[]; active?:string; color?:RxColor; variant?:'default'|'aurora'|'bounce'|'glass'|'gooey'|'magnet'|'neon';
		placement?:'top'|'bottom'|'left'|'right'; size?:'sm'|'default'|'lg'; radius?:'none'|'subtle'|'rounded'|'pill'|'squircle'; tone?:'default'|'danger'|'warn'|'success'; magnification?:number; distance?:number;
		magnify?:boolean; bounce?:boolean; tilt?:boolean; goo?:boolean; magnetic?:boolean; tooltips?:boolean; pulse?:boolean; disabled?:boolean; onSelect?:(item:DockItem)=>void; onActiveChange?:(id:string)=>void;
	}
</script>

<script lang="ts">
	import { styleColor } from '$lib/registry/lib/color';
	import { neighborLight } from '$lib/registry/attachments/neighbor-light';
	let {items,active=$bindable(''),color,variant='default',placement='bottom',size='default',radius='squircle',tone='default',magnification=1.55,distance=110,magnify=true,bounce=true,tilt=true,goo=true,magnetic=true,tooltips=true,pulse=true,disabled=false,onSelect,onActiveChange}:DockProps=$props();
	const selected=$derived(active||items[0]?.id||'');
	const attachNeighbor=$derived(neighborLight({disabled:()=>disabled}));

	function dockPhysics(node:HTMLElement){
		const foundBar=node.querySelector<HTMLElement>('[data-rx-dock-bar]');if(!foundBar)return;const barEl:HTMLElement=foundBar;
		const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,vertical=placement==='left'||placement==='right';
		let frame=0,pointer=0,pointerCross=0,tracking=false;
		let railX=0,railW=0,railVX=0,railVW=0,railTargetX=0,railTargetW=0;
		const itemEls=()=>Array.from(barEl.querySelectorAll<HTMLElement>('[data-rx-dock-item]'));
		function resetItems(){for(const item of itemEls()){item.style.setProperty('--s','1');item.style.setProperty('--tx','0px');item.style.setProperty('--ty','0px');item.style.setProperty('--rot','0deg');item.style.setProperty('--sx','1');item.style.setProperty('--sy','1');item.style.setProperty('--near','0')}barEl.classList.remove('is-tracking');barEl.style.setProperty('--sheen-o','0');barEl.style.setProperty('--rx','0deg');barEl.style.setProperty('--ry','0deg');node.style.setProperty('--au-a','0')}
		function updateGoo(){const target=barEl.querySelector<HTMLElement>('[data-rx-dock-item][data-active="true"]');if(!target)return;barEl.style.setProperty('--blob-x',`${target.offsetLeft}px`);barEl.style.setProperty('--blob-y',`${target.offsetTop+target.offsetHeight*.09}px`);barEl.style.setProperty('--blob-w',`${target.offsetWidth}px`);barEl.style.setProperty('--blob-h',`${target.offsetHeight*.82}px`)}
		function measureRail(target:HTMLElement|null){if(!target)return;railTargetX=vertical?target.offsetTop:target.offsetLeft;railTargetW=vertical?target.offsetHeight:target.offsetWidth}
		function update(time:number){frame=0;let moving=false;const els=itemEls(),rect=barEl.getBoundingClientRect();
			if(tracking&&!reduce){const primary=vertical?pointerCross:pointer,secondary=vertical?pointer:pointerCross;const mainStart=vertical?rect.top:rect.left,mainSize=vertical?rect.height:rect.width,crossStart=vertical?rect.left:rect.top,crossSize=vertical?rect.width:rect.height;const mx=vertical?secondary-crossStart:primary-mainStart,my=vertical?primary-mainStart:secondary-crossStart;barEl.style.setProperty('--mx',`${mx.toFixed(1)}px`);barEl.style.setProperty('--my',`${my.toFixed(1)}px`);barEl.style.setProperty('--gx',`${mx.toFixed(1)}px`);barEl.style.setProperty('--gy',`${my.toFixed(1)}px`);barEl.style.setProperty('--glow','1');barEl.style.setProperty('--sheen-o','1');node.style.setProperty('--aux',`${mx.toFixed(1)}px`);node.style.setProperty('--auy',`${my.toFixed(1)}px`);node.style.setProperty('--au-a','1');
				if(variant==='glass'&&tilt){const nx=Math.max(-1,Math.min(1,mx/crossSize*2-1)),ny=Math.max(-1,Math.min(1,my/mainSize*2-1));barEl.style.setProperty('--ry',`${(nx*4).toFixed(2)}deg`);barEl.style.setProperty('--rx',`${(-ny*4).toFixed(2)}deg`)}
				for(const item of els){const r=item.getBoundingClientRect(),center=vertical?r.top+r.height/2:r.left+r.width/2,d=primary-center,gaussian=Math.exp(-(d*d)/(2*distance*distance));if(variant==='gooey'||variant==='neon')continue;if(variant==='magnet'&&magnetic){const influence=Math.max(0,1-Math.abs(d)/distance)**2,crossCenter=vertical?r.left+r.width/2:r.top+r.height/2,crossDelta=secondary-crossCenter,pull=Math.max(-14,Math.min(14,d*.22))*influence,crossPull=Math.max(-10,Math.min(10,crossDelta*.16))*influence;item.style.setProperty('--tx',`${(vertical?crossPull:pull).toFixed(2)}px`);item.style.setProperty('--ty',`${(vertical?pull:crossPull).toFixed(2)}px`);item.style.setProperty('--rot',`${(Math.sign(d)*-7*influence).toFixed(2)}deg`);item.style.setProperty('--s',`${(1+.24*influence).toFixed(3)}`);item.style.setProperty('--near',influence.toFixed(3))}else if(variant==='bounce'&&bounce){const lift=-18*gaussian;item.style.setProperty('--ty',`${lift.toFixed(2)}px`);item.style.setProperty('--sx',`${(1-.06*gaussian).toFixed(3)}`);item.style.setProperty('--sy',`${(1+.16*gaussian).toFixed(3)}`);item.style.setProperty('--near',gaussian.toFixed(3))}else if(((variant==='default'||variant==='aurora')&&magnify)||(variant==='glass'&&tilt)){const scale=variant==='glass'?1+.12*gaussian:1+(magnification-1)*gaussian,lift=variant==='glass'?-6*gaussian:-.34*r.height*gaussian,side=-Math.sign(d)*.16*r.width*gaussian;item.style.setProperty('--s',scale.toFixed(4));item.style.setProperty('--ty',`${(vertical?side:lift).toFixed(2)}px`);item.style.setProperty('--tx',`${(vertical?lift:side).toFixed(2)}px`);item.style.setProperty('--near',gaussian.toFixed(3))}}
			}
			if(variant==='neon'){railVX=(railVX+(railTargetX-railX)*.16)*.74;railVW=(railVW+(railTargetW*.6-railW)*.16)*.74;railX+=railVX;railW+=railVW;const rail=barEl.querySelector<HTMLElement>('[data-rx-dock-rail]');if(rail){rail.style.setProperty('--rail-x',`${(railX+railTargetW*.2).toFixed(2)}px`);rail.style.setProperty('--rail-w',`${railW.toFixed(2)}px`);rail.style.setProperty('--rail-on',railW>0?'1':'0')}moving=Math.abs(railTargetX-railX)>.25||Math.abs(railTargetW*.6-railW)>.25||Math.abs(railVX)>.25||Math.abs(railVW)>.25}
			if(tracking||moving)frame=requestAnimationFrame(update)
		}
		function move(e:PointerEvent){if(e.pointerType&&e.pointerType!=='mouse'||reduce)return;pointer=vertical?e.clientY:e.clientX;pointerCross=vertical?e.clientX:e.clientY;tracking=true;barEl.classList.add('is-tracking');if(!frame)frame=requestAnimationFrame(update)}
		function leave(){tracking=false;if(frame){cancelAnimationFrame(frame);frame=0}resetItems();const chosen=barEl.querySelector<HTMLElement>(`[data-rx-dock-item][data-active="true"]`);if(variant==='neon'){measureRail(chosen);frame=requestAnimationFrame(update)}}
		function over(e:PointerEvent|FocusEvent){const target=(e.target as Element|null)?.closest<HTMLElement>('[data-rx-dock-item]');if(target&&variant==='neon'){measureRail(target);if(!frame)frame=requestAnimationFrame(update)}}
		function press(e:PointerEvent){const target=(e.target as Element|null)?.closest<HTMLElement>('[data-rx-dock-item]');if(!target||variant!=='bounce'||!bounce)return;target.classList.remove('is-press');void target.offsetWidth;target.classList.add('is-press');window.setTimeout(()=>target.classList.remove('is-press'),320)}
		function keydown(e:KeyboardEvent){if(!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;const enabled=itemEls().filter(el=>el.getAttribute('aria-disabled')!=='true'),current=enabled.indexOf(document.activeElement as HTMLElement);if(current<0)return;e.preventDefault();const delta=e.key==='ArrowRight'||e.key==='ArrowDown'?1:-1,index=e.key==='Home'?0:e.key==='End'?enabled.length-1:(current+delta+enabled.length)%enabled.length;enabled[index]?.focus()}
		barEl.addEventListener('pointermove',move,{passive:true});barEl.addEventListener('pointerleave',leave);barEl.addEventListener('pointerover',over);barEl.addEventListener('focusin',over);barEl.addEventListener('pointerdown',press);barEl.addEventListener('keydown',keydown);const resize=()=>{leave();updateGoo()};window.addEventListener('resize',resize,{passive:true});const observer=new MutationObserver(updateGoo);observer.observe(barEl,{subtree:true,attributes:true,attributeFilter:['data-active']});requestAnimationFrame(()=>{const chosen=barEl.querySelector<HTMLElement>('[data-active="true"]');measureRail(chosen);railX=railTargetX;railW=railTargetW*.6;updateGoo();if(variant==='neon')update(0)});
		return()=>{barEl.removeEventListener('pointermove',move);barEl.removeEventListener('pointerleave',leave);barEl.removeEventListener('pointerover',over);barEl.removeEventListener('focusin',over);barEl.removeEventListener('pointerdown',press);barEl.removeEventListener('keydown',keydown);window.removeEventListener('resize',resize);observer.disconnect();if(frame)cancelAnimationFrame(frame)}
	}
	function choose(item:DockItem,e:MouseEvent){if(disabled||item.disabled){e.preventDefault();return}active=item.id;item.onSelect?.();onSelect?.(item);onActiveChange?.(item.id)}
</script>

<nav class="rx-dock rx-dock--{variant} rx-dock--{placement} rx-dock--{size} rx-dock--r-{radius} rx-dock--t-{tone}" class:is-pulse={pulse} class:no-goo={!goo} class:is-disabled={disabled} aria-label="Application dock" style={styleColor(color)??`--rx-color:var(--rx-${tone==='default'?'primary':tone})`} {@attach dockPhysics} {@attach attachNeighbor}>
	<div class="rx-dock__stage"><span class="rx-dock__aurora" aria-hidden="true"></span><span class="rx-dock__halo" aria-hidden="true"></span>
		<div class="rx-dock__bar" data-rx-dock-bar role="toolbar" aria-label="Dock controls" aria-disabled={disabled?'true':undefined}><span class="rx-dock__sheen" aria-hidden="true"></span><span class="rx-dock__edge" aria-hidden="true"></span><span class="rx-dock__glow" aria-hidden="true"></span>
			<span class="rx-dock__goo" aria-hidden="true"><svg width="0" height="0"><defs><filter id="rx-dock-goo"><feGaussianBlur in="SourceGraphic" stdDeviation="7" result="blur"/><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 24 -10" result="goo"/><feComposite in="SourceGraphic" in2="goo" operator="atop"/></filter></defs></svg><i class="rx-dock__blob rx-dock__blob--trail"></i><i class="rx-dock__blob rx-dock__blob--head"></i></span>
			{#each items as item(item.id)}<a data-rx-dock-item data-active={selected===item.id?'true':'false'} class="rx-dock__item" class:is-active={selected===item.id} class:is-lit={variant==='gooey'&&goo&&selected===item.id} href={item.href??'#'} aria-label={item.label} aria-current={selected===item.id?'page':undefined} aria-disabled={disabled||item.disabled?'true':undefined} tabindex={disabled||item.disabled?-1:undefined} onclick={(e)=>choose(item,e)}><span class="rx-dock__ico" aria-hidden="true">{@render item.icon()}</span><span class="rx-dock__dot" aria-hidden="true"></span>{#if tooltips}<span class="rx-dock__label" role="tooltip">{item.label}</span>{/if}</a>{/each}
			<span class="rx-dock__rail" data-rx-dock-rail aria-hidden="true"></span>
		</div>
	</div>
</nav>

<style>
	@property --lit{syntax:'<number>';inherits:true;initial-value:.3}
	.rx-dock{--box:52px;--icon:24px;--gap:6px;--pad:8px;--rr:26px;display:inline-flex;max-width:100%;color:rgb(var(--rx-text));perspective:900px}.rx-dock--sm{--box:44px;--icon:20px;--gap:5px;--pad:6px;--rr:20px}.rx-dock--lg{--box:60px;--icon:28px;--gap:8px;--pad:10px;--rr:30px}.rx-dock__stage{position:relative;display:inline-flex;max-width:100%;padding-top:calc(var(--box)*.9)}.rx-dock__bar{position:relative;isolation:isolate;display:inline-flex;align-items:flex-end;flex-wrap:wrap;justify-content:center;max-width:100%;gap:var(--gap);padding:var(--pad);border:1px solid rgb(var(--rx-text)/.09);border-radius:var(--rr);background:rgb(var(--rx-bg)/.78);backdrop-filter:blur(18px) saturate(140%);box-shadow:inset 0 1px rgb(var(--rx-light)/.06),0 24px 60px -22px rgb(var(--rx-dark)/.6);overflow:visible}.rx-dock--left .rx-dock__bar,.rx-dock--right .rx-dock__bar{flex-direction:column}.rx-dock__glow{position:absolute;inset:-1px;z-index:1;border-radius:inherit;padding:1px;pointer-events:none;background:radial-gradient(60px circle at var(--gx,50%) var(--gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.42) 30%,rgb(var(--rx-color)/.16) 58%,transparent 82%),radial-gradient(200px circle at var(--gx,50%) var(--gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.27) 42%,rgb(var(--rx-color)/.08) 66%,transparent 85%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);mask-composite:exclude;opacity:calc(var(--glow,0)*.63);transition:opacity 140ms}
	.rx-dock__item{position:relative;z-index:2;flex:0 0 auto;display:grid;place-items:center;width:var(--box);height:var(--box);padding:0;border:0;border-radius:calc(var(--box)*.3);color:color-mix(in srgb,rgb(var(--rx-text)/.58),rgb(var(--rx-text)) calc(var(--near,0)*100%));background:transparent;text-decoration:none;transform:translate3d(var(--tx,0),var(--ty,0),0) rotate(var(--rot,0)) scale(var(--s,1));transform-origin:bottom center;will-change:transform;transition:background-color 200ms ease,color 200ms ease}.rx-dock__item:hover{color:rgb(var(--rx-text));background:rgb(var(--rx-color)/.07)}.rx-dock__item:active{background:rgb(var(--rx-color)/.12)}.rx-dock__item:focus-visible{outline:none;box-shadow:0 0 0 2px rgb(var(--rx-color)/.7)}.rx-dock__item.is-active{color:rgb(var(--rx-color))}.rx-dock__item[aria-disabled=true]{pointer-events:none;opacity:.42}.rx-dock__ico{display:grid;place-items:center;width:var(--icon);height:var(--icon);transform:scaleX(var(--sx,1)) scaleY(var(--sy,1));transform-origin:bottom center}.rx-dock__ico :global(svg){width:100%;height:100%}.rx-dock__dot{position:absolute;bottom:calc(var(--pad)*-.5 - 2px);left:50%;width:4px;height:4px;border-radius:50%;background:rgb(var(--rx-color));translate:-50%;scale:0;opacity:0;transition:scale 260ms cubic-bezier(.34,1.56,.64,1),opacity 200ms}.rx-dock__item.is-active .rx-dock__dot{scale:1;opacity:1}.rx-dock__label{position:absolute;bottom:calc(100% + 14px);left:50%;translate:-50%;padding:4px 9px;border-radius:8px;white-space:nowrap;pointer-events:none;color:rgb(var(--rx-bg));background:rgb(var(--rx-text));font-size:12px;font-weight:500;opacity:0;scale:.92;transition:opacity 140ms,scale 160ms cubic-bezier(.34,1.56,.64,1)}.rx-dock__item:is(:hover,:focus-visible) .rx-dock__label{opacity:1;scale:1}
	.rx-dock--bounce .rx-dock__item{transition:transform 240ms cubic-bezier(.22,1.5,.36,1),background-color 200ms,color 200ms}.rx-dock--bounce .rx-dock__ico{transition:transform 240ms cubic-bezier(.22,1.5,.36,1)}.rx-dock--bounce .rx-dock__item:global(.is-press) .rx-dock__ico{animation:rx-dock-press 320ms cubic-bezier(.3,1.25,.5,1)}@keyframes rx-dock-press{0%{scale:1}26%{scale:1.1 .86}58%{scale:.97 1.06}100%{scale:1}}
	.rx-dock--glass .rx-dock__bar{background:rgb(var(--rx-bg)/.62);backdrop-filter:blur(26px) saturate(180%);transform:rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg));transition:transform 460ms cubic-bezier(.22,1,.36,1)}.rx-dock__sheen,.rx-dock__edge{display:none}.rx-dock--glass .rx-dock__sheen{display:block;position:absolute;inset:0;z-index:0;border-radius:inherit;pointer-events:none;background:radial-gradient(190px circle at var(--mx,50%) var(--my,50%),rgb(var(--rx-color)/.26),rgb(var(--rx-color)/.1) 34%,transparent 68%);opacity:var(--sheen-o,0);transition:opacity 420ms}.rx-dock--glass .rx-dock__edge{display:block;position:absolute;inset:0;z-index:1;border-radius:inherit;pointer-events:none;background:linear-gradient(180deg,rgb(var(--rx-light)/.14),transparent 42%);box-shadow:inset 0 1px rgb(var(--rx-light)/.5),inset 0 0 0 1px rgb(var(--rx-light)/.05)}
	.rx-dock__aurora,.rx-dock__halo{display:none}.rx-dock--aurora .rx-dock__stage{padding:34px}.rx-dock--aurora .rx-dock__aurora,.rx-dock--aurora .rx-dock__halo{display:block;position:absolute;inset:0;pointer-events:none;border-radius:calc(var(--rr) + 34px)}.rx-dock--aurora .rx-dock__aurora{overflow:hidden;opacity:.9;filter:blur(18px) saturate(160%);mask:radial-gradient(78% 78% at 50% 55%,#000 38%,transparent 100%)}.rx-dock--aurora .rx-dock__aurora::before,.rx-dock--aurora .rx-dock__aurora::after{content:'';position:absolute;inset:-35%}.rx-dock--aurora .rx-dock__aurora::before{background:radial-gradient(40% 55% at 32% 40%,rgb(var(--rx-color)/.9),transparent 60%),radial-gradient(45% 60% at 68% 55%,hsl(from rgb(var(--rx-color)) calc(h + 65) s l/.75),transparent 62%);animation:rx-aurora-a 17s linear infinite}.rx-dock--aurora .rx-dock__aurora::after{mix-blend-mode:screen;background:radial-gradient(36% 50% at 60% 34%,hsl(from rgb(var(--rx-color)) calc(h + 40) s l/.75),transparent 60%),radial-gradient(46% 56% at 34% 64%,rgb(var(--rx-color)/.72),transparent 64%);animation:rx-aurora-b 23s linear infinite}.rx-dock--aurora .rx-dock__halo{opacity:var(--au-a,0);background:radial-gradient(120px circle at var(--aux,50%) var(--auy,50%),rgb(var(--rx-color)),transparent 60%);filter:blur(20px) saturate(160%);mix-blend-mode:screen;transition:opacity 320ms}@keyframes rx-aurora-a{50%{transform:rotate(180deg) scale(1.3) translate(3%,-2%)}to{transform:rotate(360deg) scale(1.16)}}@keyframes rx-aurora-b{50%{transform:rotate(-200deg) scale(1.38) translate(-3%,2%)}to{transform:rotate(-360deg) scale(1.22)}}
	.rx-dock--magnet .rx-dock__item{transform-origin:center;transition:transform 520ms cubic-bezier(.34,1.56,.64,1),background-color 200ms,color 200ms}.rx-dock--magnet .rx-dock__bar:global(.is-tracking) .rx-dock__item{transition:transform 170ms cubic-bezier(.22,1,.36,1),background-color 200ms,color 200ms}
	.rx-dock__goo,.rx-dock__rail{display:none}.rx-dock--gooey .rx-dock__goo{display:block;position:absolute;inset:0;z-index:0;pointer-events:none;filter:url('#rx-dock-goo')}.rx-dock__blob{position:absolute;top:0;left:0;width:var(--blob-w,var(--box));height:var(--blob-h,calc(var(--box)*.82));border-radius:calc(var(--box)*.34);background:rgb(var(--rx-color));transform:translate(var(--blob-x,0),var(--blob-y,0))}.rx-dock--gooey .rx-dock__blob--head{transition:transform 380ms cubic-bezier(.34,1.32,.5,1),width 380ms cubic-bezier(.34,1.32,.5,1),height 380ms cubic-bezier(.34,1.32,.5,1)}.rx-dock--gooey .rx-dock__blob--trail{transition:transform 620ms cubic-bezier(.5,.05,.2,1),width 620ms cubic-bezier(.5,.05,.2,1),height 620ms cubic-bezier(.5,.05,.2,1)}.rx-dock--gooey .rx-dock__item.is-active{color:rgb(var(--rx-text))}.rx-dock--gooey .rx-dock__item.is-lit{color:rgb(var(--rx-bg));background:transparent}
	.rx-dock--neon .rx-dock__bar{padding-bottom:calc(var(--pad) + 7px)}.rx-dock--neon .rx-dock__rail{display:block;position:absolute;left:0;bottom:calc(var(--pad)*.5 + 1px);z-index:0;width:var(--rail-w,0);height:2px;transform:translateX(var(--rail-x,0));border-radius:2px;background:rgb(var(--rx-color));opacity:calc(.95*var(--rail-on,0));box-shadow:0 0 6px rgb(var(--rx-color)/.9),0 0 14px rgb(var(--rx-color)/.55),0 0 26px rgb(var(--rx-color)/.32)}.rx-dock--neon.rx-dock--t-default .rx-dock__item.is-active{color:rgb(var(--rx-text))}.rx-dock--neon .rx-dock__ico{--lit:.3;filter:drop-shadow(0 0 calc(var(--lit)*3px) rgb(var(--rx-color)/calc(var(--lit)*.9))) drop-shadow(0 0 calc(var(--lit)*9px) rgb(var(--rx-color)/calc(var(--lit)*.5))) drop-shadow(0 0 calc(var(--lit)*18px) rgb(var(--rx-color)/calc(var(--lit)*.28)));transition:--lit 220ms,transform 220ms}.rx-dock--neon .rx-dock__item.is-active .rx-dock__ico{--lit:.74}.rx-dock--neon .rx-dock__item:is(:hover,:focus-visible) .rx-dock__ico{--lit:1;transform:scale(1.06)}.rx-dock--neon.is-pulse .rx-dock__item.is-active .rx-dock__ico{animation:rx-neon-pulse 2.8s ease-in-out infinite}.rx-dock--neon.is-pulse .rx-dock__item.is-active:hover .rx-dock__ico{animation:none}@keyframes rx-neon-pulse{0%,100%{--lit:.66}50%{--lit:.92}}
	.rx-dock--r-none{--rr:0px}.rx-dock--r-subtle{--rr:14px}.rx-dock--r-rounded{--rr:20px}.rx-dock--r-pill{--rr:999px}.rx-dock--r-squircle .rx-dock__bar{border-radius:var(--rr)}.rx-dock--r-squircle .rx-dock__item{border-radius:calc(var(--box)*.42)}.rx-dock.no-goo .rx-dock__goo{display:none}.rx-dock.is-disabled{opacity:.55;pointer-events:none}
	.rx-dock__glow{background:var(--rx-neighbor-ring,transparent),radial-gradient(60px circle at var(--gx,50%) var(--gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.42) 30%,rgb(var(--rx-color)/.16) 58%,transparent 82%),radial-gradient(200px circle at var(--gx,50%) var(--gy,50%),rgb(var(--rx-color)/.6),rgb(var(--rx-color)/.27) 42%,rgb(var(--rx-color)/.08) 66%,transparent 85%);opacity:max(calc(var(--glow,0)*.63),var(--rx-neighbor-lit,0))}
	@media(prefers-reduced-motion:reduce){.rx-dock__item,.rx-dock__ico,.rx-dock__bar{transform:none!important;transition:color 160ms,background-color 160ms!important;animation:none!important}.rx-dock__aurora::before,.rx-dock__aurora::after{animation:none!important}.rx-dock__sheen,.rx-dock__halo{display:none!important}.rx-dock__label{transition:none}}
	@media(pointer:coarse){.rx-dock__item,.rx-dock__ico{transform:none!important}.rx-dock--glass .rx-dock__bar{transform:none!important}.rx-dock__sheen,.rx-dock__halo{display:none!important}}
</style>
