// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import {cursor} from './cursor';
describe('cursor attachment',()=>{beforeEach(()=>{vi.stubGlobal('requestAnimationFrame',(fn:FrameRequestCallback)=>{fn(0);return 1});vi.stubGlobal('cancelAnimationFrame',vi.fn());vi.stubGlobal('matchMedia',(query:string)=>({matches:false,media:query,addEventListener:vi.fn(),removeEventListener:vi.fn()}))});afterEach(()=>{document.body.innerHTML='';vi.unstubAllGlobals()});
	it('is safe to import and creates one inert overlay',()=>{const node=document.createElement('div');document.body.append(node);const cleanup=cursor({variant:'glow'})(node);expect(document.querySelectorAll('[data-rx-cursor]')).toHaveLength(1);expect((document.querySelector('[data-rx-cursor]') as HTMLElement).style.pointerEvents).toBe('none');cleanup?.()});
	it('restores exact cursor and cleans listeners and overlay across replacement',()=>{const node=document.createElement('div');node.style.cursor='crosshair';document.body.append(node);const remove=vi.spyOn(node,'removeEventListener');const first=cursor({variant:'label'})(node);first?.();expect(node.style.cursor).toBe('crosshair');expect(document.querySelector('[data-rx-cursor]')).toBe(null);expect(remove.mock.calls.some(([type])=>type==='pointermove')).toBe(true);const second=cursor({variant:'reticle'})(node);expect(document.querySelectorAll('[data-rx-cursor]')).toHaveLength(1);second?.()});
	it('bypasses coarse pointers without mutating cursor',()=>{vi.stubGlobal('matchMedia',(query:string)=>({matches:query.includes('pointer: coarse'),media:query,addEventListener:vi.fn(),removeEventListener:vi.fn()}));const node=document.createElement('div');node.style.cursor='help';document.body.append(node);const cleanup=cursor()(node);expect(cleanup).toBe(undefined);expect(node.style.cursor).toBe('help');expect(document.querySelector('[data-rx-cursor]')).toBe(null)});
	it('mounts a distinct renderer for every source variant',()=>{const contracts={default:['.rx-cur-dot','.rx-cur-ring'],blend:['.rx-cur-blend','.rx-cur-ghost'],blob:['.rx-cur-dot'],glow:['canvas.rx-cur-canvas'],label:['.rx-cur-label'],magnet:['.rx-cur-plate','.rx-cur-field'],reticle:['.rx-cur-reticle','.rx-cur-reticle-ring','.rx-cur-corner']} as const;for(const [variant,selectors] of Object.entries(contracts)){const node=document.createElement('div');document.body.append(node);const dispose=cursor({variant:variant as keyof typeof contracts})(node),overlay=document.querySelector<HTMLElement>(`[data-rx-cursor="${variant}"]`);expect(overlay).toBeTruthy();for(const selector of selectors)expect(overlay?.querySelector(selector),`${variant} ${selector}`).toBeTruthy();dispose?.();node.remove()}});
	it('morphs label text from the source data contract',()=>{const node=document.createElement('div'),target=document.createElement('button');target.dataset.cursorText='Open';target.dataset.cursorGrow='';node.append(target);document.body.append(node);const dispose=cursor({variant:'label'})(node);target.dispatchEvent(new MouseEvent('pointermove',{bubbles:true,clientX:24,clientY:32}));const label=document.querySelector<HTMLElement>('.rx-cur-label');expect(label?.classList.contains('is-active')).toBe(true);expect(label?.textContent).toBe('Open');expect(label?.style.height).toBe('40px');dispose?.()});
	it('keeps reduced-motion renderers functional with instant following',()=>{vi.stubGlobal('matchMedia',(query:string)=>({matches:query.includes('prefers-reduced-motion'),media:query,addEventListener:vi.fn(),removeEventListener:vi.fn()}));const node=document.createElement('div');document.body.append(node);const dispose=cursor({variant:'reticle'})(node);expect(document.querySelector('[data-rx-cursor="reticle"]')).toBeTruthy();dispose?.()});
});
