<script lang="ts" module>
	import type { Snippet } from 'svelte';import type { RxColor } from '$lib/registry/lib/color';
	export interface LinkBarItem { id:string;label:string;href?:string;icon?:Snippet;disabled?:boolean }
	export interface LinkBarProps { items:LinkBarItem[];active?:string;color?:RxColor;variant?:'default'|'glow'|'magnet'|'pill'|'slide'|'underline';size?:'sm'|'md'|'lg';tone?:'default'|'danger'|'success'|'warn';separated?:boolean;strength?:number;ariaLabel?:string;onActiveChange?:(id:string)=>void }
</script>
<script lang="ts">
	import {styleColor}from'$lib/registry/lib/color';
	let {items,active=$bindable(''),color,variant='default',size='md',tone='default',separated=false,strength=8,ariaLabel='Section navigation',onActiveChange}:LinkBarProps=$props();
	let root:HTMLElement,frame=0,hovered:HTMLElement|null=null,pointerX=0,pointerY=0,ready=$state(false);let indicator=$state('opacity:0');
	function geometry(el:HTMLElement){const pad=variant==='magnet'?10:0,y=variant==='pill'||variant==='magnet'?el.offsetTop:el.offsetTop+el.offsetHeight-(variant==='slide'||variant==='underline'||variant==='default'?2:el.offsetHeight);const h=variant==='pill'?el.offsetHeight:variant==='magnet'?el.offsetHeight+2:variant==='glow'?0:2;return`opacity:1;transform:translate(${el.offsetLeft-pad}px,${y-(variant==='magnet'?1:0)}px);width:${el.offsetWidth+pad*2}px;height:${h}px`}
	function update(){const el=root?.querySelector<HTMLElement>('[aria-current="page"]');indicator=el?geometry(el):'opacity:0';ready=true}
	function select(item:LinkBarItem,event:MouseEvent){if(item.disabled){event.preventDefault();return}if(!item.href||item.href==='#')event.preventDefault();active=item.id;onActiveChange?.(item.id);queueMicrotask(update)}
	function magnet(){frame=0;if(variant!=='magnet')return;if(!hovered){update();return}indicator=geometry(hovered);const r=hovered.getBoundingClientRect(),x=(pointerX-(r.left+r.width/2))/(r.width/2),y=(pointerY-(r.top+r.height/2))/(r.height/2);hovered.style.transform=`translate(${(x*strength).toFixed(2)}px,${(y*strength).toFixed(2)}px)`}
	function observe(node:HTMLElement){root=node;const resize=new ResizeObserver(()=>{if(!hovered)update()});const mutation=new MutationObserver(update);const move=(event:PointerEvent)=>{if(variant!=='magnet')return;const next=(event.target as Element).closest<HTMLElement>('.rx-link-bar__link');if(next!==hovered){hovered?.style.removeProperty('transform');hovered=next}pointerX=event.clientX;pointerY=event.clientY;if(!frame)frame=requestAnimationFrame(magnet)};const leave=()=>{hovered?.style.removeProperty('transform');hovered=null;if(!frame)frame=requestAnimationFrame(magnet)};resize.observe(node);mutation.observe(node,{childList:true,subtree:true});node.addEventListener('pointermove',move);node.addEventListener('pointerleave',leave);document.fonts?.ready.then(update);queueMicrotask(update);return()=>{cancelAnimationFrame(frame);resize.disconnect();mutation.disconnect();node.removeEventListener('pointermove',move);node.removeEventListener('pointerleave',leave)}}
	$effect(()=>{active;variant;size;separated;queueMicrotask(update)});
</script>
<nav class="rx-link-bar rx-link-bar--{variant}" class:is-ready={ready} data-size={size} data-tone={tone} style={styleColor(color)??'--rx-color:var(--rx-primary)'} aria-label={ariaLabel} {@attach observe}>
	<span class="rx-link-bar__indicator" style={indicator} aria-hidden="true"></span>
	{#each items as item,index (item.id)}
		<a class="rx-link-bar__link" href={item.href??'#'} aria-current={active===item.id?'page':undefined} aria-disabled={item.disabled?'true':undefined} tabindex={item.disabled?-1:undefined} onclick={(event)=>select(item,event)}>{#if item.icon}<span aria-hidden="true">{@render item.icon()}</span>{/if}{#if variant==='slide'}<span class="rx-link-bar__sr">{item.label}</span><span class="rx-link-bar__track"><span class="rx-link-bar__line">{item.label}</span><span class="rx-link-bar__line rx-link-bar__line--in">{item.label}</span></span>{:else}<span>{item.label}</span>{/if}</a>
		{#if separated&&index<items.length-1}<span class="rx-link-bar__separator" aria-hidden="true"></span>{/if}
	{/each}
</nav>
<style>
	.rx-link-bar{--fs:14px;--gap:16px;position:relative;display:inline-flex;flex-wrap:wrap;align-items:center;max-width:100%;gap:var(--gap);font-family:inherit}.rx-link-bar[data-size=sm]{--fs:13px;--gap:12px}.rx-link-bar[data-size=lg]{--fs:15px;--gap:20px}.rx-link-bar--pill{--gap:6px}.rx-link-bar--glow,.rx-link-bar--magnet{--gap:18px}.rx-link-bar[data-size=sm].rx-link-bar--magnet{--gap:14px}.rx-link-bar[data-size=lg].rx-link-bar--magnet{--gap:24px}.rx-link-bar__link{position:relative;z-index:1;display:inline-flex;align-items:center;gap:6px;box-sizing:border-box;min-height:24px;color:rgb(var(--rx-text-muted));font-size:var(--fs);line-height:1;text-decoration:none;white-space:nowrap;transition:color 180ms cubic-bezier(.22,1,.36,1),transform 220ms cubic-bezier(.34,1.56,.64,1)}.rx-link-bar__link:hover,.rx-link-bar__link[aria-current=page]{color:rgb(var(--rx-text))}.rx-link-bar__link[aria-disabled=true]{opacity:.4;cursor:not-allowed}.rx-link-bar__link:focus-visible{outline:2px solid rgb(var(--rx-color));outline-offset:4px;border-radius:2px}.rx-link-bar__link:after{content:"";position:absolute;left:0;bottom:1px;width:100%;height:1px;background:currentColor;transform:scaleX(0);transform-origin:left;transition:transform 240ms cubic-bezier(.22,1,.36,1)}.rx-link-bar__link:hover:after{transform:scaleX(1)}.rx-link-bar__separator{width:1px;height:14px;align-self:center;background:rgb(var(--rx-border));opacity:.35}.rx-link-bar__indicator{position:absolute;left:0;top:0;z-index:0;width:0;height:1px;border-radius:999px;background:rgb(var(--rx-color));opacity:0;pointer-events:none;will-change:transform,width,height;transition:transform 260ms cubic-bezier(.22,1,.36,1),width 260ms cubic-bezier(.22,1,.36,1),height 200ms,opacity 180ms}
	.rx-link-bar--underline,.rx-link-bar--slide{padding-bottom:4px}.rx-link-bar--underline .rx-link-bar__link:after,.rx-link-bar--slide .rx-link-bar__link:after{display:none}.rx-link-bar--slide .rx-link-bar__indicator{transition-duration:300ms}.rx-link-bar__sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}.rx-link-bar__track{position:relative;display:block;overflow:hidden;height:1em}.rx-link-bar__line{display:block;line-height:1;transition:transform 300ms cubic-bezier(.22,1,.36,1)}.rx-link-bar__line--in{position:absolute;inset:0;color:rgb(var(--rx-color));transform:translateY(100%)}.rx-link-bar--slide .rx-link-bar__link:hover .rx-link-bar__line,.rx-link-bar--slide .rx-link-bar__link[aria-current=page] .rx-link-bar__line{transform:translateY(-100%)}
	.rx-link-bar--pill .rx-link-bar__link{padding:8px 14px;border-radius:999px}.rx-link-bar--pill[data-size=sm] .rx-link-bar__link{padding:6px 12px}.rx-link-bar--pill[data-size=lg] .rx-link-bar__link{padding:10px 18px}.rx-link-bar--pill .rx-link-bar__indicator{background:rgb(var(--rx-color)/.16);transition-duration:420ms;transition-timing-function:cubic-bezier(.34,1.56,.64,1)}.rx-link-bar--pill .rx-link-bar__link:hover{background:rgb(var(--rx-text)/.1);transform:translateY(-1px)}.rx-link-bar--glow .rx-link-bar__link:hover{text-shadow:0 0 6px rgb(var(--rx-color)/.7),0 0 16px rgb(var(--rx-color)/.45)}.rx-link-bar--glow .rx-link-bar__link[aria-current=page]{animation:rx-lb-pulse 2400ms ease-in-out infinite}.rx-link-bar--glow .rx-link-bar__indicator{display:none}.rx-link-bar--magnet .rx-link-bar__indicator{height:auto;border:1px solid rgb(var(--rx-border));background:rgb(var(--rx-text)/.07);transition-duration:380ms;transition-timing-function:cubic-bezier(.34,1.56,.64,1)}.rx-link-bar[data-tone=danger]{--rx-color:var(--rx-danger)}.rx-link-bar[data-tone=success]{--rx-color:var(--rx-success)}.rx-link-bar[data-tone=warn]{--rx-color:var(--rx-warning)}@keyframes rx-lb-pulse{0%,100%{text-shadow:0 0 4px rgb(var(--rx-color)/.3)}50%{text-shadow:0 0 8px rgb(var(--rx-color)/.65),0 0 20px rgb(var(--rx-color)/.4)}}@media(prefers-reduced-motion:reduce){.rx-link-bar__link,.rx-link-bar__indicator,.rx-link-bar__line{transition:none}.rx-link-bar--magnet .rx-link-bar__link{transform:none!important}.rx-link-bar--glow .rx-link-bar__link[aria-current=page]{animation:none}.rx-link-bar--glow .rx-link-bar__link:hover{text-shadow:none}.rx-link-bar--pill .rx-link-bar__link:hover{transform:none}.rx-link-bar--slide .rx-link-bar__line--in{display:none}.rx-link-bar--slide .rx-link-bar__link:hover .rx-link-bar__line,.rx-link-bar--slide .rx-link-bar__link[aria-current=page] .rx-link-bar__line{transform:none}}
	.rx-link-bar__link{color:rgb(var(--rx-text-secondary))}
	:root[data-theme='dark'] .rx-link-bar__line--in{color:color-mix(in srgb,rgb(var(--rx-color)) 78%,rgb(var(--rx-light)))}
</style>
