<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { RadioGroup as RadioGroupTypes } from 'bits-ui';
	import type { RxColor } from '$lib/registry/lib/color';
	import type { RadioGroupVariant } from './context';
	export interface RadioGroupProps extends Omit<RadioGroupTypes.RootProps, 'value' | 'orientation' | 'disabled' | 'children' | 'child' | 'color' | 'onValueChange'> {
		value?: string; color?: RxColor; size?: 'lg' | 'default' | 'sm'; orientation?: 'vertical' | 'horizontal';
		variant?: RadioGroupVariant; disabled?: boolean; children: Snippet; onValueChange?: (value: string) => void;
	}
</script>
<script lang="ts">
	import { setContext } from 'svelte';
	import { RadioGroup as RadioGroupPrimitive } from 'bits-ui';
	import { styleColor } from '$lib/registry/lib/color';
	import { RADIO_GROUP, type RadioGroupContext } from './context';
	let { value = $bindable(''), color, size = 'default', orientation = 'vertical', variant = 'base', disabled = false, children,
		onValueChange, class: className, style, ...restProps }: RadioGroupProps = $props();
	let root = $state<HTMLElement | null>(null), measureFrame = 0;
	setContext<RadioGroupContext>(RADIO_GROUP, { color: () => color, size: () => size, disabled: () => disabled, variant: () => variant });
	const inlineStyle = $derived(`${styleColor(color) ?? '--rx-color: var(--rx-primary)'}; ${style ?? ''}`);
	function paintIndicator() {
		measureFrame = 0;
		if (!root) return; const item = root.querySelector<HTMLElement>('.rx-radio-field:has(.rx-radio[data-state="checked"])'); if (!item) return;
		root.style.setProperty('--rx-radio-i-x', `${item.offsetLeft}px`); root.style.setProperty('--rx-radio-i-y', `${item.offsetTop}px`);
		root.style.setProperty('--rx-radio-i-w', `${item.offsetWidth}px`); root.style.setProperty('--rx-radio-i-h', `${item.offsetHeight}px`); root.dataset.ready = 'true';
	}
	function measure() { if (!measureFrame) measureFrame = requestAnimationFrame(paintIndicator); }
	$effect(() => {
		value; orientation; variant; if (!root) return; const node = root; measure();
		const resize = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(measure); resize?.observe(node);
		const mutation = new MutationObserver(measure); mutation.observe(node, { subtree: true, attributes: true, attributeFilter: ['data-state'] });
		document.fonts?.ready.then(measure); return () => { resize?.disconnect(); mutation.disconnect(); if (measureFrame) cancelAnimationFrame(measureFrame); measureFrame = 0; };
	});
</script>
<RadioGroupPrimitive.Root {...restProps} bind:ref={root} bind:value {orientation} {disabled} {onValueChange}
	class={[`rx-radio-group rx-radio-group--${orientation} rx-radio-group--${size} rx-radio-group--variant-${variant}`, className]} style={inlineStyle}>
	<span class="rx-radio-group__indicator" aria-hidden="true"></span>
	{@render children()}
</RadioGroupPrimitive.Root>
<style>
	:global {
	.rx-radio-group{--rx-radio-h:40px;--rx-radio-fs:14px;--rx-radio-px:14px;position:relative;display:inline-flex;gap:14px;font-family:inherit}.rx-radio-group--vertical{flex-direction:column;align-items:flex-start}.rx-radio-group--horizontal{flex-flow:row wrap;align-items:center;gap:22px}.rx-radio-group--sm{--rx-radio-h:32px;--rx-radio-fs:13px;--rx-radio-px:12px}.rx-radio-group--lg{--rx-radio-h:48px;--rx-radio-fs:15px;--rx-radio-px:18px}.rx-radio-group__indicator{display:none;position:absolute;z-index:0;pointer-events:none;transform:translate(var(--rx-radio-i-x),var(--rx-radio-i-y));width:var(--rx-radio-i-w,0);height:var(--rx-radio-i-h,0);opacity:0}.rx-radio-group[data-ready=true] .rx-radio-group__indicator{opacity:1}
	.rx-radio-group--variant-cards{gap:12px;max-width:100%;align-items:stretch}.rx-radio-group--variant-cards.rx-radio-group--horizontal{flex-wrap:wrap}.rx-radio-group--variant-cards .rx-radio-field{position:relative;min-width:0;min-height:calc(var(--rx-radio-h) + 12px);padding:0 calc(var(--rx-radio-px) + 6px);border:1.5px solid rgb(var(--rx-border-strong));border-radius:14px;background:rgb(var(--rx-surface));color:rgb(var(--rx-text)/.78);font-size:var(--rx-radio-fs);font-weight:500;overflow:hidden;transition:transform 260ms cubic-bezier(.34,1.56,.64,1),border-color 220ms ease,box-shadow 260ms ease,color 220ms ease}.rx-radio-group--variant-cards .rx-radio-field:hover:not(.rx-radio-field--disabled){transform:translateY(-3px);border-color:rgb(var(--rx-color)/.45);box-shadow:0 12px 26px -16px rgb(var(--rx-color)/.6)}.rx-radio-group--variant-cards .rx-radio-field:active:not(.rx-radio-field--disabled){transform:translateY(-1px)}.rx-radio-group--variant-cards .rx-radio-field:has(.rx-radio[data-state=checked]){border-color:rgb(var(--rx-color));color:rgb(var(--rx-text));box-shadow:0 0 0 1px rgb(var(--rx-color)) inset,0 12px 30px -18px rgb(var(--rx-color)/.8)}.rx-radio-group--variant-cards .rx-radio{width:20px;height:20px}.rx-radio-group--variant-cards .rx-radio[data-state=checked]{background:rgb(var(--rx-color));transform:scale(1.08)}.rx-radio-group--variant-cards .rx-radio__dot{background:rgb(var(--rx-bg));clip-path:polygon(14% 53%,38% 76%,86% 22%,96% 31%,39% 91%,4% 63%);border-radius:0;width:65%;height:65%}
	.rx-radio-group--variant-glow{gap:8px}.rx-radio-group--variant-glow.rx-radio-group--horizontal{gap:20px}.rx-radio-group--variant-glow .rx-radio-field{min-height:var(--rx-radio-h);padding:0 6px;color:rgb(var(--rx-text)/.72);font-size:var(--rx-radio-fs);font-weight:500;border-radius:10px;transition:color 220ms ease}.rx-radio-group--variant-glow .rx-radio-field:hover,.rx-radio-group--variant-glow .rx-radio-field:has(.rx-radio[data-state=checked]){color:rgb(var(--rx-text))}.rx-radio-group--variant-glow .rx-radio{width:18px;height:18px;background:rgb(var(--rx-surface));transition:border-color 260ms ease,box-shadow 320ms ease}.rx-radio-group--variant-glow .rx-radio[data-state=checked]{box-shadow:0 0 0 1px rgb(var(--rx-color)/.6),0 0 10px 1px rgb(var(--rx-color)/.55),0 0 20px 3px rgb(var(--rx-color)/.35)}.rx-radio-group--variant-glow .rx-radio.rx-radio--group-glow-fire::after{content:'';position:absolute;inset:-1.5px;border-radius:999px;border:1.5px solid rgb(var(--rx-color));animation:rx-radio-group-glow-ripple 620ms ease-out;pointer-events:none}@keyframes rx-radio-group-glow-ripple{0%{opacity:.7;transform:scale(.7)}100%{opacity:0;transform:scale(2.4)}}
	.rx-radio-group--variant-pill,.rx-radio-group--variant-segment{align-items:center;gap:4px;padding:4px;border:1.5px solid rgb(var(--rx-border-strong));border-radius:999px;background:rgb(var(--rx-surface))}.rx-radio-group--variant-pill.rx-radio-group--vertical,.rx-radio-group--variant-segment.rx-radio-group--vertical{align-items:stretch}.rx-radio-group--variant-pill .rx-radio-group__indicator,.rx-radio-group--variant-segment .rx-radio-group__indicator{display:block;border-radius:999px;background:rgb(var(--rx-color));transition:transform 420ms cubic-bezier(.34,1.56,.64,1),width 420ms cubic-bezier(.34,1.56,.64,1),height 420ms cubic-bezier(.34,1.56,.64,1),opacity 200ms ease}.rx-radio-group--variant-pill .rx-radio-field,.rx-radio-group--variant-segment .rx-radio-field{position:relative;z-index:1;justify-content:center;min-height:calc(var(--rx-radio-h) - 8px);padding:0 var(--rx-radio-px);border-radius:999px;color:rgb(var(--rx-text)/.72);font-size:var(--rx-radio-fs);font-weight:500;white-space:nowrap;transition:color 240ms ease}.rx-radio-group--variant-pill .rx-radio-field{transition:none}.rx-radio-group--variant-pill .rx-radio-field:has(.rx-radio[data-state=checked]){color:var(--rx-color-foreground,rgb(var(--rx-dark)))}.rx-radio-group--variant-pill .rx-radio-field:has(.rx-radio[data-state=checked]) .rx-radio__label>span:first-child{border-radius:2px;background:rgb(var(--rx-color));box-shadow:0 0 0 2px rgb(var(--rx-color))}.rx-radio-group--variant-pill .rx-radio,.rx-radio-group--variant-segment .rx-radio{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent}.rx-radio-group--variant-pill .rx-radio__dot,.rx-radio-group--variant-segment .rx-radio__dot{display:none}.rx-radio-group--variant-pill .rx-radio__label,.rx-radio-group--variant-segment .rx-radio__label{pointer-events:none}
	.rx-radio-group--variant-segment{gap:2px;border-width:1px;border-radius:calc(var(--rx-radio-h)/2 + 4px);isolation:isolate}.rx-radio-group--variant-segment .rx-radio-group__indicator{background:rgb(var(--rx-color)/.22);border:1px solid rgb(var(--rx-color)/.55);box-shadow:0 4px 14px -6px rgb(var(--rx-color)/.7);transition-duration:340ms;transition-timing-function:cubic-bezier(.34,1.4,.5,1)}.rx-radio-group--variant-segment .rx-radio-field{min-height:var(--rx-radio-h);color:rgb(var(--rx-text)/.62)}.rx-radio-group--variant-segment .rx-radio-field:has(.rx-radio[data-state=checked]){color:rgb(var(--rx-text))}
	.rx-radio-group--variant-slide{gap:0;isolation:isolate}.rx-radio-group--variant-slide.rx-radio-group--vertical{padding-left:12px;border-left:1px solid rgb(var(--rx-border-strong))}.rx-radio-group--variant-slide.rx-radio-group--horizontal{gap:4px;padding-bottom:8px;border-bottom:1px solid rgb(var(--rx-border-strong))}.rx-radio-group--variant-slide .rx-radio-group__indicator{display:block;border-radius:999px;background:rgb(var(--rx-color));box-shadow:0 0 10px -1px rgb(var(--rx-color)/.65);transition:transform 360ms cubic-bezier(.34,1.35,.5,1),width 360ms cubic-bezier(.34,1.35,.5,1),height 360ms cubic-bezier(.34,1.35,.5,1),opacity 160ms ease}.rx-radio-group--variant-slide.rx-radio-group--vertical .rx-radio-group__indicator{left:-12.5px;width:2px!important}.rx-radio-group--variant-slide.rx-radio-group--horizontal .rx-radio-group__indicator{bottom:-8.5px;top:auto;height:2px!important}.rx-radio-group--variant-slide .rx-radio-field{position:relative;min-height:var(--rx-radio-h);padding:0 var(--rx-radio-px);border-radius:8px;color:rgb(var(--rx-text)/.6);font-size:var(--rx-radio-fs);font-weight:500;transition:color 240ms ease,transform 340ms cubic-bezier(.34,1.35,.5,1)}.rx-radio-group--variant-slide.rx-radio-group--vertical .rx-radio-field{padding-left:4px}.rx-radio-group--variant-slide .rx-radio-field:has(.rx-radio[data-state=checked]){color:rgb(var(--rx-text))}.rx-radio-group--variant-slide.rx-radio-group--vertical .rx-radio-field:has(.rx-radio[data-state=checked]){transform:translateX(4px)}.rx-radio-group--variant-slide.rx-radio-group--horizontal .rx-radio-field:has(.rx-radio[data-state=checked]){transform:translateY(-1px)}.rx-radio-group--variant-slide .rx-radio{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent}.rx-radio-group--variant-slide .rx-radio__dot{display:none}.rx-radio-group--variant-slide .rx-radio__label{pointer-events:none}
	@media(prefers-reduced-motion:reduce){.rx-radio-group__indicator{transition:opacity 120ms ease!important}.rx-radio-group--variant-cards .rx-radio-field,.rx-radio-group--variant-glow .rx-radio-field,.rx-radio-group--variant-pill .rx-radio-field,.rx-radio-group--variant-segment .rx-radio-field,.rx-radio-group--variant-slide .rx-radio-field{transition:none}.rx-radio-group--variant-cards .rx-radio-field:hover{transform:none}.rx-radio-group--variant-glow .rx-radio.rx-radio--group-glow-fire::after{animation:none}.rx-radio-group--variant-slide .rx-radio-field:has(.rx-radio[data-state=checked]){transform:none}}
	}
</style>
